### ISSUE TITLE
Unit test coverage

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#102]
We need better unit test coverage of NAPI APIs.

Currently our test coverage consists of the test cases under `test/addons-abi`, which while better than nothing are far from exhaustive. They don't test error conditions at all, and several APIs are completely uncovered. We need to either expand these test cases or build some new test infrastructure. A problem with the way the current tests work is there isn't any way to `assert` in the C code -- all assertions are in the JavaScript code.

And then, it would be really nice to get code coverage to measure how much of the NAPI implementation code is being covered by the tests.

**Comment by mhdawson** [comment]
Unless we can do something easy, I'd be voting that we expand test/addons-abi.  Its already run by https://github.com/nodejs/abi-stable-node/issues/103 which we should be running from now on.

**Comment by mhdawson** [comment]
You can now look at the code coverage here:  https://coverage.nodejs.org, just drill down to the specific files for n-api.

**Comment by mhdawson** [comment]
The coverage in  https://coverage.nodejs.org shows as

97% for js_native_api_v8.cc and js_native_api_v8.h.

We also have efforts with lots of open test issues in node-addon-api as well as this issue to puruse fuller cover there: https://github.com/nodejs/abi-stable-node/issues/431

I think we can close this. Closing please let us know if you think that was not the right thing to do.
