### ISSUE TITLE
Make sure to run CI for all commit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#103]
Just a reminder that as discussed in the last meeting we should run this job:
```bash
https://ci.nodejs.org/view/Abi%20stable%20module%20API/job/node-test-commit-linux-abi/
```
before landing any commits and paste it into the issue for reviewers.

Its just a start as it only cover linux (and by default will only run on ubuntu) but better than nothing.

It should  be configured so that anybody from the team working on the abi stable api can start the job.

**Comment by jasongin** [comment]
Can you provide instructions? I went to that site and it's not clear to me how I would queue a CI job for my PR.

Or even better, can we have this run automatically whenever a PR is submitted/updated, and display the status on the PR page?

**Comment by mhdawson** [comment]
Closing since we've not moved over to the main repo.
