### ISSUE TITLE
tests: do a pass over the C++ portion and make sure the style is the same throughout

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#112]
For example, we might follow @jasongin's [suggestion](https://github.com/nodejs/abi-stable-node/pull/109#discussion_r102359052) and use macros to make the code more succinct.

**Comment by mhdawson** [comment]
I think that at this point we can close this since it's been a number of years and we have not action-ed (We have made many changes, introduced MACROs etc. though). Closing please let us know if you think that was not the right thing to do.
