### ISSUE TITLE
Bring all braches in sync

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#115]

**Comment by jasongin** [comment]
I backported all our V8 commits from the **api-prototype-8.x** to the **api-prototype-6.2.0** branch. Those two branches are now in sync, and NAPI tests are all passing in both.

The **api-prototype-chakracore-8.x** still needs a couple changes. ETA Monday or Tuesday.

**Comment by jasongin** [comment]
Done: api-prototype-chakracore-8.x branch is up to date also.
