### ISSUE TITLE
Convert sqllite to use NAPI

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#12]

**Comment by mhdawson** [comment]
Slowly working on it in this repo: https://github.com/mhdawson/node-sqlite3

**Comment by aruneshchandra** [comment]
Conversion should include the error handling as well

**Comment by aruneshchandra** [comment]
Waiting on #53

**Comment by mhdawson** [comment]
This issue is long stale closing. Please let us know if you think this was not the right thing to do.
