### ISSUE TITLE
Lint errors

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#126]
We have lots of lint errors both in the core files and in the add-on-tests.  We will have to fix these up before creating the PR to core:
[02:47|% 100|+ 1388|-   0]: Done                                               
/Applications/Xcode.app/Contents/Developer/usr/bin/make lint
./node tools/eslint/bin/eslint.js --cache --rulesdir=tools/eslint-rules \
	  benchmark lib test tools
src/node_asyncapi.cc:4:  Using C-style cast.  Use reinterpret_cast<napi_work_impl*>(...) instead  [readability/casting] [4]
src/node_asyncapi.cc:5:  Using C-style cast.  Use reinterpret_cast<uv_work_t*>(...) instead  [readability/casting] [4]
src/node_jsvmapi.cc:32:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:33:  public: should be indented +1 space inside class HandleScopeWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:36:  private: should be indented +1 space inside class HandleScopeWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:45:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:46:  public: should be indented +1 space inside class EscapableHandleScopeWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:53:  private: should be indented +1 space inside class EscapableHandleScopeWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:128:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:129:  public: should be indented +1 space inside class Reference  [whitespace/indent] [3]
src/node_jsvmapi.cc:144:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:146:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:146:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:174:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:176:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:176:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:189:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:189:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:194:  private: should be indented +1 space inside class Reference  [whitespace/indent] [3]
src/node_jsvmapi.cc:199:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:219:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:220:  public: should be indented +1 space inside class TryCatch  [whitespace/indent] [3]
src/node_jsvmapi.cc:234:  private: should be indented +1 space inside class TryCatch  [whitespace/indent] [3]
src/node_jsvmapi.cc:251:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:262:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:263:  public: should be indented +1 space inside class CallbackWrapperBase  [whitespace/indent] [3]
src/node_jsvmapi.cc:264:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]
src/node_jsvmapi.cc:269:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:273:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:277:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:281:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:282:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:285:  protected: should be indented +1 space inside class CallbackWrapperBase  [whitespace/indent] [3]
src/node_jsvmapi.cc:287:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:304:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:306:  public: should be indented +1 space inside class FunctionCallbackWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:317:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:321:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:325:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:327:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:342:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:348:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:350:  public: should be indented +1 space inside class GetterCallbackWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:363:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:367:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:377:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:383:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_jsvmapi.cc:385:  public: should be indented +1 space inside class SetterCallbackWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:401:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:405:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:419:  "virtual" is redundant since function is already declared as "override"  [readability/inheritance] [4]
src/node_jsvmapi.cc:424:  private: should be indented +1 space inside class SetterCallbackWrapper  [whitespace/indent] [3]
src/node_jsvmapi.cc:497:  Missing space before ( in while(  [whitespace/parens] [5]
src/node_jsvmapi.cc:522:  Missing space before ( in while(  [whitespace/parens] [5]
src/node_jsvmapi.cc:542:  Missing space before ( in while(  [whitespace/parens] [5]
src/node_jsvmapi.cc:570:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
src/node_jsvmapi.cc:576:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:580:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:581:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:692:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:692:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:704:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:704:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:727:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:772:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:785:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:810:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:852:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:869:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:914:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:943:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
src/node_jsvmapi.cc:947:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:947:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:963:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
src/node_jsvmapi.cc:967:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:967:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:979:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
src/node_jsvmapi.cc:1002:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1002:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
src/node_jsvmapi.cc:1010:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1040:  Missing spaces around =  [whitespace/operators] [4]
src/node_jsvmapi.cc:1056:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1085:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1142:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1153:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1164:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1237:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1248:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1273:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1301:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1337:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:1337:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:1470:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1483:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1495:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1515:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1516:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1529:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1530:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1531:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1550:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1577:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1591:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1614:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1624:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1629:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1630:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1632:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1644:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1666:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1684:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1708:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1720:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1721:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1722:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1738:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1739:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1758:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1760:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1790:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
src/node_jsvmapi.cc:1791:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1795:  Missing spaces around =  [whitespace/operators] [4]
src/node_jsvmapi.cc:1800:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
src/node_jsvmapi.cc:1801:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1809:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
src/node_jsvmapi.cc:1847:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1931:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1940:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:1944:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
src/node_jsvmapi.cc:2046:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:2048:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:2070:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:2087:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.cc:2179:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2179:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2182:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2182:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2185:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2185:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2188:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2188:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2191:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2191:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2194:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2194:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2197:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2197:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2200:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
src/node_jsvmapi.cc:2200:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
src/node_jsvmapi.cc:2211:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_api_helpers.h:44:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_api_helpers.h:62:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_api_helpers.h:86:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_api_helpers.h:133:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_api_helpers.h:285:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
src/node_api_helpers.h:401:  Missing space before {  [whitespace/braces] [5]
src/node_api_helpers.h:463:  At least two spaces is best between code and comments  [whitespace/comments] [2]
src/node_api_helpers.h:466:  At least two spaces is best between code and comments  [whitespace/comments] [2]
src/node_asyncapi.h:27:  At least two spaces is best between code and comments  [whitespace/comments] [2]
src/node_asyncapi.h:29:  At least two spaces is best between code and comments  [whitespace/comments] [2]
src/node_jsvmapi.h:97:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:101:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:102:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:103:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:105:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:106:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:107:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:108:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:111:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:112:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:113:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:114:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:115:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:116:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:119:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:122:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:127:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:129:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:130:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:135:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:139:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:140:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:141:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:142:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:146:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:166:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:210:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:213:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:226:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:235:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:241:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:251:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:255:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:256:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:257:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:259:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:261:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:262:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:264:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:266:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:268:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:270:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:271:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:273:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:275:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:289:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:306:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:309:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:310:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:312:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:314:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:316:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:317:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:318:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:319:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:320:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:321:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:322:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:323:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:324:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node_jsvmapi.h:326:  At least two spaces is best between code and comments  [whitespace/comments] [2]
src/node_macros.h:20:  At least two spaces is best between code and comments  [whitespace/comments] [2]
test/addons-abi/6_object_wrap/myobject.cc:5:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/6_object_wrap/myobject.cc:25:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/6_object_wrap/myobject.cc:187:  Do not use variable-length arrays.  Use an appropriately named ('k' followed by CamelCase) compile-time constant for the size.  [runtime/arrays] [1]
test/addons-abi/7_factory_wrap/myobject.cc:22:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/7_factory_wrap/myobject.cc:47:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
test/addons-abi/7_factory_wrap/myobject.cc:47:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
test/addons-abi/7_factory_wrap/myobject.cc:66:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/8_passing_wrapped/binding.cc:49:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/8_passing_wrapped/myobject.cc:45:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
test/addons-abi/8_passing_wrapped/myobject.cc:45:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
test/addons-abi/8_passing_wrapped/myobject.cc:63:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_array/test_array.cc:62:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
test/addons-abi/test_array/test_array.cc:62:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
test/addons-abi/test_array/test_array.cc:65:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
test/addons-abi/test_array/test_array.cc:65:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
test/addons-abi/test_buffer/test_buffer.cc:7:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_buffer/test_buffer.cc:24:  Using C-style cast.  Use reinterpret_cast<char *>(...) instead  [readability/casting] [4]
test/addons-abi/test_buffer/test_buffer.cc:38:  Almost always, snprintf is better than strcpy  [runtime/printf] [4]
test/addons-abi/test_buffer/test_buffer.cc:102:  Using C-style cast.  Use reinterpret_cast<char *>(...) instead  [readability/casting] [4]
test/addons-abi/test_buffer/test_buffer.cc:111:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_object/test_object.cc:43:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_object/test_object.cc:96:  Do not use variable-length arrays.  Use an appropriately named ('k' followed by CamelCase) compile-time constant for the size.  [runtime/arrays] [1]
test/addons-abi/test_object/test_object.cc:98:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_object/test_object.cc:191:  Do not use variable-length arrays.  Use an appropriately named ('k' followed by CamelCase) compile-time constant for the size.  [runtime/arrays] [1]
test/addons-abi/test_object/test_object.cc:193:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_string/test_string.cc:31:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_symbol/test_symbol.cc:31:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_symbol/test_symbol.cc:64:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_typedarray/test_typedarray.cc:70:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_typedarray/test_typedarray.cc:74:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/test_typedarray/test_typedarray.cc:84:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
test/addons-abi/test_typedarray/test_typedarray.cc:84:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
test/addons-abi/test_typedarray/test_typedarray.cc:92:  An else should appear on the same line as the preceding }  [whitespace/newline] [4]
test/addons-abi/test_typedarray/test_typedarray.cc:92:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
test/addons-abi/test_typedarray/test_typedarray.cc:111:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/7_factory_wrap/myobject.h:10:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
test/addons-abi/8_passing_wrapped/myobject.h:10:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Total errors found: 259
make[1]: *** [cpplint] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by mhdawson** [comment]
The above is from '''make cpplint'''.  There are also issues in the test files from '''make lint'''

**Comment by digitalinfinity** [comment]
@mhdawson have you already started on this? If not, I'm happy to take a crack at fixing these

**Comment by digitalinfinity** [comment]
Fixed with #139 and #140.
