### ISSUE TITLE
Project naming terminology

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#130]
I'm still not quite sure what this project is supposed to be called officially. We need to decide on terminology and straighten out the names so that they are consistent everywhere before submitting the PR to node. We have a variety of terms that all are referring to basically the same concept, including:

Thing | Current Naming
--- | ---
GitHub repos prefix | `abi_stable_node`
Prefix on all the APIs and types | `napi_`
Main C header file | `node_jsvmapi.h`
Tests directory | `addons-abi`
C++ wrapper header file | `napi.h`
C++ namespace | `Napi`
Module registration callback typedef | `addon_abi_register_func`
Module registration macro | `NODE_MODULE_ABI`
C++ wrapper NPM package name | ([Related PR](https://github.com/nodejs/abi-stable-node-wrapper/pull/2))

I called out that module registration callback typedef because it uses a different prefix from all the typedefs.

**Comment by kkoopa** [comment]
May I suggest calling the C++ part NAN 3.0? A familiar name would likely encourage its use, which in turn would lead to greater use of the ABI stable API. The need for evangelization would also be reduced, leaving room to focus on the new improvements, like the stable ABI and new design. People would already know what it is supposed to do.

**Comment by jasongin** [comment]
@kkoopa I mostly agree; in some ways it would make a lot of sense to be NAN 3.0.

A reason we might not want to do that is that we're not necessarily trying to deprecate or prevent direct usage of the V8 APIs by native modules. Some native modules, hopefully a very small subset, may still need to call V8 APIs directly if they need to do something unusual that is very engine-specific. ([`deasync`](https://github.com/abbr/deasync) might be an example.) Or maybe in extreme cases it may be necessary to optimize performance while sacrificing portability. For those uses, it might still be helpful to the current style of NAN abstractions for the V8 APIs. Or maybe those would be rare enough that they can get by without NAN.

I'm curious what others think about this.

**Comment by NickNaso** [comment]
Hi everyone,
i agree with @jasongin  what you said is really true. I like your idea to call it NAPI as reported here https://github.com/nodejs/abi-stable-node-wrapper/pull/2 
Personally i also change all the names to be consistent to the project's name.

**Comment by mhdawson** [comment]
We discussed in last weekly NAPI meeting. @aruneshchandra  should add extra row to table to show our current suggestions.

**Comment by mhdawson** [comment]
We should also add these to the list:

node_asyncapi.cc  node_asyncapi.h  node_asyncapi_internal.h  node_asyncapi_types.h

as they will part of the PR.

**Comment by aruneshchandra** [comment]
Thing | Current Naming | New Naming
--- | --- |---
GitHub repos prefix | `abi_stable_node` |`node_api`
Prefix on all the APIs and types | `napi_`|`napi_`
Main C header file | `node_jsvmapi.h`|`node_api.h`
Tests directory | `addons-abi`|`addons-napi`
C++ wrapper header file | `napi.h`| TBD
C++ namespace | `Napi`|TBD
Module registration callback typedef | `addon_abi_register_func`|`napi_addon_register_func`
Module registration macro | `NODE_MODULE_ABI`|`NAPI_MODULE`
C++ wrapper NPM package name | ([Related PR](https://github.com/nodejs/abi-stable-node-wrapper/pull/2))|TBD

**Comment by jasongin** [comment]
Thanks @aruneshchandra. I'll prepare a PR with these renames soon.

> node_asyncapi.cc node_asyncapi.h node_asyncapi_internal.h node_asyncapi_types.h

I'm not sure those should be included. Maybe we should leave them out initially, and add them in later if we conclude they are needed.

**Comment by mhdawson** [comment]
Are there calls for libuv that are used directly in the C++ wrapper other than these ?  I not then I think we should include them.  If there are others we should look at those and have the larger discussion.

**Comment by jasongin** [comment]
Fixed by #158
