### ISSUE TITLE
Delete node_api_helpers.h and update code that used it

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#136]
Helper classes in `node_api_helpers.h` rely heavily on `napi_get_current_env()`. That is not a pattern we want to promote, and we're probably removing that API anyway.

I already built new equivalents for all the helper classes there, we just need to port the code. That includes a couple of the test cases long with leveldown, nanomsg, and maybe iotivity.

I already started a leveldown port, and I have some updates pending for the C++ classes that make them easier to use when mixing usage of the C and C++ NAPI APIs.

**Comment by sampsongao** [comment]
Closed in e057a6f974203ad667b460521ced4b818cec4814
