### ISSUE TITLE
Final Validation

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#138]
Please update this list with the status 

- [x] macOS validation
- [x] CI (internal and node) run - @jasongin 
- [x] Addon examples - @sampsongao 
- [x] Build and Unit Test for LevelDown - @jasongin 
- [x] Build and Unit Test for Nanomsg - @sampsongao 
- [x] Build and Unit Test for Canvas - @jasongin 
- [x] Build and Unit Test for Node-Sass - @boingoing 
- [x] Build and Unit Test for IoTivity - @gabrielschulhof 
- [x] Update Readme Status - @aruneshchandra
- [x] Draft PR Description - @mhdawson 
- [x] Open PR to Node.js Master - @jasongin

**Comment by jasongin** [comment]
As preparation for final validation, and to make creation of the PR easier, today I merged the latest from node/master into api-prototype-8.x, as https://github.com/nodejs/abi-stable-node/commit/795ba36d24ee35a6b535f06e143c0486d27c67e2. The CI still passes.

I may have to pick up a few more changes from node/master before I make the PR, but it won't be much if anything.

**Comment by gabrielschulhof** [comment]
iotivity-node is green against 7e2cbb944c07e25298a30a5372c3d01c79314a43.

**Comment by jasongin** [comment]
Canvas and leveldown are validated against the staged PR on Windows and Mac.

**Comment by digitalinfinity** [comment]
@mhdawson can you help with triggering the Node CI run on Jason's branch
@sampsongao do you have any update on whether Addon Examples have been updated to work with the new NAPI APIs

@aruneshchandra @jasongin has done basic validation on macOS. @boingoing is validating node-sass. Do we need to verify anything else beyond what the Node CI will validate?

**Comment by mhdawson** [comment]
Closing as this is done.
