### ISSUE TITLE
Linker Error in LevelDown for AsyncQueueWorker symbol

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#14]
After commit 8413f2a5c56e371a1f536dae3ec1d8441e3ebdea we are seeing a Linker error in LevelDown

**Comment by digitalinfinity** [comment]
@aruneshchandra can you paste the link error here? is this in node-chakracore or node-v8?

**Comment by aruneshchandra** [comment]
`C:\git\leveldown>node-gyp rebuild --nodedir=c:\git\src-node-v8 --release --x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.6.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\archandr\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\git\\leveldown\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\archandr\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\git\\src-node-v8\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=c:\\git\\src-node-v8',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\archandr\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\git\\leveldown',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\git\\leveldown\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  leveldb.vcxproj -> C:\git\leveldown\build\Release\\leveldb.lib
  snappy.vcxproj -> C:\git\leveldown\build\Release\\snappy.lib
  batch.cc
  batch_async.cc
  database.cc
  database_async.cc
  iterator.cc
  iterator_async.cc
  leveldown.cc
  leveldown_async.cc
  win_delay_load_hook.cc
     Creating library C:\git\leveldown\build\Release\leveldown.lib and object C:\git\leveldown\build\Release\leveldown.
  exp
batch.obj : error LNK2001: unresolved external symbol "void __cdecl Napi::AsyncQueueWorker(class Napi::AsyncWorker *)"
(?AsyncQueueWorker@Napi@@YAXPEAVAsyncWorker@1@@Z) [C:\git\leveldown\build\leveldown.vcxproj]
C:\git\leveldown\build\Release\leveldown.node : fatal error LNK1120: 1 unresolved externals [C:\git\leveldown\build\lev
eldown.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\archandr\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\archandr\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--nodedir=c:\\git\\src-node-v8" "--release" "--x64"
gyp ERR! cwd C:\git\leveldown
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok`

**Comment by aruneshchandra** [comment]
<img width="1280" alt="error" src="https://cloud.githubusercontent.com/assets/12057627/20025699/39e339c0-a2ae-11e6-9837-d9bdf7a60c03.png">

**Comment by digitalinfinity** [comment]
@sampsongao looks like this was caused by 8413f2. If the AsyncWorker methods are part of the NAPI interface, then they should not be in a namespace since NAPI needs to be a flat C API. If they're just C++ sugar, then the implementation needs to be moved back into the header, the way it was before.

The reason it fails on Windows is that VC++ doesn't export all symbols in a shared library by default- they need to be declspec-ed or listed out explicitly in the .DEF file. Looks like the general behavior of clang/gcc is to export by default in a shared library.

**Comment by sampsongao** [comment]
Does the newest commit (d8a0d972e6c6adc218f38ef650fe28eabb7520b4)fix it?

**Comment by boingoing** [comment]
This fix unblocks the leveldown build against node 6 but it seems pretty roundabout. Can we remove these three inlined functions from the Napi namespace?
```
inline void Napi::AsyncExecute(uv_work_t* req)
inline void Napi::AsyncExecuteComplete(uv_work_t* req)
inline void Napi::AsyncQueueWorker(AsyncWorker* worker)
```
And change the module code to call the EXTERN functions directly?
```
NODE_EXTERN void napi_async_execute(uv_work_t* req);
NODE_EXTERN void napi_async_execute_complete(uv_work_t* req);
NODE_EXTERN void napi_async_queue_worker(void* worker);
```
The functions in the Napi namespace really can't be called from the module code since they are in a namespace which will get name-mangled. I believe this is only working now because those functions are getting inlined. But it doesn't seem we need the functions in Napi namespace at all if they just directly forward to these EXTERN'd functions.

**Comment by sampsongao** [comment]
The first two can be removed since I think the developer is not using it. But the AsyncQueueWorker is used in module code, so I think we will keep it for now. By the way, I am working on separating the libuv api and C++ helpers into new sets of files, I will see if I can make it simpler.
