### ISSUE TITLE
Warning when abi-addon on tests run

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#144]
Warning when abi-addon on tests run

Lots of warnings in the CI runs:
https://ci.nodejs.org/job/node-test-commit-linux-abi/nodes=ubuntu1404-64/23/console

As one example:
```
test/addons/null-buffer-neuter/build'
  CXX(target) Release/obj.target/binding/binding.o
../test_string.cc: In function 'void Init(napi_env, napi_value, napi_value)':
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::getter' [-Wmissing-field-initializers]
   };
   ^
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::setter' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::value' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::attributes' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::data' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::getter' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::setter' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::value' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::attributes' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::data' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::getter' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::setter' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::value' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::attributes' [-Wmissing-field-initializers]
../test_string.cc:123:3: warning: missing initializer for member 'napi_property_descriptor::data' [-Wmissing-field-initializers]
  SOLINK_MODULE(target) Release/obj.targ
```

**Comment by gabrielschulhof** [comment]
@jasongin tells me this is gcc being overly paranoid and that the initializer in question fully complies with the standard.

**Comment by jasongin** [comment]
While that's true (and there are no warnings on Windows builds), we should probably change the code anyway to clean up the gcc warnings.

**Comment by boingoing** [comment]
@sampsongao 

Noticed you assigned this to yourself, did you already fix the warnings? I was thinking of taking this up if it's not already in-progress.

**Comment by digitalinfinity** [comment]
@mhdawson given that the initializer is actually correct, is this a must have for milestone 6?

@sampsongao @jasongin and I were talking about this offline- I think the consensus is to go down the macro route for readability. You might want to consider fixing #112 too while fixing this. We were imagining the macros taking either one of the two following forms:
`#define DEFAULT_ATTR 0, 0, 0, napi_default, 0`
or 
`#define DECLARE_NAPI_PROPERTY(varName, propName, method) napi_property_descriptor varName = { propName, method, 0, 0, 0, napi_default, 0 }`

And then something like `napi_property_descriptor desc = { "hello", Method };` can be rewritten as either  `napi_property_descriptor desc = { "hello", Method, DEFAULT_ATTR };` or `DECLARE_NAPI_PROPERTY(desc, "hello", Method)`.

Thoughts?

**Comment by sampsongao** [comment]
I don't know why should we introduce new macros while removing NAPI_METHOD and NAPI_MODULE_I. Or are the new macros just for internal, like for our addons-abi tests?

**Comment by jasongin** [comment]
Yes, Hitesh is only suggesting adding common macros for tests, not in the public header.

**Comment by jasongin** [comment]
Fixed by https://github.com/nodejs/abi-stable-node/pull/156
