### ISSUE TITLE
Recently landed changes have broken tests/CI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#148]
https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/30/nodes=ubuntu1404-64/console

```
gyp info spawn args   '-Goutput_dir=.' ]
../test_function.cc: In function 'void Init(napi_env, napi_value, napi_value)':
../test_function.cc:52:65: error: cannot convert 'void (*)(napi_env, napi_callback_info) {aka void (*)(napi_env__*, napi_callback_info__*)}' to 'const char*' for argument '2' to 'napi_status napi_create_function(napi_env, const char*, napi_callback, void*, napi_value__**)'
   status =  napi_create_function(env, Test, nullptr, nullptr, &fn);
                                                                 ^
make[2]: *** [Release/obj.target/test_function/test_function.o] Error 1
```

Likely https://github.com/nodejs/abi-stable-node/pull/142. Looks like code was changed after last succefull CI run.

@boingoing

**Comment by boingoing** [comment]
My mistake. This broke when I changed the parameter order to napi_create_function. I fixed the other uses but missed this one.

**Comment by boingoing** [comment]
Prepared a fix https://github.com/nodejs/abi-stable-node/pull/149

**Comment by boingoing** [comment]
Fixed by https://github.com/nodejs/abi-stable-node/pull/149
