### ISSUE TITLE
NAPI Documentation

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#153]
- [x] Getting Started - Hitesh/Michael 
- [x] Data Types and Values (convert to and from C) - Hitesh
- [x] Abstract Operations (return napi objects or tell you the type) - Hitesh
- [x] Functions to call into JS - Hitesh
- [x] Functions to call back from JS  - Hitesh
- [x] Error Handling - Michael 
- [x] Memory Management - Michael 
- [x] Async APIs - Michael 
- [x] Module Registration  - Michael 
- [x] ObjectWrap - Jason

**Comment by digitalinfinity** [comment]
Related C++ issue: https://github.com/nodejs/node-api/issues/6

**Comment by jasongin** [comment]
Maybe there should be another section about **Properties**: getting, setting, and defining them.

**Comment by digitalinfinity** [comment]
Added and self-assigned for now 😄

**Comment by digitalinfinity** [comment]
I had a bunch of these docs sitting on my machine for a couple weeks- dusted them off, updated with the API changes since then and opened PRs #215, #216, #217, #218 and #219

**Comment by mhdawson** [comment]
Will try to add my 2 cents tomorrow

**Comment by aruneshchandra** [comment]
This is done and live
https://nodejs.org/dist/latest-v7.x/docs/api/n-api.html
