### ISSUE TITLE
Latin1 string encoding

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#179]
N-API currently supports UTF-8 and UTF-16 string encoding. V8 additionally supports latin1 string encoding, called "OneByte" strings in the V8 APIs, and it is widely used.

Proposed additional APIs:
 - `napi_create_string_latin1`
 - `napi_get_value_string_latin1_length`
 - `napi_get_value_string_latin1`

**Comment by aruneshchandra** [comment]
We will take this up after the PR lands.

**Comment by sampsongao** [comment]
#192

**Comment by jasongin** [comment]
Closing since this was done and merged into node.
