### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#18]
# Roadmap

✅ **Milestone 1** - Initial API Implementation (DONE except landing EP)
  * Initial concept defined in EP
  * Initial API 
  * All [NaN examples](https://github.com/nodejs/abi-stable-node-addon-examples) running
  * Implementation of initial modules ([`leveldown`](https://github.com/boingoing/leveldown/) and [`nanomsg`](https://github.com/sampsongao/node-nanomsg))

✅ **Milestone 2** - Ports across versions and runtimes
  * Ports to ChakraCore (7.x)
  * Ports across versions (0.10.x, 0.12.x, 6.2.x, 7.x)
  * [Performance Eval](https://github.com/nodejs/abi-stable-node/issues/8#issuecomment-260032253) of initial implementation

✅ **Milestone 3** - Demo for Node Interactive

✅ **Milestone 4** - Full error handling
  * Land EP as a draft after CTC Review
  * Addition of full error handling
  * Broad analysis of V8 API usage in top 30 most downloaded native modules    
  * Investigate `canvas`
  * Evaluate Performance 

✅ **Milestone 5** - API feature complete (VM summit Readiness)
  * Full API checked in to abi-stable-node and up to date with current Node.js master
  * Update ports to head of v6, v8, ChakraCore-master
  * Enable build flag for experimental support for NAPI
  * Complete porting [`IoTivity`](https://github.com/gabrielschulhof/iotivity-node/tree/abi-stable)
  * Convert most depended on native module `node-sass`
  * Convert native module from CITGM List `canvas` 
  * Community review checkpoint and update EPS
  * Demo 

✅ **Milestone 6** - Land in master as Experimental - Targeting Node version 8.0
* Submit PR to Node master 
* Land N-API in Node 8.0

**Milestone 7** - Community Outreach
* Documentation for migrating existing Native modules to NAPI 
* Automation for Migration assistance 
* Blog: call to action for community / early adopters

**Comment by Fishrock123** [comment]
@mhdawson could you convert this to a checklist for better visibility of the status?

**Comment by aruneshchandra** [comment]
Updated the roadmap for better progress visibility and current status.

**Comment by MylesBorins** [comment]
Are we on target for this to land in 8 as mentioned in milestone 5?

edit: can we expand on what "experimental" means in the roadmap

**Comment by aruneshchandra** [comment]
@TheAlphaNerd - IIRC from VM Summit 2, experimental means this will be available behind a config flag for version 8 and previous 1 or 2 LTSes. 

As per being on target - its unclear at the moment, how much can be achieved by the time we cut a build for version 8. But Milestone 5 is what we are shooting for with the number of people who are working on it today. By VM Summit 3 (March 2017) we will have a better idea.

**Comment by RReverser** [comment]
Sorry for commenting on a probably inappropriate issue, but the Hangout link in the README seems dead. Are you still doing meetings? I'm trying to implement N-API on a somewhat unusual target and got quite a few questions/suggestions that would love to discuss. cc @nodejs/n-api

**Comment by aruneshchandra** [comment]
@RReverser - the link is not dead. The meetings are on Thursdays 10.30 Pacific / 1:30 Eastern US time.  We would love to hear about your project and your feedback. Please join us this Thursday on June 8th.

**Comment by RReverser** [comment]
@aruneshchandra 

> the link is not dead

Well it returns 404 to me :/
<img width="677" alt="screen shot 2017-06-05 at 16 35 29" src="https://cloud.githubusercontent.com/assets/557590/26790815/07c183aa-4a0d-11e7-9dca-a51d69f02c7b.png">

> The meetings are on Thursdays 10.30 Pacific / 1:30 Eastern US time. We would love to hear about your project and your feedback. Please join us this Thursday on June 8th.

Thanks!

**Comment by aruneshchandra** [comment]
How about this URL ?
https://plus.google.com/events/c0eevtrlajniu7h8cjrdk0f56c8?authkey=COH04YCalJS8Ug

**Comment by RReverser** [comment]
Same. Perhaps one needs to be invited to be able to access it?

**Comment by RReverser** [comment]
Ha, it opens when I open in incognito mode. So certainly something to do with permissions. Let me try from another Google account.

**Comment by aruneshchandra** [comment]
I don't think this is an invite only link - coz we had someone join without invitation last week. @sampsongao - can you please check ?

**Comment by RReverser** [comment]
Apparently, it has something to do with Google Apps (I have Google account on custom domain) + Google Plus Events links. https://www.reddit.com/r/google/comments/5b11gw/google_events_gone_for_good/

Direct hangout link should work. Could someone please send me an invite for hangout itself to me@rreverser.com? Thanks!

**Comment by mhdawson** [comment]
@sampsongao can you send @RReverser a direct invitation.

**Comment by RReverser** [comment]
@sampsongao Friendly ping (and sorry for the hassle).

**Comment by sampsongao** [comment]
@RReverser Invitation sent. Have you receive it?

**Comment by RReverser** [comment]
<s>@sampsongao Received it, but it contains the same link to the event itself and not to hangout, so still 404. This becomes weirdly complicated...

Sorry for bothering again, but is there a way to extract `https://hangouts.google.com/hangouts/_/{id}` link from the event page? I wonder if that `id` is same as the event id and I will be able to just substitute or I should register a separate `gmail.com` address just to join...</s>

Got direct link to a hangout, all good now, thanks!

**Comment by Silur** [comment]
any plans about when this will grow out the experimental status?
how can we help to accelerate it?

**Comment by addaleax** [comment]
@Silur actually, yes: https://github.com/nodejs/node/issues/14532

**Comment by gabrielschulhof** [comment]
@nodejs/n-api can we close this issue?

**Comment by mhdawson** [comment]
I think so, closing.
