### ISSUE TITLE
Create a test addon in C

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#183]
Add an addon to the addons-napi test suite that is written in C.

**Comment by gabrielschulhof** [comment]
Actually, I'm thinking about converting test/addons-napi rather than adding one. Shouldn't be a big deal since they're already written in C.

**Comment by gabrielschulhof** [comment]
Ugh! There's no `bool` in C by default - at least the way addons are built in test/addons-abi.

**Comment by jasongin** [comment]
Can we typedef it, like I did for `char16_t`?

**Comment by gabrielschulhof** [comment]
Yeah.
```C
#include <stdbool.h>
```
We also need a bunch of
```C
#ifdef __cplusplus
extern "C" {
#endif /* def __cplusplus */
...
#ifdef __cplusplus
} // extern "C"
#endif /* def __cplusplus */
```

**Comment by gabrielschulhof** [comment]
My PR will have these changes. The existing addons-napi are trivial to convert so far.
