### ISSUE TITLE
Remove [=yes|no] from runtime flag

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#184]

**Comment by jasongin** [comment]
At the same time, we should also update the error message to mention the runtime flag, as [suggested in this comment](https://github.com/nodejs/node/pull/11975#discussion_r107325207)?

**Comment by gabrielschulhof** [comment]
Definitely.

*  [ ] Remove yes/no
*  [ ] update docs
*  [ ] mention runtime flag in error
