### ISSUE TITLE
Use ref/unref terminology instead of addref/release

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#188]
Consider renaming:
 - `napi_reference_addref()`
 - `napi_reference_release()`

To:
 - `napi_reference_ref()`
 - `napi_reference_unref()`

To be consistent with the "Ref/Unref" terminology used throughout Node.js.

See https://github.com/nodejs/node/pull/11975#discussion_r107326862

**Comment by boingoing** [comment]
Fixed by #193
