### ISSUE TITLE
Consider "new.target" for constructor callbacks

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#200]
Reference https://github.com/nodejs/node/pull/11975#discussion_r108027972, https://github.com/nodejs/node/pull/9293, https://github.com/nodejs/node/issues/10915

In mixed JS/native inheritance scenarios, it can be necessary to get the "new target" for the constructor, via `v8::FunctionCallbackInfo<T>::NewTarget()`. In N-API this would be exposed as `napi_get_cb_new_target()` or something similar.

**Comment by boingoing** [comment]
Should this be added as an optional out parameter to ```napi_get_cb_info```? If we remove the other methods in this family since one method could handle all of their use cases, it seems to make sense. Would make sense to do that together with #196.

**Comment by jasongin** [comment]
@boingoing I don't think it should be added to `napi_get_cb_info()` because it would be very rarely needed, only by _some_ constructors. Maybe it could be combined with `napi_is_construct_call()` into a `napi_get_cb_construct_info()` or something like that.

**Comment by boingoing** [comment]
>Maybe it could be combined with napi_is_construct_call() into a napi_get_cb_construct_info() or something like that.

This sounds like a good plan to me. Only constructors would be interested in this flag or new.target generally.

**Comment by jasongin** [comment]
Actually a callback is a constructor call if and only if a new target is defined. So I think we can just change `napi_is_construct_call()` to `napi_get_new_target()`.

**Comment by mhdawson** [comment]
That makes sense to me.

**Comment by sampsongao** [comment]
https://github.com/nodejs/node/pull/14698

**Comment by mhdawson** [comment]
Looks like related PR landed, closing.
