### ISSUE TITLE
APIs for ES6 DataView

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#202]
N-API currently has APIs for `ArrayBuffer` and `TypedArray` classes, but not the `DataView` class. [The `DataView` class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) is specified by ES6 as another kind of view over an `ArrayBuffer`.

While it could be possible to extend (and rename?) `napi_create_typedarray()` and `napi_get_typedarray_info()` to also support `DataView` objects, I think the combination would be too confusing, because a `DataView` doesn't have a type, and measures length in terms of bytes instead of elements. So, probably there should be separate APIs:

 - `napi_is_dataview()`
 - `napi_create_dataview()`
 - `napi_get_dataview_info()`

**Comment by jasongin** [comment]
Related to https://github.com/nodejs/node/pull/11975#discussion_r108029186

**Comment by mhdawson** [comment]
https://github.com/nodejs/node/issues/13926

**Comment by shivanth** [comment]
I'm taking this up :-)

**Comment by digitalinfinity** [comment]
@shivanth thanks- might want to comment on nodejs/node#13926 so that people there know 😄

**Comment by digitalinfinity** [comment]
Landed in https://github.com/nodejs/node/pull/14382
