### ISSUE TITLE
Cache the Symbol.hasInstance value

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#209]
For the V8 implementation of `napi_instanceof`, we look up the value of [`Symbol.hasInstance`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance), so that we can check if a particular constructor has customized the `instanceof` behavior.

As an optimization, the `Symbol.hasInstance` value could be cached (for each `napi_env`), which will save some extra work of looking it up for each call to `napi_instanceof`.

**Comment by jasongin** [comment]
This was suggested in the node/master PR comment: https://github.com/nodejs/node/pull/11975#discussion_r108028981

**Comment by gabrielschulhof** [comment]
I can take this once #208 lands.

**Comment by mhdawson** [comment]
Closing as this has landed in master.
