### ISSUE TITLE
[Discussion] List of most popular binary modules

### ISSUE THREAD

**Issue by indexzero** [nodejs/abi-stable-node#22]
Updated `npm-pkg-top` to use the modern skimdb URLs. The results are below sorted by npm stars, github stars, and number of dependent public modules:

```
 #  npm git  dep pkg               
 1  153 0    973 node-sass         
 2  95  1928 565 sqlite3           
 3  214 0    524 bcrypt            
 4  52  0    483 serialport        
 5  131 0    441 phantomjs         
 6  28  239  435 hiredis           
 7  75  3617 354 canvas            
 8  51  1525 326 websocket         
 9  40  0    272 phantomjs-prebuilt
 10 15  261  256 deasync           
 11 14  358  217 leveldown         
 12 18  0    199 nodegit           
 13 40  2484 198 fibers            
 14 44  1473 189 zmq               
 15 21  520  169 iconv             
 16 48  0    167 electron-prebuilt 
 17 21  0    161 libxmljs          
 18 6   0    154 radium            
 19 16  1740 128 ffi               
 20 9   0    117 microtime         
```

You can run this yourself by:

```
npm i -g npm-pkg-top
npm-pkg-top --save-query 'npm.json' --username='VALID_GITHUB_USERNAME' --password='VALID_GITHUB_PASS'
```

**Comment by MylesBorins** [comment]
currently in citgm we are testing

* bcrypt
* serialport
* levedown

We are in the process of adding

* node-sass
  - The test suite + build rely on a git submodule
  - /cc xzyfer

We currently cannot add

* PhantomJS / phantomjs-prebuilt
  -  The npm package is actually a wrapper and not official release
  -  The build system is bespoke
  -  /cc @ariya
* hiredis
  - will need redis on system
* canvas
  - requires cairo

I will attempt to add the following modules and update accordingly:

#### working (testing on OSX)

* sqlite3
* iconv
* electron-prebuilt
* libxmljs
* radium
* ffi
* microtime

#### not working
* websocket
  - appears to hang during test phase
  - no problems when manually testing github tarball
* deasync
  - does not support `npm test`
* nodegit
  - `lib/` is not included in release tarball
  - not able to run tests on published releases
* fibers
  - latest version is not published to github as tarball
* zmq
  - requires `libzmq`

running the new modules in citgm: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/463/

**Comment by aruneshchandra** [comment]
Thanx for this list @indexzero @TheAlphaNerd 

Is there an easy way to get a list of top downloaded native modules ?

**Comment by xzyfer** [comment]
I'd also suggest `fsevents` as a widely popular native extension. It's a transitive dependency for many large projects, including node-sass. As a result it doesn't get many stars directly.

**Comment by kunalspathak** [comment]
@TheAlphaNerd , if not already supported, how easy would it be to have a flag in citgm that will run test suites of most popular node modules that `npm-pkg-top` returns?

**Comment by MylesBorins** [comment]
@kunalspathak 

here is the list... fun emoji

✅ Got it
📛 Not compatible (yet)
🆕 TBD

data:    1  155 0   983 node-sass 📛
data:    2  95  0   578 sqlite3 ✅
data:    3  214 0   530 bcrypt ✅
data:    4  52  0   485 serialport ✅
data:    5  132 0   440 phantomjs 📛
data:    6  28  0   436 hiredis 📛
data:    7  75  0   355 canvas 📛
data:    8  51  0   325 websocket 📛
data:    9  41  0   275 phantomjs-prebuilt 📛
data:    10 16  0   260 deasync 📛
data:    11 14  0   218 leveldown ✅
data:    12 40  0   200 fibers 📛
data:    13 18  0   198 nodegit 📛
data:    14 44  0   189 zmq 📛
data:    15 21  0   169 iconv ✅
data:    16 48  0   167 electron-prebuilt ✅
data:    17 21  0   161 libxmljs ✅
data:    18 7   0   155 radium ✅
data:    19 16  0   127 ffi ✅
data:    20 9   0   116 microtime ✅

edit: to expand... we need to manually add / test each module to make sure it complies and add information to a lookup table for the prefix used in release, just in case they do something unconventional. So as such we can't add a flag to test specific modules. that being said, as you can see a very large portion of the top modules are already being tested! We can likely add a few more to the lookup table based on the notes I made above

**Comment by jjrv** [comment]
Is there any chance you could check out [nbind](https://github.com/charto/nbind#readme) as an alternative API for communicating between Node.js and C++ addons? It's a replacement for NAN (built on top of it) and I'm porting it to support NAPI.

It doesn't just replace V8 types with more portable ones, but instead simply uses C++ standard library types. Typically porting a NAN project to nbind mainly involves removing all existing binding code, listing class and method names, and then it just works. However, I've only tested that with small projects. Bigger ones have targeted nbind from the beginning (see [libui-node](https://github.com/parro-it/libui-node)).

nbind is already independent from Node.js, because you can set a build tool flag to target asm.js using Emscripten instead. They are extremely different platforms, and yet both work from a single codebase.

You can compare this [RisingStack NAN tutorial](https://blog.risingstack.com/writing-native-node-js-modules/) with its [nbind-based port](https://github.com/peteyy/native-addon-example/issues/1).

**Comment by jasongin** [comment]
Note `npm-pkg-top` does not do a perfect job of listing only packages with native modules. When querying with type 'binary' (the default) it actually includes any packages that have a preinstall, install, or postinstall script. (It [uses the skimdb needBuild view](https://github.com/nodejitsu/npm-pkg-top/blob/master/index.js#L20), which [filters packages on the existence of those scripts](https://github.com/npm/npm-registry-couchapp/blob/master/registry/views.js#L263).) While `node_gyp` is probably the most common reason for a package to have an install script, there are many packages that have other kinds of install scripts.

From the top 20 list above, the following 4 packages do not actually have native modules. (Technically phantomjs and electron do install native binaries, but not the kind we're looking for.)
 * phantomjs
 * phantomjs-prebuilt
 * electron-prebuilt
 * radium

If you want to make 20, the next 4 in order that do have native modules are:
 * fsevents
 * ref
 * pty.js
 * node-hid

**Comment by vkurchatkin** [comment]
`deasync` most definitely shouldn't be tested, as it uses libuv in an unsupported way

**Comment by mhdawson** [comment]
This issue is long stale, closing. Please let us know if you think that was not the right thing to do.
