### ISSUE TITLE
npm name for wrapper

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#223]
have not been able to contact the owner of node-api.  Lets brainstorm some other ideas.

**Comment by gabrielschulhof** [comment]
[node-addon-api](https://www.npmjs.com/search?q=node-addon-api&page=1&ranking=optimal)

**Comment by jasongin** [comment]
`node-addon-api` sounds good to me.

**Comment by Fishrock123** [comment]
We could just ask npm support about `node-api`. I've done this before, getting an abandoned name isn't that big of a deal.

**Comment by mhdawson** [comment]
@Fishrock123 does it take very long ?

**Comment by mhdawson** [comment]
I think at this point maybe we should just start using node-addon-api and if we can move to node-api later do that.

**Comment by jasongin** [comment]
Published at https://www.npmjs.com/package/node-addon-api
I also added [nodejs-foundation](https://www.npmjs.com/~nodejs-foundation) as a package owner.

**Comment by mhdawson** [comment]
believe we can close this.
