### ISSUE TITLE
Napi APIs should handle out of memory better

### ISSUE THREAD

**Issue by boingoing** [nodejs/abi-stable-node#224]
If a Napi API call hits an OOM, we often don't catch this condition and just return an opaque pointer wrapping `nullptr`. This is the case in `napi_create_reference`, for example, if `v8impl::Reference::New` fails with out of memory and returns `nullptr`. 

Should we instead return `napi_out_of_memory`?

**Comment by jasongin** [comment]
> Should we instead return `napi_out_of_memory`?

That would seem more correct to me.

**Comment by addaleax** [comment]
Fwiw Node’s general strategy for OOM situations is “crash”. Using `node::Malloc()` & co has the advantage of telling V8 to do a GC if a first attempt at allocating fails, but right now that’s the best we do.

So, for now you should be good reserving special OOM handling for situations that try to allocate user-specified amounts of memory, e.g. typed array creation.

**Comment by jasongin** [comment]
I don't think there is anywhere we directly allocate a user-specified amount of memory. For `Buffer` and `ArrayBuffer` creation, can we assume that an empty maybe result is due to OOM? Or does V8 throw an exception in that case? It's probably worth adding some tests around that.

(I see there's currently a bug in `napi_create_arraybuffer()`: it doesn't check whether the result of `v8::ArrayBuffer::New()` is empty.)

**Comment by jasongin** [comment]
I see pervasive use of `new` throughout node core codebase, without any checking for a null result. That makes sense because `new` should throw `std::badalloc` if allocation fails, according to the C++ standard.

**Comment by addaleax** [comment]
> For `Buffer` and `ArrayBuffer` creation, can we assume that an empty maybe result is due to OOM?

Yes, that seems like a safe assumption to me.

> Or does V8 throw an exception in that case?

> (I see there's currently a bug in `napi_create_arraybuffer()`: it doesn't check whether the result of `v8::ArrayBuffer::New()` is empty.)

There is no MaybeLocal version of `ArrayBuffer::New` yet, right now it just crashes on OOM. V8 source quote:

```c++
  // TODO(jbroman): It may be useful in the future to provide a MaybeLocal
  // version that throws an exception or otherwise does not crash.
  if (!i::JSArrayBuffer::SetupAllocatingData(obj, i_isolate, byte_length)) {
    i::FatalProcessOutOfMemory("v8::ArrayBuffer::New");
  }
```

**Comment by mhdawson** [comment]
We've not worked on this for 3 and 1/2 years and there has also not been related problems reported so we agreed to close this issue and open a new one if/when we plan to work on it. Please let us know if that was not the right thing to do.
