### ISSUE TITLE
Test for interaction between scope and exception

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#228]
Enhance `test/addons-napi` with a test where we pass such a callback from JS into the addon that, when called, will throw. In the addon we call the JS callback from between a scope open/close. The scope close must return `napi_ok`. We should induce a fatal error, like an abort otherwise.

**Comment by jasongin** [comment]
This PR includes such a test: https://github.com/nodejs/node/pull/12524

**Comment by gabrielschulhof** [comment]
@jasongin I think you got this one with that PR.
