### ISSUE TITLE
Need to address N-API versioning scheme

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#231]

**Comment by mhdawson** [comment]
Will take this on once the doc lands.

**Comment by mhdawson** [comment]
Looking at this today.  I think we have enough flexibility in how we load the N-API modules that we can introduce any module version checking later on without affecting exsting modules, if this ever needed. Hopefully not.

The only thing missing seems to be a method for an addon to be able to check the level of N-API being supported.
