### ISSUE TITLE
Can't use node::FatalError()

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#232]
... because node_internals.h is not available outside of node. So, if we want node-api to contain unaltered versions of the implementation, we must not rely on any node internals.

I guess we could simply throw a JS exception. Since `Isolate::GetCurrent()` is going away, and since we don't have an env from which to extract an isolate, is there some other way we can signal that we wish to throw an exception?

**Comment by bnoordhuis** [comment]
> I guess we could simply throw a JS exception.

FatalError() is a noreturn function.  Its n-api equivalent shouldn't throw an exception, it should exit.

**Comment by addaleax** [comment]
Just copying Node’s `FatalError`, i.e. fprintf() + fflush() + abort(), sounds good to me too.

> Since `Isolate::GetCurrent()` is going away

Just curious, is that publicly announced anywhere?

**Comment by bnoordhuis** [comment]
> Just curious, is that publicly announced anywhere?

Not really, but V8 people have repeatedly indicated over the years they want to get rid of it.

**Comment by gabrielschulhof** [comment]
@addaleax well, it's actually more than that, because in Windows it's `raise(SIGABRT)`, and not fprintf() but `WriteConsoleW()`, etc. So, there's quite a bit of code in `node.cc` dealing with this.

**Comment by gabrielschulhof** [comment]
@bnoordhuis we were originally debating whether we should consider the absence of an `env` a fatal error or not. There was a good argument for "not" in that this is just a module, so perhaps the whole app shouldn't be shot down because of a buggy module. The reason we went with the "aye" in the end was that it's very much a corner case anyway.

**Comment by gabrielschulhof** [comment]
But without an `env`, and hence without an isolate, we can't even throw an exception.

**Comment by gabrielschulhof** [comment]
We can wrap the call to `node::FatalError()` in `#if defined(NODE_WANT_INTERNALS) && NODE_WANT_INTERNALS` to avoid failure to compile outside of node, but we should really have something in the `#else` case.

**Comment by jasongin** [comment]
I'm still not convinced we need `FatalError()` functionality. The one place where it is used now could return a `napi_status` error instead.

**Comment by jasongin** [comment]
Related: https://github.com/nodejs/node-api/pull/25

**Comment by jasongin** [comment]
We might want to actually expose `node::FatalError()` (or similar) as a `napi_fatal_error()` API. See https://github.com/nodejs/node-api/pull/32#discussion_r114903602 for a scenario where it is needed.

**Comment by mhdawson** [comment]
https://github.com/nodejs/node/issues/13927

**Comment by digitalinfinity** [comment]
Addressed by https://github.com/nodejs/node/pull/13971
