### ISSUE TITLE
Cache commonly-used JSRT property keys (JsPropertyIdRefs)

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#234]
From https://github.com/nodejs/abi-stable-node/pull/233#discussion_r112586511

Consider caching commonly-used property keys, instead of allocating them whenever they are used.

 - In `napi_define_class()`: `"prototype"`, `"constructor"`
 - In `napi_define_properties()`: `"get"`, `"set"`, `"value"`, `"configurable"`, `"enumerable"`, `"writable"`
 - In `napi_get_array_length()`: `"length"`

**Comment by mhdawson** [comment]
Closing since Chakra is no longer active. Please let us know if you think that was not the right thing to do.
