### ISSUE TITLE
Symbol.hasInstance support in JSRT

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#236]
After [updating the Node-ChakraCore JSRT implementation](https://github.com/nodejs/abi-stable-node/pull/233), `addons_napi/test_instanceof` fails because `Symbol.hasInstance` is not handled by either `JsInstanceOf()` or the JSRT `napi_instanceof()` implementation.

**Comment by mhdawson** [comment]
Closing since Chakra is no longer active, please let us know if you think that was not the right thing to do.
