### ISSUE TITLE
More (unnecessary?) NAPI_PREAMBLE() calls

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#238]
We have
- [x] `napi_is_array` (`val->IsArray()`)
- [x] `napi_is_buffer` (`node::Buffer::HasInstance()`)
- [x] `napi_is_arraybuffer` (`val->IsArrayBuffer()`)
- [x] `napi_is_typedarray` (`val->IsTypedArray()`)

that have `NAPI_PREAMBLE()`, whereas
- [ ] `napi_is_error` (`val->IsNativeError()`)

does not have it.

I don't believe the ones above that have `NAPI_PREAMBLE()` need it, for the same reason that `napi_typeof()` doesn't need it. What do @nodejs/addon-api think?

**Comment by mhdawson** [comment]
If you have checked and don't believe we need them there, I'm happy to have them be removed.

**Comment by gabrielschulhof** [comment]
The only thing I'm not sure about is whether the engine would ever throw an exception in response to `IsArrayBuffer()`, or `IsArray()` or functions of this nature. I think I'll remove the `NAPI_PREAMBLE()`s, because it doesn't make sense to me that it should ever throw an exception in such cases.

**Comment by jasongin** [comment]
+1

The four listed above seem the most obvious, though we may also consider several other APIs that don't have any possibility of invoking JavaScript code. Does V8 ever throw exceptions when not invoking JS code? I assume not.

**Comment by gabrielschulhof** [comment]
OK, so while we're on the topic, what about these:
- `napi_get_value_string_latin1`
- `napi_get_value_string_utf8`
- `napi_get_value_string_utf16`
- `napi_get_value_external`
- `napi_get_buffer_info`
- `napi_get_arraybuffer_info`
- `napi_get_typedarray_info`
We should test how these functions behave if we pass in the wrong type, or, better yet `CHECK_TO_<type>` at the top.

**Comment by jasongin** [comment]
> better yet CHECK_TO_<type> at the top

Generally we have avoided automatic type coercions, because they can have a significant perf cost. (I think there may even be a few places currently doing type coercions that shouldn't.) If the wrong type is passed into an API, it should just return an appropriate error code.

**Comment by jasongin** [comment]
And yes, I agree with adding all those getters to the list.

**Comment by gabrielschulhof** [comment]
They all have checks, so that's good.

**Comment by gabrielschulhof** [comment]
Yeah, sorry, I meant type checks, not coercions.
