### ISSUE TITLE
Porting nbind to use NAPI

### ISSUE THREAD

**Issue by jjrv** [nodejs/abi-stable-node#24]
I'd be interested in porting [nbind](https://github.com/charto/nbind#readme) to use NAPI. Basically it's a replacement for, among others, NAN (Node.js parts of nbind are built on top of it). The idea is that you write ordinary C++ classes and functions using standard library types, and finally do:

```C++
#include "nbind/nbind.h"

NBIND_CLASS(YourClassName) {
  method(yourMethod);
  // etc.
}
```

You don't need to list the method argument or return types, they're all autodetected using template magic and type conversion code is generated by the C++ compiler as needed. It uses NAN when targeting Node.js addons, but the exact same C++ code can also be compiled using Emscripten to target asm.js and run it inside browsers.

You can have any number of `NBIND_CLASS` blocks in any source files and it Just Works™ with the API accessible from JavaScript.

If ported to NAPI, again only the code inside nbind would need to change, while any addons using it will remain unchanged. Currently the only public NPM package that I know is using it, is `libui-node` which provides cross-platform native UI widgets.

However, if nbind supported NAPI, it would be way less work to write future native addons targeting NAPI (through nbind) than using any other previously existing API.

**Comment by jjrv** [comment]
After considering this further, here's the main value proposition:

If you have a set of functions and C++ classes with methods, you declare them like in the code block above, and compile in one of two possible modes:

A: Code is generated to export the API to Node.js using NAPI, much like nbind can already do for NAN.

B: Code is compiled to a library with an entry point callable using C calling convention. It reports back unmangled names, pointers and argument types of the C++ functions, which are then bound by nbind's JavaScript library using Fast-FFI. Some type conversion will be necessary to autogenerate, for example to pass a JavaScript `Array` to a C++ function expecting `std::vector<std::string>`.

Problem: Can Fast-FFI call a function given its address, or does it want to look up the symbol? In the latter case we'd need to know the *mangled* name which I can't think of how to get portably. However, doing platform-specific implementations for Linux, OS X and Windows is likely still possible.

**Comment by mhdawson** [comment]
I'm thinking it would make sense for you to give the team working on NAPI an quick overview/explanation of nbind so we can ramp up more quickly.  It is possible for you to attend our meeting on Dec 9th at 2 EST ?

Its good to heard that you are going to exercise NAPI and we look forward to your experience in using it.

**Comment by jjrv** [comment]
@mhdawson yes, I'll attend the meeting.

**Comment by sampsongao** [comment]
@jjrv  Have you get the invite to the meeting?

**Comment by jjrv** [comment]
@sampsongao I took the liberty to enroll myself through the weekly standup hangout link in the readme, a few days ago. The Google Plus event page is showing me in the list of participants, and I'm able to join through the "hangouts" link on that page. When testing, currently it of course says I'm the only one present. I guess that means the invitation works.

I've prepared a [presentation](https://gist.github.com/jjrv/9bd53ccdec07b9b2f4a18198865a9253) of about 5 minutes. Hopefully there will be time to include that, and screen sharing will work.

**Comment by ofrobots** [comment]
I would like to join the meeting too. How do I join?

**Comment by jjrv** [comment]
@ofrobots https://plus.google.com/u/0/events/c0eevtrlajniu7h8cjrdk0f56c8?authkey=COH04YCalJS8Ug

**Comment by ofrobots** [comment]
I need permissions to be able to access it.

**Comment by sampsongao** [comment]
@ofrobots Can you send me your email address for hangout so that I can invite you? Not sure if your email in your github profile is the one with google account.

**Comment by ofrobots** [comment]
@sampsongao my github profile email address is correct. ofrobots at google.com

**Comment by mhdawson** [comment]
Unfortunately looks like this stalled out. Closing, please let us know if you think that is not the right thing to do.
