### ISSUE TITLE
Validate ported modules and the demo

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#240]

**Comment by jasongin** [comment]
I updated leveldown to work with the latest N-API:

https://github.com/jasongin/leveldown/tree/napi/

https://github.com/jasongin/leveldown/commit/12320e85e165a9eb9e7c87dade8dd7e40e454f27

**Comment by sampsongao** [comment]
Updated nanomsg to latest N-API
https://github.com/sampsongao/node-nanomsg/tree/napi-port-3.2.4

**Comment by gabrielschulhof** [comment]
iotivity-node also [works](https://travis-ci.org/gabrielschulhof/iotivity-node/builds/232766786) with the latest N-API, although I'm copying the implementation verbatim out of Node.js, rather than depending on the node-addon-api package.

**Comment by jasongin** [comment]
> I'm copying the implementation verbatim out of Node.js, rather than depending on the node-addon-api package

Why? Is it just because the `node-addon-api` package is a little out of date? I do need to publish an update to the NPM package soon.

**Comment by gabrielschulhof** [comment]
Last time I tried I couldn't get it to work. I can give it another shot. I also forgot to mention that iotivity-node also [works](https://ci.appveyor.com/project/gabrielschulhof/iotivity-node-roxkw/build/1.0.457) on Windows with Node 6 and 7.

**Comment by jasongin** [comment]
If you have issues using that package, we should fix them. :) I remember you had some problems a while ago, but I thought we addressed them.

**Comment by sampsongao** [comment]
I have just updated the addon examples.
https://github.com/nodejs/abi-stable-node-addon-examples/commit/2f8495dd287c3e04bf92b971c0ebe918b8ea9311

**Comment by jasongin** [comment]
I updated the canvas port: https://github.com/jasongin/node-canvas/commit/d5b95768f3d2c11f0eaa791d9a1c8b07f3e89fcc

**Comment by jasongin** [comment]
I updated node-sass: https://github.com/boingoing/node-sass/commit/71132a2049a113f6eadb8ab304534e44c0df17f3

For this package, I temporarily changed the `npm test` script to only run the tests in `test/api.js`, since those are the tests that have good coverage of N-API. The tests in `test/cli.js` have problems because they spawn other node processes, so the `--napi-modules` requirement gets in the way. I started trying to workaround that, but it wasn't easy.

**Comment by mhdawson** [comment]
With current master you can use 
```bash
export NODE_OPTIONS=--napi-modules
```
 so you should not need to modify the tests and it should still test with N-API for child processes.

**Comment by jasongin** [comment]
Setting `NODE_OPTIONS=--napi-modules` mostly works, with two caveats:

1. If that option is set during the install/build, the N-API warning causes the `"<!(node -p \"require('node-addon-api').gyp\")"` to fail.
2. The N-API warning breaks several node-sass CLI test cases that are expecting specific stderr output.

Also, some of the `node-sass` CLI tests seem to have other problems on Windows. That's probably why [it's marked as "flaky" for Windows in CTGM](https://github.com/nodejs/citgm/blob/master/lib/lookup.json#L345).

So for those reasons, I think it will be easier to run only the `node-sass` API tests for N-API validation.

**Comment by jasongin** [comment]
I'm working on [a fork of CITGM](https://github.com/jasongin/citgm/tree/napi) that will run [tests on the N-API ported modules](https://github.com/jasongin/citgm/blob/napi/lib/lookup.json). It's not quite ready yet. I'm working through some issues with nanomsg, and I need to verify it works on all platforms and all targeted node versions (4.x, 6.x, 8.x, Node-ChakraCore).

**Comment by digitalinfinity** [comment]
cc @MylesBorins just as a heads up, in case he has thoughts 😄

**Comment by mhdawson** [comment]
@jasongin that sounds good, I know that @sampsongao was working on a build job to test nanomsg, but the longer term goal was to get it using CITGM.  Maybe you can touch base with him to co-ordinate.
