### ISSUE TITLE
Title inconsistent with actual function signature in the doc

### ISSUE THREAD

**Issue by legenddcr** [nodejs/abi-stable-node#243]
Two URL:
- https://github.com/nodejs/abi-stable-node/search?utf8=%E2%9C%93&q=napi_get_value_string_utf16_length&type=
- https://nodejs.org/api/n-api.html#n_api_napi_get_value_string_utf16_length

"napi_get_value_string_utf16_length" in title should be "napi_get_value_string_utf16".

**Comment by mhdawson** [comment]
Thanks will fix that up
