### ISSUE TITLE
Generate list of next APIs to implement

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#244]
Put together list to surface the "next" on the todo list.
Invite people to help out.

**Comment by jasongin** [comment]
Some candidates:
 - Promises https://github.com/nodejs/abi-stable-node/issues/242
 - Fatal error https://github.com/nodejs/abi-stable-node/issues/232 (also https://github.com/nodejs/node-addon-api/issues/48)
 - Deleting properties https://github.com/nodejs/abi-stable-node/issues/94
 - Eval https://github.com/nodejs/abi-stable-node/issues/51
 - Own properties https://github.com/nodejs/abi-stable-node/issues/67
 - DataView https://github.com/nodejs/abi-stable-node/issues/202
 - Error code https://github.com/nodejs/abi-stable-node/issues/241
 - AdjustExternalMemory https://github.com/nodejs/abi-stable-node/issues/52

**Comment by jasongin** [comment]
For async hooks, we might need new APIs, or maybe just updates to existing implementation. See discussion at https://github.com/nodejs/node/issues/13254

**Comment by klaus82** [comment]
I think Promises is the best issue to work on.

**Comment by mhdawson** [comment]
Create this list of issues:

* https://github.com/nodejs/node/issues/13924 (Deleting properties)
* https://github.com/nodejs/node/issues/13925 (Own properties)
* https://github.com/nodejs/node/issues/13926 (Data View)
* https://github.com/nodejs/node/issues/13927 (Fata Error)
* https://github.com/nodejs/node/issues/13928 (AdjustExternalMemory)
* https://github.com/nodejs/node/issues/13933 (error codes)

There is already an issue for promises:

https://github.com/nodejs/node/pull/13717

**Comment by mhdawson** [comment]
We have enough progress on this, going to add going forward based on need.
