### ISSUE TITLE
Reach out to top 30 modules owners

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#245]
| Module  | owner    |
|---------- |----------|
| serialport | Michael |
| bycrypt | Arunesh |
| hiredis | Arunesh |
| websocket | Sampson |
| fibers | Hitesh |
| nodegit | Hitesh |

**Comment by aruneshchandra** [comment]
Here's the list 
https://github.com/nodejs/abi-stable-node/blob/doc/data/TopNativeImports.csv

**Comment by jasongin** [comment]
This list will be easier to use:
https://github.com/nodejs/abi-stable-node/blob/doc/data/TopPackagesWithNativeModules.csv

**Comment by mhdawson** [comment]
Issue for node-serialport - https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/1186

**Comment by digitalinfinity** [comment]
Issue for nodegit - https://github.com/nodegit/nodegit/issues/1298

**Comment by aruneshchandra** [comment]
Issue for hiredis - https://github.com/redis/hiredis-node/issues/134

**Comment by aruneshchandra** [comment]
Issue for bcrypt - https://github.com/kelektiv/node.bcrypt.js/issues/513

**Comment by sampsongao** [comment]
Issue for node-sqlite3 - https://github.com/mapbox/node-sqlite3/issues/830

**Comment by sampsongao** [comment]
Issue for websocket - https://github.com/theturtle32/WebSocket-Node/issues/284

**Comment by mhdawson** [comment]
Talked to Francis today about Node Serial port.  He is happy to have a branch in the repo and help maintain once there is a port.

He sees definite benefits in that today he needs to support downloading because there has to be a different binary for every version of Node.js and the sum of those are too big to bundle into an npm.  With a single binary bundling would be possible.

The plan is for me to take a first cut at porting, he's available to support us by answering questions etc.  Once we have an initial cut we'll get back together to get it into a branch in the repo and figure out the plan going forward.

**Comment by andreek** [comment]
Hello,

I started to investigate porting theturtle32/WebSocket-Node#284 to N-API. After some research I found out the original code for the native modules were extracted of [ws](https://www.npmjs.com/ws). Today this code is in the packages [bufferutil](https://www.npmjs.com/bufferutil) and [utf-8-validate](https://www.npmjs.com/utf-8-validate) as opt-in dependencies for [ws](https://www.npmjs.com/ws). I ported both packages to N-API: [andreek/bufferutil](https://github.com/andreek/bufferutil) / [andreek/utf-8-validate](https://github.com/andreek/utf-8-validate).

My recommendation regarding to theturtle32/WebSocket-Node#284 is to use  [bufferutil](https://www.npmjs.com/bufferutil) / [utf-8-validate](https://www.npmjs.com/utf-8-validate). 

I could use some help reaching the maintainers of [websocket/bufferutil](https://github.com/websockets/bufferutil) / [websocket/utf-8-validate](https://github.com/websockets/utf-8-validate) (33/34 on list) talking them into having a N-API branch. But I don't know if there is any strategy. I was thinking about just creating PRs and asking for creating a separate branch to maintain.

I hope its the right place to give feedback and ask for some help.

**Comment by mhdawson** [comment]
@andreek thanks for your work.  What we have done in the past is created a PR explaining the context of why they want to move to N-API, the branch were the port has been done. Our guidance on how to have an N-API for now is in https://nodejs.org/en/docs/guides/publishing-napi-modules/

Would like like to come to our next N-API interlock (Thursdays at 1:30 EST) so we can discuss how to help reaching the maintainers and maybe you can give us an overview of your thoughts on the API having done the port ?

**Comment by andreek** [comment]
@mhdawson yeah, I would like to. The hangout link in the readme is still used?

**Comment by mhdawson** [comment]
@andreek yes the same link as in the readme.  It is also in the foundation calendar entry.

**Comment by andreek** [comment]
websockets/bufferutil#81 / websockets/utf-8-validate#54 merged into n-api branch. For theturtle32/WebSocket-Node#284 PR theturtle32/WebSocket-Node#302 is open to depend on n-api modules.

**Comment by Globik** [comment]
Also libqrencode partialy translated to the n-api approach.
https://github.com/Globik/qrencode_mini

**Comment by NickNaso** [comment]
Hi everyone, I just ended the porting of **hiredis** and I provided to update the issue on the repo if **hiredis** https://github.com/redis/hiredis-node/issues/134#issuecomment-378781006

**Comment by mhdawson** [comment]
I think we are past this effort and we should open a new issue if we decided to do more outreach to larger modules.
