### ISSUE TITLE
Reach out to owners of ported modules

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#246]
Reach out to the owners of the modules we ported and see if they will accept the ports into their repos and help maintain.

| module    | owners                        |
| -----------|-------------------------|
| leveldown | boingoing / jasongin |
| nanomsg | sampsongao |
| canvas | jasongin |
| node-sass | boingoing / jasongin |
| node-sqlite3 | sampsongao / mhdawson |

**Comment by mhdawson** [comment]
leveldown |boingoing / jasongin
nanomsg	| sampsongao
canvas | jasongin
node-sass | boingoing / jasongin
node-sqlite3 | sampsongao / mhdawson

**Comment by nschonni** [comment]
node-sass tracking issue https://github.com/sass/node-sass/issues/1988

**Comment by jasongin** [comment]
`node-canvas` tracking issue: https://github.com/Automattic/node-canvas/issues/923

**Comment by sampsongao** [comment]
node-nanomsg tracking issue: https://github.com/nickdesaulniers/node-nanomsg/issues/177

**Comment by digitalinfinity** [comment]
Filed an issue for node-zopfli here: https://github.com/pierreinglebert/node-zopfli/issues/92

**Comment by NickNaso** [comment]
Issue for **microtime** here: [https://github.com/wadey/node-microtime/issues/56](https://github.com/wadey/node-microtime/issues/56)

**Comment by NickNaso** [comment]
Issue for **farmhash** here: [https://github.com/lovell/farmhash/issues/19](https://github.com/lovell/farmhash/issues/19)

**Comment by NickNaso** [comment]
Issue for **ghostscript4js** here: [https://github.com/NickNaso/ghostscript4js/issues/29](https://github.com/NickNaso/ghostscript4js/issues/29)

**Comment by NickNaso** [comment]
Issue for **magick-cli** here: [https://github.com/NickNaso/magick-cli/issues/11](https://github.com/NickNaso/magick-cli/issues/11)

**Comment by NickNaso** [comment]
Issue for **64** here: [https://github.com/lovell/64/issues/4](https://github.com/lovell/64/issues/4)

**Comment by NickNaso** [comment]
Issue for **highwayhash** here: [https://github.com/lovell/highwayhash/issues/6](https://github.com/lovell/highwayhash/issues/6)

**Comment by NickNaso** [comment]
Issue for **sse4_crc32** here:  [https://github.com/anandsuresh/sse4_crc32/issues/69](https://github.com/anandsuresh/sse4_crc32/issues/69)

**Comment by mhdawson** [comment]
I think we've closed on what we were going to do on this one. Closing, please let us know if you think that was not the right thing to do.
