### ISSUE TITLE
Document electron issues with different v8 versions.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#247]
Talk James/Myles to see what information we have on the problem and if N-API helps.

**Comment by mhdawson** [comment]
Send email to James/Myles as first point of contact.

**Comment by MylesBorins** [comment]
which email? I didn't see it

**Comment by mhdawson** [comment]
Will refind/re-send

**Comment by mhdawson** [comment]
Myles got me invited to the electron slack channel.  I've started to engage there.  My initial intro:

```
I'm from the Node.js community working on N-API which is a new API for writing native addons that
should be ABI stable.  It was mentioned that there were some cases that electron had issues
supporting/using Node.js that it might help with.  I wanted to find those who might have been in those
discussions to understand the problem so that I can see if N-API helps or not.
```

**Comment by mhdawson** [comment]
This is the summary from my conversation last night with

Jacob Groundwater
Kevin Sawicki
Zeke

The problems they have are not necessarily related to the API for native modules but N-API will help to simplify some of their use cases.

1) Since  electron does not necessarily have a version of v8 with a matching level to that in a Node.js release, modules used with electron, native modules have to be compiled for each electron version.  This is particularly cumbersome for modules that use pre-gyp as they need to provide binaries for each node release **and** each electron release.  If modules only depended on N-API, it would be easier as one binary should run for any level of Node or electron.

2) When compiling for electron, a different set of headers are needed than when compiling with electron (as the v8 level may be different).  npm is not set up to handle this easily so this requires additional options to specify a different download URL and leads to additional difficulties when compiling.  The result is that modules need to include an npm rc file to make sure the right thing happens for electron.  If modules only depended on N-API then then only the N-API includes would be required so it might help here as well.  

3) Modules that use node pre-gyp sometimes have issues on windows finding symbols even when compiled against the right headers.  

4) Sometimes there are conflicts between development dependencies and deployment dependencies.  The modules used with Node.js for development (ex Gulp)  may have common sub-modules with those shipped with the electron application.  The problem is that the sub-module needs to be compiled with different headers for Node.js and electron (due to different v8) levels so you can get into a back and forth where you do a development step and the module gets compiled with Node.js but then the binary won't run with the electron app and vice versa.  Got worse with the flattening of modules.  They have worked around it by configuring so there is a different tree for dev and deployment.

Outside the issues we discussed we also talked about:

1) Electron uses ~20 modules of their own, primarily to support the atom editor.  These are task oriented and **not** "chatty".  They currently use NaN and use the Async helper APIs.

2) What levels of V8 with N-API support from the Node.js team -> Only those in released version of Node.js.  They try to hit every chrome release so there may be some gaps.

3) They will be starting the move to use Node 8.x in the next couple of weeks. As part of the Kevin will port one of the modules to use N-API and give us feedback, report issues etc.


Actions from the discussion:

1) Mentioned we already had an issue open to understand the pre-gyp interaction with N-API.  Its relevant for electron usage as well so we should move it forward.

2) Kevin will port initial electron module, he will open issues on abi-stable-node repo if necessary and we'll loop back in 3-4 weeks to sync on how things are going.

If we have more questions we should reach out to Jacob and Kevin.  Once thing that comes to mind now is that we should get the list of key native modules used with electron.  It may be interesting to approach them as early N-API adopters.
