### ISSUE TITLE
Create template for reaching out to module owners.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#248]

**Comment by mhdawson** [comment]
When do you think you'll have the first cut for discussion ?

**Comment by aruneshchandra** [comment]
Just sent it over via email

**Comment by mhdawson** [comment]
Agreed template:

The recently announced Node 8 has a new experimental feature called [N-API]( https://nodejs.org/dist/latest-v8.x/docs/api/n-api.html) which is aimed at reducing maintenance cost for node native addons. Checkout this [blog]( https://medium.com/@nodejs/n-api-next-generation-node-js-apis-for-native-modules-169af5235b06) for more details on its benefits. 

Module X(fill in for specific module) is one of the top 30 native modules by dependency count, and in order to help the Node.js community make the important transition to N-API, we are hoping you will be able to work with us in order to port X to support N-API.  Your support and feedback is important in making this effort a success.
 
I am part of the  N-API working group and and would like to talk to you about how you can can get started with N-API and what help we might be able to provide.  I'm available to talk on the phone individually if you'd like.  Alternatively, if you prefer, feel free to jump in our [WG meeting](https://plus.google.com/u/0/events/c0eevtrlajniu7h8cjrdk0f56c8?authkey=COH04YCalJS8Ug)which happens every Thursday at *1.30 Eastern / 10.30 Pacific US time*, to discuss any issues. 
 
Here’s a video of N-API in action 
https://www.youtube.com/watch?v=nmXhJ88nZsk
