### ISSUE TITLE
napi_is_exception_pending could just use a return status

### ISSUE THREAD

**Issue by RReverser** [nodejs/abi-stable-node#250]
It looks like this API could be simplified and, instead of requiring a separate output pointer for boolean, just return either `napi_ok` or `napi_pending_exception` which already clearly communicate current state.

**Comment by jasongin** [comment]
Yes, it could work that way. But I think that would be inconsistent with all the other `napi_is_` APIs that have a boolean out parameter. And it would be mis-using the intent of `napi_ok`, which is just supposed to indicate that the _called_ API (not any previous call) executed successfully.

**Comment by RReverser** [comment]
Yeah but this API doesn't execute any real code to potentially fail. And `napi_pending_exception` in return status already indicates that any pending exception exists, not necessarily created by didn't method, so seems consistent to use that way.

As for the prefix - true, but could as well be renamed or something...

**Comment by mhdawson** [comment]
We did choose to make all of the APIs consistent in how they return the result and status.  I think we'd need a compelling reason to make an exception.

**Comment by RReverser** [comment]
@mhdawson There is already precedent for reasonable exceptions such as `napi_throw_*` which return `napi_ok` and not `napi_pending_exception` after they throw an error (unlike every other method that calls out to JavaScript).

This function has another reason - duplication of same information - but seems valid too. Or is it currently designed to return `napi_ok` and not `napi_pending_exception` when pending exception exists?

**Comment by mhdawson** [comment]
It is currently designed to return napi_ok regardless of whether an exception is pending or not, provided it could make the determination.

The pattern is that napi_status tells us if the function succeeded in what you were requesting or not. 
Code should be checking napi_status and can assume the request was successful if the returned status is napi_ok.  If not, it needs to take appropriate action, often bailing out of the native in an error path.  The consistency across all functions allows consistent check after all calls.  As an example, it allows us to use the NAPI_CALL macro in our tests to call all napi functions.  NAPI_CALL checks the result and throws an exception if the result is not napi_ok.

In this particular case I think we need the out parameter as a successful call (which should return napi_ok) needs to return different information depending on whether an exception was pending or not.  On the other hand napi_throw_* does not need to return any info other than confirmation that what you requested could be completed.

**Comment by RReverser** [comment]
@mhdawson Ok, makes more sense now, thanks. Still having some questions around using this "pending exception" status, but they're unrelated to this suggestion and guess I'll save them for the weekly meeting.

**Comment by mhdawson** [comment]
Good to hear.  Looking forward to talking to you in the meeting this week.
