### ISSUE TITLE
Specify when input pointers can be NULL

### ISSUE THREAD

**Issue by RReverser** [nodejs/abi-stable-node#252]
For example, apparently (according to examples) it’s ok to pass `NULL` as `thisArg` and `data` to `napi_get_cb_info` if you don’t want to retrieve it, but this is not mentioned in the docs.

Some other places like napi_wrap mention “optional” explicitly for out params, might be a good idea to go through other functions too and explicitly specify when pointer is "optional" or when it must be non-NULL.

**Comment by RReverser** [comment]
@sampsongao Are you still planning to do this?

**Comment by sampsongao** [comment]
I am busy with my assignment for school now. I will continue on this maybe next week or so.

**Comment by mhdawson** [comment]
Submitted - https://github.com/nodejs/node/pull/40821 for reported instance.  
Leaving open as we should look for other cases where we can add the optional info.

**Comment by mhdawson** [comment]
Submitted https://github.com/nodejs/node/pull/41021 to close out the remaining places that needed an update.
