### ISSUE TITLE
Add optional length to functions accepting const char *

### ISSUE THREAD

**Issue by RReverser** [nodejs/abi-stable-node#254]
As discussed in the last meeting, zero-terminated `const char*`, while popular in C land, might be problematic for consumers in other languages having different string representation (for example, Rust with non-zero-terminated string slices represented as `data` + `length`).

Some N-API functions already accept optional `length` that, when set to `-1`, would mean a length calculated from zero-terminated string and explicit byte length otherwise.

It's worth to go through a list of functions that accept `const char*` and add `length` parameter where it's missing, especially for functions that don't provide variants with `napi_value` as a string, namely:

 - `napi_create_function`
 - `napi_define_class`
 - `napi_module_register` -> `napi_module` struct

**Comment by digitalinfinity** [comment]
Thanks @RReverser - moved discussion to https://github.com/nodejs/node/issues/15108 since this is a nice to have and we'll get more help and visibility on the main repo. Closing this one
