### ISSUE TITLE
N-API Question: convert a C native array to a JavaScript array

### ISSUE THREAD

**Issue by magiclen** [nodejs/abi-stable-node#258]
Currently, N-API can create a number (`napi_create_number`) and a string(`napi_create_string_utf16`, `napi_create_string_utf8`).

If I want to create a JS array whose elements are all numbers or strings, is there any api to do that? Or I need to create an JS array by `napi_create_array`, and then, use `napi_create_number`, `napi_create_string_utf16`, `napi_create_string_utf8` and `napi_set_element` to convert data to JS values and set them in a loop.

The conversion takes a lot of time. I want to learn how to speed up these steps. Thanks.

**Comment by gabrielschulhof** [comment]
You can use an array buffer and a typed array (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) and back it with your C array - at least for numbers. I think for strings you need to do the loop.

https://nodejs.org/api/n-api.html#n_api_napi_create_arraybuffer
https://nodejs.org/api/n-api.html#n_api_napi_create_typedarray

**Comment by magiclen** [comment]
Thanks, it's very useful!
