### ISSUE TITLE
Will napi_set_function_name work with spidermonkey

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#26]
* **Version**: ALL
* **Platform**: ALL 
* **Subsystem**: API

Comment from Ben in https://github.com/nodejs/node-eps/pull/20#issuecomment-264451567, we'll need to see if:
```
NODE_EXTERN void napi_set_function_name(napi_env e, napi_value func,
+                                        napi_propertyname napi_value);
```
will work with other engines like spidermonkey were the name it declared up front.

**Comment by aruneshchandra** [comment]
@mykmelez do you have any idea about this ?

**Comment by jasongin** [comment]
ChakraCore also can only set the name when the function is created. For issue https://github.com/nodejs/abi-stable-node/issues/78 we decided to remove `napi_set_function_name` and add an optional name parameter to `napi_create_function` instead.
