### ISSUE TITLE
Define 2nd list of next api to ask for help on.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#262]

**Comment by jasongin** [comment]
Some candidates:
 - [Add optional length to functions accepting const char *](https://github.com/nodejs/abi-stable-node/issues/254)
 - [new target for constructors](https://github.com/nodejs/abi-stable-node/issues/200)
 - [named exports for ES6 modules](https://github.com/nodejs/abi-stable-node/issues/256) - this one probably requires some design discussion first

**Comment by gabrielschulhof** [comment]
For convenience: `napi_is_date()` - on V8 it would be `->IsDate()`, and on ChakraCore it would be `napi_instanceof()` after retrieving the "Date" property of the global object to obtain the constructor.

**Comment by digitalinfinity** [comment]
We're going to implement APIs on an as-needed basis, informed by the migration effort
