### ISSUE TITLE
Storing custom module data per-env

### ISSUE THREAD

**Issue by RReverser** [nodejs/abi-stable-node#265]
Current `napi_env` documentation says:

> `napi_env` is used to represent a context that the underlying N-API implementation can use to persist VM-specific state.

But is there a way to store custom values associated with that environment from the module itself?

In particular, this can be useful for creating permanent constants (e.g. strings) using `napi_ref` and then returning them from module callbacks instead of converting same constants over and over from native side to JS on each invocation (what even string shorthands such as `napi_set_named_property` seem to be currently doing).

**Comment by addaleax** [comment]
Fwiw, the upside of the “Node doesn’t really know how to unload native modules/load them twice/etc.” problem is that right now, just using static data works pretty well for this…

**Comment by RReverser** [comment]
Actually, nevermind, it looks like this should be achievable through `void *data` associated with exposed functions. I guess I can just put a bunch of `napi_value` there as part of module's initialization...

**Comment by RReverser** [comment]
@addaleax Yeah but it's scary to use with potential multithreading or `vm` module reusing same shared library but with different `napi_env`.

**Comment by RReverser** [comment]
As a side point: it's still worrying to me that `napi_set_named_property` seem to implicitly create new `napi_value` every time for the given string, and this is not mentioned anywhere, so using it in a loop can easily exhaust tons of memory... or is there some optimization (string interning) that is common for all VMs that it implicitly relies on?

**Comment by addaleax** [comment]
@RReverser It’s creating internalized strings, i.e. identical strings will occupy the same memory and the garbage collector expects them to be long-lasting objects.

If you’re worried about the extra handles that are being created, I guess we could make that a bit less bad by using `HandleScope`s (but then again, the created objects will occupy memory *anyway*, and each one more than a single handle, so I don’t think that’s as bad as it sounds)?

**Comment by RReverser** [comment]
~~@addaleax Oh, that sounds reassuring, thanks (I wonder if it's guaranteed to be true for every engine implementing N-API). On the other hand, IIUC, this means that a dynamically allocated string must not be used with these APIs, as its pointer can contain a different sequence of bytes over time - should this be explicitly documented?~~ Nevermind, I thought it's just using a pointer for detecting whether string should be copied over again.

**Comment by addaleax** [comment]
> I wonder if it's guaranteed to be true for every engine implementing N-API

@RReverser I only know that the V8 version. The JSRT version uses `JsCreatePropertyId`, which *sounds* good. ;)

> On the other hand, this means that a dynamically allocated string must not be used with these APIs, as its pointer can contain a different sequence of bytes over time - should this be explicitly documented?

V8 still creates a copy, but a single copy, not multiple ones, so that should be okay. :)
