### ISSUE TITLE
Performance Comparison between NAPI and node-addon-api

### ISSUE THREAD

**Issue by sampsongao** [nodejs/abi-stable-node#268]
Just for a data point, I take a simple measurement of performance on NAPI and node-addon-api with nanomsg perf test. The result are similar.

napi

Items | 1 | 2 | 3 | 4 | 5 | Average
------|---|---|---|---|---|--------
average latency [us] | 117.087 | 117.364 | 116.603 | 116.891| 117.058| 117.006
throughput [msg/s] | 1591 | 1511 | 1576 | 1537 | 1562 | 1555.4
throughput [Mb/s] | 0.013 | 0.012 | 0.013 | 0.012 | 0.012 | 0.0124 

node-addon-api

Items | 1 | 2 | 3 | 4 | 5 | Average
------|---|---|---|---|---|--------
average latency [us] | 118.496 | 113.657 | 113.998| 116.369| 113.887| 115.2814
throughput [msg/s] | 1547 | 1510 | 1550 | 1531 | 1557 | 1539
throughput [Mb/s] | 0.012 | 0.012 | 0.012 | 0.012 | 0.012 | 0.012

**Comment by jasongin** [comment]
This is what I expected, but it is great to have data proving it. Thanks!
