### ISSUE TITLE
List of potential N-API breaking changes

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#271]
After N-API exits experimental status, we can no longer make breaking changes. So we should track any issues that might force breaking changes, to ensure they are resolved before then. Here are the ones that I am aware of:

 - ~~Change `napi_add_register_func` callback for better ES6 module compatibility https://github.com/nodejs/abi-stable-node/issues/256 (Taylor)~~
 - ~~Replace `napi_create_number()` with APIs that take more specific types (for perf) https://github.com/nodejs/node/pull/14573~~
 - ~~Replace `napi_is_construct_call()` with API that gets the new-target for constructors https://github.com/nodejs/abi-stable-node/issues/200~~
 - ~~Add async hooks context parameter to `napi_make_callback()` https://github.com/nodejs/node/issues/13254 (Jason)~~
 - Add optional length to functions accepting const char* https://github.com/nodejs/node/issues/15108
(We still haven't decided whether we will do anything for this.)

**Comment by jasongin** [comment]
The changes for async hooks are in 2 PRs: https://github.com/nodejs/node/pull/14697, https://github.com/nodejs/node/pull/15189

**Comment by mhdawson** [comment]
Now just waiting on https://github.com/nodejs/node/issues/15108
@sampsongao will add the tests tonight and hopefully we can land Friday Sep 15

**Comment by mhdawson** [comment]
We've done what we were going to do on this front, closing.
