### ISSUE TITLE
napi_get_last_error_info second parameter should not be const

### ISSUE THREAD

**Issue by nonninz** [nodejs/abi-stable-node#272]
Hello,
while trying to debug an unrelated error I found what I think is a conceptual error in the function `napi_get_last_error_info`, or maybe I just don't understand it.

From the documentation:
```c
NAPI_EXTERN napi_status
napi_get_last_error_info(napi_env env,
                         const napi_extended_error_info** result);
```

Why is the second parameter a `const`? If it's an **out** parameter it shouldn't be const, because the value it points to will be changed.

Example of usage (as I understood):

```c
napi_extended_error_info *info;
napi_status info_status = napi_get_last_error_info(env, &info);

// LOGE is a macro printing to stderr
LOGE(info->error_message);
```
This generates a warning:
```
../src/utils.c: In function ‘assert_and_log’:
../src/utils.c:15:61: warning: passing argument 2 of ‘napi_get_last_error_info’ from incompatible pointer type [-Wincompatible-pointer-types]
     napi_status info_status = napi_get_last_error_info(env, &info);
                                                             ^
In file included from ../src/utils.h:4:0,
                 from ../src/utils.c:1:
/home/fra/.node-gyp/8.2.1/include/node/node_api.h:110:1: note: expected ‘const napi_extended_error_info ** {aka const struct <anonymous> **}’ but argument is of type ‘napi_extended_error_info ** {aka struct <anonymous> **}’
 napi_get_last_error_info(napi_env env,
 ^~~~~~~~~~~~~~~~~~~~~~~~
```

I checked the source code to be sure, and it's indeed an *out* parameter since the user is not supposed to provide it's own `napi_extended_error_info` allocated struct but just a pointer to it..

**Comment by kfarnung** [comment]
In this case it's a non-const pointer to a const struct.  That means that the data in the struct cannot be modified, but the pointer itself can be changed to point to another struct.

Take a look at https://github.com/nodejs/node/blob/master/test/addons-napi/test_general/test_general.c#L71 where the API is used.  Simply adding `const` to your declaration should be enough to get it building without error and attempts to modify the members of the resulting struct will be blocked.

**Comment by nonninz** [comment]
Thank you for your explanation. I didn't know about that.

Sorry for the noise, closing this issue. 🙇

**Comment by kfarnung** [comment]
No problem!
