### ISSUE TITLE
Model for long running module producing data at interval

### ISSUE THREAD

**Issue by renambot-uic** [nodejs/abi-stable-node#273]
(posting here since I went through the nice example repo and didnt find an answer)

I have a long running task that produces data buffers at regular interval (like a stream) and I would like to receive the data in javascript (with a handler or something like ".on('data', func)".

I made it work easily with napi in sequential and of course it blocks the evaluation loop. I converted it to async with a call to 'napi_queue_async_work' and calling 'napi_call_function'. But I get all kind memory corruptions (segmentation fault).

Is that the correct approach ? Should I create a 'async_work' for every callback ?

Thanks for any tips.

**Comment by mhdawson** [comment]
Can you share the code or pointer to a repo with the code ?

Are you porting an existing module or starting from scratch ?

**Comment by renambot-uic** [comment]
Sure, here's a template for the type of module I want to create from scratch:
      https://github.com/renambot-uic/testnapi

I put a couple of alternative in the code (async/sync, buffer creation), but it doesn't work for me (segmentation fault in the buffer creation). I must be missing something in the life cycle of objects and memory management.

Thanks for looking into it.

**Comment by renambot-uic** [comment]
I also tried with node 8.5, same result.

**Comment by addaleax** [comment]
@renambot-uic You can’t call any of the N-API methods that interact with JS values in another thread, that’s always going to give you trouble. That’s what the `complete` callback is there for – the `execute` one needs to store its output (and receive its input) in a non-JS format, so there needs to be a way to do pre-/post-execution processing.

**Comment by renambot-uic** [comment]
Thanks, I think I made it work now.
