### ISSUE TITLE
New APIs to compile and run the script

### ISSUE THREAD

**Issue by levimm** [nodejs/abi-stable-node#274]
This issue is copied from nodejs/node-addon-api (https://github.com/nodejs/node-addon-api/issues/130). I think it's better to raise it here.

Summarize: Is it possible to support Nan like CompileScript and RunScript APIs?

**Comment by gabrielschulhof** [comment]
@levimm we actually already have an issue for this here: https://github.com/nodejs/abi-stable-node/issues/51
