### ISSUE TITLE
Building the api-prototype-chakracore-7.x branch on Linux

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#28]
```
$ ./configure --prefix=${HOME}/sw
...
$ make
...
make[1]: *** No rule to make target '/home/nix/node/abi-stable-node/out/Release
/obj.target/v8_libbase/deps/v8/src/base/debug/stack_trace.o', needed by '/home/
nix/node/abi-stable-node/out/Release/obj.target/deps/v8/src/libv8_libbase.a'.  
Stop.
```

Is there a way around this?

**Comment by gabrielschulhof** [comment]
Judging by https://github.com/nodejs/node-chakracore#how-to-build it's not possible to build node-chakracore on Linux ...

**Comment by digitalinfinity** [comment]
Actually, node-chakracore does build on Linux fine but you need to build the xplat branch- see https://github.com/nodejs/node-chakracore/blob/xplat/README.md for full instructions. 
In this case, the missing step for you is that you need to do ./configure --engine=chakracore.

@boingoing can you investigate why node-v8 is not building in the chakracore branch- if it's an issue not unique to api-prototype-chakracore-7.x, please file an issue in Nodejs/Node-ChakraCore

@thefourtheye btw, can we get your help on Nodejs/Node-ChakraCore#152, precisely to reduce confusion like this

**Comment by gabrielschulhof** [comment]
@digitalinfinity Thanks for the tip! `--engine=chakracore` works on branch api-prototype-chakracore-7.x as well. It's built now :+1:
