### ISSUE TITLE
Get node-addon-api working with version 4.x and 6.x, and older 8.x versions

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#282]

**Comment by mhdawson** [comment]
https://github.com/nodejs/node-addon-api/issues/142

**Comment by NickNaso** [comment]
On my recent porting of bcrypt all compile well on version previous of 8 but when i requere the module i get an error reported here:
https://github.com/kelektiv/node.bcrypt.js/issues/513#issuecomment-337121161
