### ISSUE TITLE
Complete steps needed to get out of experimental

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#284]
https://github.com/nodejs/node/issues/14532

**Comment by aruneshchandra** [comment]
The group agreed on the following criteria to exit experimental status:

|Criteria|Status|
|------|---------|
Multiple implementations of n-api on at least 2 VMs| Done
Define N-API / async_hooks dependency|Done [#14697](https://github.com/nodejs/node/pull/14697)
At least two modules used in real world use cases on at least one VM|In progress. [bcrypt](https://github.com/kelektiv/node.bcrypt.js/issues/513), [weak-napi](https://www.npmjs.com/package/weak-napi) and [iotivity-node](https://www.npmjs.com/package/iotivity-node) (used in academic project "[Campie](http://www.campie.cu.edu.eg/)")
At least two modules that are NPM installable with pre-builds and all unit tests passing| We should continue to enable this, but it does not have any impact on the stability of N-API. Next step is to discuss with TSC to remove this as a blocking criterion

**Comment by aruneshchandra** [comment]
Pre-gyp conversations is on issue #263

**Comment by aruneshchandra** [comment]
[node-zopfli](https://www.npmjs.com/package/node-zopfli) is now being used in production with Edge Dev portal on Node-ChakraCore

**Comment by mhdawson** [comment]
Issue with request to move out of experimental: https://github.com/nodejs/TSC/issues/501

**Comment by mhdawson** [comment]
Closing, out of experimental in master.
