### ISSUE TITLE
Enforce NAPI version in module headers

### ISSUE THREAD

**Issue by kfarnung** [nodejs/abi-stable-node#286]
As discussed today it seems like rather than having developers declare their version specifically it would make sense to enforce it in the header file.

By default only the first version would be exposed and the developer can explicitly opt in using a preprocessor directive:
```cpp
#define NAPI_VERSION  2
#include <node_api.h>
```

I've made the required changes in a [private branch](https://github.com/kfarnung/node/tree/napiver) to start the discussion.  If there are no objections I can go ahead and open a PR in the main repo.

**Comment by mhdawson** [comment]
Looks reasonable.  I think we'll need a doc that captures the approach and update the doc on creating a release so that we include the required steps.

I also think we should discuss if we start enforcing this before/after we exit experimental.

**Comment by kfarnung** [comment]
@mhdawson I can update the documentation for N-API to describe the approach for module authors, is that sufficient?

It would probably make sense to have an answer for this before we exit experimental, but there are more pieces to put into place.  I'm not sure how this would fit into the end-to-end pipeline, for instance how do modules surface this value to npm/node-gyp?

**Comment by mhdawson** [comment]
Updating the N-API documentation works for me.

**Comment by kfarnung** [comment]
Based on discussion in the meeting today we'll set the starting version at 2 (the current shipping N-API version) so we don't break any developers.

**Comment by kfarnung** [comment]
I'm still working on this PR, but I took a stab at trying to figure out the version mapping:

|       | 1       | 2        | 3       |
|:-----:|:-------:|:--------:|:-------:|
| v4.x	|         |          |         |
| v6.x  |         |          |         |
| v8.x  | v8.0.0* | v8.10.0* |         |
| v9.x  | v9.0.0* | v9.3.0*  |         |
| v10.x |         |          | v10.0.0 |

\* Versions 1 and 2 were really loose (during experimental) so these are approximate.

**Comment by kfarnung** [comment]
I opened the initial PR: https://github.com/nodejs/node/pull/19962

**Comment by mhdawson** [comment]
PR landed, closing out.
