### ISSUE TITLE
Detecting NAPI

### ISSUE THREAD

**Issue by jjrv** [nodejs/abi-stable-node#29]
[nbind](https://github.com/charto/nbind#readme) currently detects Node.js using `#ifdef BUILDING_NODE_EXTENSION` and Emscripten using `#ifdef EMSCRIPTEN`. How would I distinguish whether the Node.js version supports NAPI, without using other build tools in the module besides Gyp?

Could there be a macro like `NODE_USE_NAPI` or similar defined in `common.gypi`?

**Comment by mhdawson** [comment]
I think we discussed and answered this in the meeting last Friday.  Once Node supports the API it will be supported in all subsequent versions so checking that version is x or greater should be all that is required.
