### ISSUE TITLE
Get string pointer from napi_value

### ISSUE THREAD

**Issue by how759** [nodejs/abi-stable-node#290]
I notice that **napi_get_value_string_utf8** can write a string from napi_value to a buffer, but this requires copying of the data. How can I derive the row pointer of the string?

**Comment by addaleax** [comment]
@how759 You can’t, because the JS engine might not store the string as UTF-8 (and at least V8 specifically never does that).

**Comment by mhdawson** [comment]
Closing since this was answered and there has been no follow up for quite some time. Please let us know if that was not the right thing to do.
