### ISSUE TITLE
Production usage of N-API

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#293]
Let's list production usage of N-API in this issue.

**Comment by gabrielschulhof** [comment]
Project ["CAMPIE"](http://www.campie.cu.edu.eg/) out of the University of Cairo uses iotivity-node@1.3.1-0, which is built on top of N-API. I'm working with one of the project's participants, [professor Khaled Elsayed](http://www.campie.cu.edu.eg/?q=node/142).

**Comment by NickNaso** [comment]
Project ["Lexgenda"](https://www.lexgenda.com/) Search engine for judgments issued by Italian courts . it use **bcrypt@n-api** which is built on top of N-API. I'm working on this project. I'm the main mantainer.

For more details see at issue [#287](https://github.com/nodejs/abi-stable-node/issues/287)

**Comment by jackhorton** [comment]
[Microsoft Edge Developer Portal](https://developer.microsoft.com/en-us/microsoft-edge) uses [node-zopfli](https://github.com/pierreinglebert/node-zopfli) to compress static assets for browsers that don't support Brotli. This package was converted to N-API using the conversion tool and is being used in production with Node-ChakraCore version 8.9.4. The N-API fork for node-zopfli is available [here](https://github.com/digitalinfinity/node-zopfli/tree/support-napi) and we have opened an issue to discuss merging the N-API version [here](https://github.com/pierreinglebert/node-zopfli/issues/92).

**Comment by mhdawson** [comment]
Done for now
