### ISSUE TITLE
Next weekly meeting - Friday Oct 14 @ 2PM EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#3]
This is the hangout for the next meeting : https://plus.google.com/u/0/events/c0eevtrlajniu7h8cjrdk0f56c8

**Comment by mykmelez** [comment]
@mhdawson Is the next meeting happening this Friday, October 21, at 2pm Eastern?

**Comment by mykmelez** [comment]
> This is the hangout for the next meeting : https://plus.google.com/u/0/events/c0eevtrlajniu7h8cjrdk0f56c8

I tried going to this URL at 3pm eastern today (October 21), but it returned a 404. I'd love to attend the next meeting, whenever it happens. Please keep me in the loop!

**Comment by mhdawson** [comment]
I guess you were hit by the ddos issues today.  It seemed ok for the rest of us.  I won't be there next week but hopefully you can catch up with the rest of the team.  @aruneshchandra, @sampsongao could you two send @mykmelez you direct contact info so he can ping you if he has troubles getting in next week ?

**Comment by sampsongao** [comment]
Contact me at sampsong@ca.ibm.com if you have trouble getting in.

**Comment by mykmelez** [comment]
> I guess you were hit by the ddos issues today. It seemed ok for the rest of us.

Hmm, I did have trouble loading this page from GitHub. But then I remembered that I'd emailed the Google Plus URL to a colleague, so I retrieved it from that message.

And I had no trouble loading the Google Plus page itself. Its domain resolved, and the page loaded quickly, just as it had a few days ago. The server just returned a 404 page, which is also what it did a few days ago, and what it still does now:

<img width="861" alt="screen shot 2016-10-21 at 14 30 49" src="https://cloud.githubusercontent.com/assets/305455/19612391/199304d4-979b-11e6-9e79-e8988b806922.png">

So I don't think my experience is related to the DDOS attack today.

**Comment by sampsongao** [comment]
might be the problem of invitation. Can you send me your google account so that I can send you an invitation.

**Comment by mykmelez** [comment]
> might be the problem of invitation. Can you send me your google account so that I can send you an invitation.

Hmm, after signing into Google+ with my myk@mykzilla.org account (the same one I use for GitHub), I received a different page, which said I needed an invitation. I then pressed the button to request one, so presumably there's an invitation request pending.

**Comment by sampsongao** [comment]
might be the problem of invitation. Can you send me your google account so that I can send you an invitation.


Sampson

________________________________

**Comment by mykmelez** [comment]
> might be the problem of invitation. Can you send me your google account so that I can send you an invitation.

@sampsongao There should be an invitation request pending, per https://github.com/nodejs/abi-stable-node/issues/3#issuecomment-255610265, but in any case the Google account you can use to send me an invitation is myk@mykzilla.org.

**Comment by sampsongao** [comment]
Can you see the event page now?

**Comment by mykmelez** [comment]
> Can you see the event page now?

Yes, thank you, I can see it now! Unfortunately, I missed today's meeting. But I'll attend next week's.
