### ISSUE TITLE
Adding a data pointer for calling a C function

### ISSUE THREAD

**Issue by jjrv** [nodejs/abi-stable-node#30]
`node_jsvmapi.h` currently says:

```C++
// Consider: Would it be useful to include an optional void* for external data
// to be included on the function object?  A finalizer function would also need
// to be included.  Same for napi_create_object, and perhaps add a
// napi_set_external_data() and get api?  Consider JsCreateExternalObject and
// v8::ObjectTemplate::SetInternalFieldCount()
NODE_EXTERN napi_value napi_create_function(napi_env e, napi_callback cbinfo);
```

nbind creates one C++ wrapper function for each signature (combination of argument and return types), so it then needs to pass a number telling which C++ function among those with identical signatures is actually referred to by that `napi_value`. NAN allows doing:

```C++
Local<FunctionTemplate> functionTemplate = Nan::New<FunctionTemplate>(
  functionPointer,
  Nan::New<v8::External>(data)
);
```

It stores the data pointer in an internal field:

```C++
v8::Local<v8::Value> val = v8::Local<v8::Value>::New(isolate, data);

if (!val.IsEmpty()) {
  obj->SetInternalField(imp::kDataIndex, val);
}
```

It will then read that field when calling the C++ function, passing it inside the equivalent of `napi_func_cb_info`:

```C++
FunctionCallbackInfo<v8::Value>
  cbinfo(info, obj->GetInternalField(kDataIndex));
callback(cbinfo);
```

So the NAPI equivalent could be a function like:

```C++
napi_value napi_get_cb_data(napi_env e, napi_func_cb_info cbinfo);
```

I don't think there's a need for a finalizer function here? Instead if needed, the programmer could pass the data value to `napi_create_weakref` which should also allow passing it a finalizer. Currently it doesn't seem to take one and just sets up this empty finalizer instead:

```C++
static void WeakRefCallback(const v8::WeakCallbackInfo<int>& data) {
}
```

See [here](https://github.com/nodejs/abi-stable-node/blob/5cd092101dcdfda89909aa334edf3170b6b0023f/src/node_jsvmapi.cc#L748-L749) and [here](https://github.com/nodejs/abi-stable-node/blob/5cd092101dcdfda89909aa334edf3170b6b0023f/src/node_jsvmapi.cc#L159-L160).

**Comment by jasongin** [comment]
I implemented this as part of the refactoring of function callbacks that I did for [property accessors](https://github.com/nodejs/abi-stable-node/issues/44).

**Comment by jasongin** [comment]
Fixed in the 6.2 branch with https://github.com/nodejs/abi-stable-node/commit/67f4581fd711cbb8bec0858f4c653e86792e4aae

To be ported to other branches soon.

**Comment by mhdawson** [comment]
@jjrv can you confirm that what was added satisfies your use case ?

**Comment by jasongin** [comment]
Specifically, this is supported via the new `data` parameter of [`napi_create_function()`](https://github.com/nodejs/abi-stable-node/blob/api-prototype-6.2.0/src/node_jsvmapi.h#L233), and the new [`napi_get_cb_data()` function](https://github.com/nodejs/abi-stable-node/blob/api-prototype-6.2.0/src/node_jsvmapi.h#L233) to retrieve that data pointer from the callback info.

**Comment by jasongin** [comment]
Closing since the `data` parameter was added a while ago.

There is no direct support for finalization of the `data` pointer, but it can be accomplished by creating an external value (`napi_create_external()`) with the same `data` pointer, then attaching that as a property on the function.
