### ISSUE TITLE
Create workshop for Node Summit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#302]

**Comment by mhdawson** [comment]
Target for first outline is May 4

**Comment by jschlight** [comment]
> This is proposed outline 

# An N-API Workshop

## Abstract

Ready to get your hands dirty with N-API, Node's new ABI-stable native add-on API? Don't miss this workshop. Whether you're maintaining a NAN module, looking to start a new add-on using N-API, or are interested in porting existing native add-ons to N-API, we're here to get you started right. After a brief introduction you'll have the chance to work through a tutorial or bring your project and N-API experts will be available to help you through any issues. You'll leave with a solid understanding of N-API and the tools available to help you best succeed. 

## Objectives

- Help existing and first-time native module maintainers to get started with N-API

- Orientation to best practices

- Offer hands-on assistance during the workshop for projects of importance to the participants

- Offer tips, tools, and resources participants can use after the workshop

- Solicit suggestions and ideas to improve N-API and it's supporting ecosystem

## Concept

The idea would be to offer some opening remarks about N-API in general. We might then poll the participants to determine how many are brand new to native modules and how many are attempting to port an existing module to N-API. It would be good to know how many have brought a specific project to work on and how many are there to get a start with N-API. 

Based on the feedback, we could then split up the group and the facilitators could then concentrate on a specific group, but still be available for other questions.

The second part of the workshop would comprise of working directly with participants.

## Topics

### Part 1 - Brief introductory remarks

- Poll participants about interest in today's workshop

- Benefits of N-API — ABI stable, works across JavaScript engines

- Available tools and online tutorials

### Part 2 - Hands-on assistance

- One group working through the initial tutorials

- The other group working through migrating an existing module

### Part 3 - Wrap up

- A verbal evaluation of the workshop, how might it be improved?

- Suggestions for improving N-API in general?

- Questions?

**Comment by jschlight** [comment]
I am preparing two online tutorials to accompany this workshop.

- Creating an N-API module using the `generator-napi-module` package
- Migrating an existing native module to N-API

I'll have these tutorials ready for review in time for the May 17 meeting.

**Comment by jschlight** [comment]
@aruneshchandra @NickNaso @gabrielschulhof FYI.

I've uploaded the two tutorials for everyone's review. I'm anxious to receive your comments and suggestions for improvement. 

- [Creating an N-API module using the `generator-napi-module` package](https://napi.inspiredware.com/getting-started/first.html)
- [Migrating an existing native module to N-API](https://napi.inspiredware.com/getting-started/migration.html)

A primary objective is to keep the two tutorials succinct enough for a conference environment.

**Comment by NickNaso** [comment]
Hi @jschlight I looked at your examples and I think that we need to provide an example of how to create an asynchronous function through `AsyncWorker` and maybe how to use `Buffer`. 
For me it's important to say that all the functions  are normally executed on the **event loop** and if you want execute a long running task you have to write **asynchronous function**. 
When you want pass a great quantity of data between JS and C++ and vice versa it's very useful use the buffer to achieve good performance.
The buffer object is a particular JavaScript object that uses the memory outside of JavaScript engine heap. All this means that the buffer object is not subject to multi-threading rules of JavaScript engine and you can interact with it **in place** from C++. 

I know that we need to keep the tutorials succinct for a conference, but it could be interesting find a space to expose the two concepts that I reported.

**Comment by jschlight** [comment]
Thank you, @NickNaso. Let's discuss this further tomorrow.

**Comment by gabrielschulhof** [comment]
@jschlight 
"This package makes working with N-API much easier as it implements a very nice object model and abstracts away much of the detailed coding that would otherwise be required."
We should add ", while retaining the N-API promise of ABI stability and forward compatibility."

**Comment by gabrielschulhof** [comment]
"This is a sample C++ file that shows how to use power..." *the* power

**Comment by jschlight** [comment]
Here's an initial set of slides for everyone's review. 

I'm hoping Thursday we can discuss the idea of uploading theses slides to a collaborative online site where we can work as a group to continue to refine the workshop. 

# N-API Workshop Slides

## Welcome and introductions

## Workshop schedule

- Introductory remarks

- Online tutorials

- Work on individual projects

- Wrap-up and assessment

## Objectives of the workshop

- Orientation to N-API

- Awareness of available tools and processes

- A good start on your own projects

## Motivations for N-API

- Abstraction of the underlying JavaScript engine

- A binary-stable ABI

## A brief history of N-API

- Project inception

- Development work

- Support for ChakraCore

- N-API leaves experimental status April 2018

- Back-porting status

- Ongoing work, invitation to the Working Group

## How N-API differs from NAN

- Not tied to a specific JavaScript engine

- Offers a binary-stable API

- Includes a C++ wrapper

## Supporting resources

- N-API Documentation 

- N-API migration assistant

- node-pre-gyp

- prebuild

## Online Tutorials

- For starting a new add-on module from scratch

- For migrating an existing NAN module

## Opportunity to work on individual projects

- Workshop presenters available for help and questions

## Wrap-up and assessment

- Solicit comments and suggestions concerning the workshop and N-API

- Extend another invitation to participate in the Working Group

**Comment by gabrielschulhof** [comment]
"The file defines a FirstProject JavaScript class and the exports it." It should be "then exports it", I think.

**Comment by gabrielschulhof** [comment]
"This code demonstrates how to use the FirstProject JavaScript class defined in /lib/binding.js." IINM customarily the path is given as "lib/binding.js", so as to avoid using absolute paths.

**Comment by gabrielschulhof** [comment]
@jschlight the above comments refer to the "A first project" section of your tutorial. Sorry for not mentioning that before!

**Comment by jschlight** [comment]
Thanks, @gabrielschulhof  I'm integrating your suggestions.

**Comment by gabrielschulhof** [comment]
@jschlight in your migration tutorial, in the section "Run the conversion tool" the first code snippet contains
```
npm install node-addon-api
```
Perhaps that should be `npm install --save node-addon-api` because it will remain part of the project afterwards.

**Comment by gabrielschulhof** [comment]
Style nit: In "A new way to define exports" and below "Needs to be replaced with:" there should be no space after `exports.Set`.

**Comment by gabrielschulhof** [comment]
In "What is N-API?" we should maybe add "without the need for running `npm install` again" to the end of "This means that a module you create today will continue to run on all future versions of Node."

**Comment by jschlight** [comment]
Here is a comment link to the Google Slides. https://docs.google.com/presentation/d/1nBw8QNWDzMe-8QEYSnvJDNPWYMvmbmUz-mtnGZuiWLE/edit?usp=sharing 
Please let me know if you would like edit access.

**Comment by gabrielschulhof** [comment]
@jschlight I created some slides to explain the concept of ABI stability:

https://gabrielschulhof.github.io/presentations/abi-stable.pdf

Do you think it's worth integrating them into theworkshop's opening remarks?

**Comment by mhdawson** [comment]
@jschlight requested edit access.

**Comment by NickNaso** [comment]
Hi everyone,
in my last talk one of the question that attendees asked me is if it could be possible use programming language different from C or C++. 
At that time  my answer was that the only alternative that I know was  [https://github.com/neon-bindings/neon](https://github.com/neon-bindings/neon) a Rust bindings that uses the classical v8 API. 
In the last days I started thinking that if N-API guarantees the API and ABI stability it will became very simple create the bindings with other programming languages that allow to execute the call to C code. 
Maybe I'm wrong but with N-API the bindings with other language will became more simple and stable.
For now I found this [https://github.com/napi-rs](https://github.com/napi-rs). 
I don't know if we want underline this aspect on the slides for the workshop.

**Comment by mhdawson** [comment]
From my understanding, I think it should be possible to support other languages as C is going to be one of the easier languages to interface to.  I think it would be fairly low in our priority list to support a different language but if somebody wanted to build/figure it out I think we'd be happy to include the documentation/pointers.

**Comment by jschlight** [comment]
I've posted an [AsyncWorker Tutorial](https://napi.inspiredware.com/special-topics/asyncworker.html) in preparation for the workshop at Node Summit. I am open to any suggestions for improvement. I'll be able to get back to this on Monday.

**Comment by gabrielschulhof** [comment]
@jschlight 

> The AsyncWorker class was introduced in Node 10.5.0 and is not available in earlier versions. 

I don't understand. We have `napi_create_async_work()` in all maintained versions of Node.js, and AFAICT we've had `AsyncWorker` in node-addon-api for a while too.

**Comment by gabrielschulhof** [comment]
> The Excute method has no access to any part of the N-API environment.

typo

**Comment by gabrielschulhof** [comment]
> The OnOK method is called after the Execute method returns unless the Execute method call SetError or in 

*calls

**Comment by gabrielschulhof** [comment]
@jschlight you need to instantiate a handle scope inside `OnOK` because, although you have access to the N-API environment, your code is at the top of the stack. That is, your code was not called from JavaScript, and therefore no handle scope was set up in which to create JavaScript values.

**Comment by gabrielschulhof** [comment]
> The runSimpleAsyncWorker function, which is accessible from JavaScript takes two arguments

There should be a comma before "takes"

**Comment by gabrielschulhof** [comment]
> The first argument, which is passed as info[0] is the runTime

There should be a comma after `info[0]`

**Comment by gabrielschulhof** [comment]
@jschlight you can use `AsyncWorker::Cancel` from the main thread to cancel async work.

**Comment by jasongin** [comment]
Hi all, I will be attending Node Summit again this year! While my primary trip purpose is not about N-API, I do plan to come to this workshop and try to help out if I can.

**Comment by mhdawson** [comment]
Sounds good :)

**Comment by jschlight** [comment]
Thank you, @gabrielschulhof. I've published your recommendations.

**Comment by mhdawson** [comment]
@jschlight a few comments

# Conversion workshop
I'd suggest changing `But` to `However.` in

However, the conversion tool will only get you so far. Further manual cleanup is still required as described below.


# Async Worker

I'm not sure this is true 
`Note that unlike Execute, the OnOK and OnError methods do have access to the N-API environment. In order to correctly setup this access in these methods, the HandleScope object must be instantiated as a local as shown in the code.
`

as a HandleScope seems to be created in OnWorkComplete. 

It might be worth mentioning the need for a Scope if you override OnWorkComplete though.

**Comment by jschlight** [comment]
Thank you @mhdawson. I've incorporated the changes you recommended. 

I've removed all references to `HandleScope`. It looks like `AsyncWorker:: OnWorkComplete` is `private` and not `virtual`, so I'm not sure it will be overridden. But if I'm mistaken, I can easily add the warning. 

I've uploaded a [node-pre-gyp tutorial](
https://napi.inspiredware.com/special-topics/node-pre-gyp.html) for Node Summit and would welcome any suggestions to improve it.

**Comment by gabrielschulhof** [comment]
@jschlight the new tutorial is great!

I found a single typo:

-if a sutable binary cannot be located to download
+if a suitable binary cannot be located to download

**Comment by jschlight** [comment]
Thank you, @gabrielschulhof. I've made the fix. Best of luck with the workshop today!

**Comment by mhdawson** [comment]
I think we can close this as the workshop was help and a success!

We probably want a new issue for the next workshop though.
