### ISSUE TITLE
WeakMap support

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#312]
> N-API can already create and manipulate a Array, but there is no support
to create and manipulate a WeakMap, which may sometimes be useful for
internally attaching extra data to arbitrary objects.
> 
> (You might be able to define your own finalizer callbacks also using a
WeakMap anyways, by giving a key for the object to check, and the value
being a external value with a finalizer callback defined, so that it will
be called when the key object is finalized; I don't know whether or not it
will work, but it seems like it is allowed to work, at least.)

**Comment by gabrielschulhof** [comment]
Re: https://github.com/nodejs/node/issues/14256

**Comment by bnoordhuis** [comment]
> but there is no support to create and manipulate a WeakMap

There's no support for that in the V8 C++ API either.

**Comment by gabrielschulhof** [comment]
There is always the roundabout way of obtaining the JS API using `napi_get_global()` and `napi_get_named_property()`.

**Comment by bnoordhuis** [comment]
Sure, but why would you want to?  At that point you're just adding API sugar.

**Comment by gabrielschulhof** [comment]
Oh, definitely. There's not even a performance benefit, since you're not saving yourself a trip into JS by using a native API, because, as you pointed out, the native API does not exist. Of course, *other* engines may have such an API, but I guess when we're faced with that, we can reconsider this issue. I guess we can close this issue.
