### ISSUE TITLE
Generator function APIs

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#315]
> A way to create generator functions with N-API functions. (You can already
fake it, but real generator functions may help a bit better, will work if
you use the actual generator methods rather than others with the same
name, and may be more efficient in some cases maybe.)
> 
> Attaching a finalizer callback to the generator object can also help.

**Comment by gabrielschulhof** [comment]
Re: https://github.com/nodejs/node/issues/14256

**Comment by bnoordhuis** [comment]
How would that work?  Note that V8 won't let you create generator functions from C++ either.

**Comment by mhdawson** [comment]
I think we can close this. We've not actioned it for a number of years. Closing, please let us know if you think that was not the right thing to do.
