### ISSUE TITLE
node-rfc ported

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/abi-stable-node#320]
Hi N-API team and thank you very much for stabilising native Node API.

I ported the [node-rfc](https://github.com/SAP/node-rfc/tree/napi) module from Nan and experienced no big issues.

What would be the best way to get more feedback from your team and further discuss topics like [type checks](https://github.com/nodejs/node-addon-api/issues/265) or potential  AsyncWorker enhancements?

**Comment by NickNaso** [comment]
Hi @bsrdjan,
good work. I think that we can discuss through the issues on **[node-addon-api](https://github.com/nodejs/node-addon-api)** and then if you want more explanation I think that it could be possible to partecipate at our weekly meeting and ask us all you need.

**Comment by bsrdjan** [comment]
Thanks !
