### ISSUE TITLE
Object lifetime clarification

### ISSUE THREAD

**Issue by TravisGesslein** [nodejs/abi-stable-node#321]
The docs mention that any objects created within a native method call that was triggered in javascript are bound to a scope that is destroyed when the method has finished executing. 

What happens when an object created inside that method is returned by the method?

e.g.

```
var test = module.method();

//in the c native method
napi_value method(napi_env env, napi_callback_info info)
{
   napi_value object;
   napi_create_object(env, &object);
   return object;
}

```

Also, what happens when you bind an object created in that method as a property to some other object via napi? Does that automatically extend its lifetime? 

Do I still have to manually create references to those objects when I create them, to guarantee they stay alive? Also, if I do it that way, how do I detect when a user does something like

```
test =null;
```

So I can correctly decrement the ref counter and destroy it?

**Comment by NickNaso** [comment]
Hi @Heishe,
when you return an object from native method you are returning a copy of that object. In your example you are returning a copy of an object and it will be managed by JS Engine. This means that you do not care if a user of your native function does something like you reported:
```js
test = null;
```
In this case the JS Engine will garbage collect `test` as any other JavaScript object.

In general  you have to remember that when you pass primitive data from JavaScript side to C++ these data will be copied from memory managed by JS Engine to memory used by C++ and after your computation the results will be copied from C++ memory to memory managed by JS Engine.

**Comment by TravisGesslein** [comment]
Thanks for the answer. Is the same true when you assign an object to another one as a property via napi_define_properties (i.e. a copy is assigned, the original discarded after the method ends)?

**Comment by gabrielschulhof** [comment]
Technically, the parent object obtains a reference to the child object
after the assignment is made. The reference you used when making the
assignment becomes invalid as soon as the method ends.

**Comment by TravisGesslein** [comment]
Thanks, that makes sense.
