### ISSUE TITLE
Merge abi-stable-node-addon-examples into node-addon-examples

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#326]
@nodejs/addon-api what do you think? Now that N-API is part of Node.js and backported to all supported versions, shall we merge the ABI stable examples into the main repo?

**Comment by mhdawson** [comment]
I think its a good idea, just have not had time to do it.  We'd need to update some other references in the docs but overall I think its time.  We'd need agreement from the overall set of Node.js collaborators as well.

**Comment by NickNaso** [comment]
I agree on the idea proposed by @gabrielschulhof and I'm available to help.

**Comment by gabrielschulhof** [comment]
@mhdawson it seems the node-addon-examples repo is now read-only, so I cannot make a PR against it.

**Comment by gabrielschulhof** [comment]
So far, I have https://github.com/nodejs/node-addon-examples/compare/master...gabrielschulhof:n-api-examples

**Comment by mhdawson** [comment]
We'll have understand if they have been moved somewhere else?

**Comment by gabrielschulhof** [comment]
@mhdawson the [documentation](https://nodejs.org/api/addons.html) states:

> All of the following examples are available for [download](https://github.com/nodejs/node-addon-examples) and may be used as the starting-point for an Addon.

The "download" link points to the read-only repo.

**Comment by gabrielschulhof** [comment]
@Trott @mhdawson @jasnell @mcollina I'd like to ping some of you regarding a potential TSC discussion on this topic. We'd really like to post some N-API examples, both C and C++ via node-addon-api, and we already have a [repo](https://github.com/nodejs/node-addon-examples/) that has examples in it, but it is substantially out of date. May we have the repo reactivated so that we might add the N-API examples? If we do, we would likely have to clean out examples against Node.js versions we no longer support. Also, if we reactivate the repo, shall we maintain NAN examples, and examples against supported Node.js versions, or just N-API examples?

If the latter, it might be better to start a separate repo altogether – perhaps n-api-examples.

May we have your thoughts on this matter, and is this something that needs to be placed on the TSC agenda?

**Comment by gabrielschulhof** [comment]
https://github.com/nodejs/node-addon-api/issues/241#issuecomment-413664162 and https://github.com/nodejs/help/issues/1412#issuecomment-411162564 could both benefit from an example.

**Comment by Trott** [comment]
> May we have your thoughts on this matter, and is this something that needs to be placed on the TSC agenda?

@gabrielschulhof Definitely no reason to put this on the TSC agenda, at least not at this time. That should be a last resort.

I don't have an opinion on which of the two ways you outline is the right path, but either way, the document to review for the correct process is https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories. The process is basically: Figure out whether you want to resume use of the old repository or create a new one, and then open an issue in the admin repository. Unless someone on CommComm or TSC objects within 72 hours, the request is considered approved.

**Comment by mhdawson** [comment]
I'd say we should re-use the name of the original repo.  We were hoping to get some context as to why its archived, but if we can't find that then just proposing we re-use makes sense to me.

**Comment by gabrielschulhof** [comment]
This has landed.
