### ISSUE TITLE
optimize passing arguments from js to c

### ISSUE THREAD

**Issue by jorangreef** [nodejs/abi-stable-node#327]
See https://github.com/nodejs/abi-stable-node/issues/55#issuecomment-403192587 for context.

**Comment by jorangreef** [comment]
> @jorangreef I tested the uint32_t truncation, and AFAICT it's working as advertised. Please have a look at the PR and let me know if I've missed any scenarios!

Thanks @gabrielschulhof, I see that you asserted that overflow happens when calling `napi_get_value_uint32()` on a JS value that is more than 32 bits: `testUint32(4294967297, 1);`

What I meant was that if the JS value is more than 32 bits, I would have expected an exception to be thrown instead. However, this kind of check should rather be in `napi_get_value_uint32_validated()` (or something like that) to avoid slowing down `napi_get_value_uint32()`.

> I just realized that using a large ArrayBuffer to hold the arguments implies that the memory for the two Buffers is contiguous, otherwise it requires copying. Is this the case for your addon and, if not, can you rearrange the memory to make this the case?

Yes, I thought of this but the addon needs to be zero-copy, and the `key` and `value` buffer arguments would not necessarily always be the same.

> @jorangreef I'm curious - are you using N-API directly, or via the node-addon-api package?

I am using N-API directly, using `#include <node_api.h>` running Node v10.6.0.

Thanks for all your help with this!

**Comment by jorangreef** [comment]
I know we always compare N-API to v8, but is there any chance that some of the v8 methods we're comparing against are slower than they should be?

**Comment by gabrielschulhof** [comment]
@jorangreef when I build the comparison binding in V8 I try to use the most efficient method for grabbing the arguments from the engine.

**Comment by gabrielschulhof** [comment]
@jorangreef have you tried switching from `node::Buffer` to `ArrayBuffer`? AFAICT, `node::Buffer` uses an [`ArrayBufferView`](https://github.com/nodejs/node/blob/573744caaedf2f941e152b8e9533cd5629d55c1c/src/node_buffer.cc#L204-L231) which seems to be an additional level of indirection.

**Comment by gabrielschulhof** [comment]
I tested some more combinations, and it looks like if you switch to `ArrayBuffer` and we provide validation-free versions of `napi_get_arraybuffer_info()` and `napi_get_value_int64()` then we can nearly erase the impact of switching from V8 to N-API.

![More Buffer/ArrayBuffer/Int64 Combinations](https://user-images.githubusercontent.com/976081/42585326-4b4f5124-8503-11e8-8087-c382ba23f3c9.png)

@nodejs/addon-api this supports that we should provide validation-free versions of the convert-to-native-type APIs.

**Comment by gabrielschulhof** [comment]
The code: https://github.com/nodejs/node/compare/master...gabrielschulhof:55-abi-stable-node

**Comment by mhdawson** [comment]
Sorry I could look at the code, but for clarity in this issue, what do you mean by "validation-free"

**Comment by gabrielschulhof** [comment]
@mhdawson by "validation-free" I mean a version of the API where we don't call APIs such as `->IsNumber()` after casting the `napi_value` as a `v8::Local<v8::Value>`. We simply assume that it's a number and retrieve the value.

Similarly, we do not validate that the `napi_value` is a `v8::ArrayBuffer`, but we simply `.As<v8::ArrayBuffer>()` and then proceed to retrieve the pointer to the data and the length.

We leave the validation (if any) to the addon author and document that the API doesn't perform any validation, all in the name of better performance.

**Comment by gabrielschulhof** [comment]
@mhdawson I ran individual benchmarks for each data type to test whether removing the validation would improve the performance to some significance, but the only data type for which this was the case was `Int64`. All the convert-to-native APIs have pretty much the same performance whether or not we validate.

I suspect that's because in `napi_get_value_int64()` we not only validate that the value we are asked to convert to native is indeed a JavaScript number, but we also perform some sanitization of the value:

```C++
  if (val->IsInt32()) {
    *result = val.As<v8::Int32>()->Value();
    return napi_clear_last_error(env);
  }

  RETURN_STATUS_IF_FALSE(env, val->IsNumber(), napi_number_expected);

  // v8::Value::IntegerValue() converts NaN, +Inf, and -Inf to INT64_MIN,
  // inconsistent with v8::Value::Int32Value() which converts those values to 0.
  // Special-case all non-finite values to match that behavior.
  double doubleValue = val.As<v8::Number>()->Value();
  if (std::isfinite(doubleValue)) {
    // Empty context: https://github.com/nodejs/node/issues/14379
    v8::Local<v8::Context> context;
    *result = val->IntegerValue(context).FromJust();
  } else {
    *result = 0;
}
```

the performance gain stems from reducing all this to just
```C++
    *result = val->IntegerValue(context).FromJust();
```
foregoing the special-casing mentioned in the comment.

So, a new, non-validating API really only makes sense for Int64:

![napi-fast-string](https://user-images.githubusercontent.com/976081/42965086-effc0d2a-8b66-11e8-9e41-8902d0a4b96c.png)

![napi-fast-double](https://user-images.githubusercontent.com/976081/42965138-210c258a-8b67-11e8-8267-d4461eeab88d.png)

![napi-fast-int64](https://user-images.githubusercontent.com/976081/42965286-87811d20-8b67-11e8-9edc-0710197344ab.png)

**Comment by jorangreef** [comment]
> I tested some more combinations, and it looks like if you switch to ArrayBuffer and we provide validation-free versions of napi_get_arraybuffer_info() and napi_get_value_int64() then we can nearly erase the impact of switching from V8 to N-API.

Thanks @gabrielschulhof for the tremendous effort.

**Comment by mhdawson** [comment]
@gabrielschulhof thanks for all of the analysis. One last question, 

Did you check the perf  if this part is left in

```
  if (val->IsInt32()) {
    *result = val.As<v8::Int32>()->Value();
    return napi_clear_last_error(env);
  }
```

**Comment by gabrielschulhof** [comment]
@mhdawson we can leave it in. It has no perf impact.

**Comment by mhdawson** [comment]
Looks like the related PR has landed. Closing.
