### ISSUE TITLE
Content for Milestone 11

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#329]
* Focus on AsyncWorker, there are a number of issues/problems we should work through
* Continued focus on burning down issues in the 2 repos
* Evangelism
  * Prepare presentation for JS interactive (Michael and Arunesh)
  * Breakout session at collaborator summit - https://github.com/nodejs/summit/issues/100#issuecomment-410011700
    * cover the code layout and how to jump in - node-addon-api and core
    * also cover node code ways to contribute
  * Github badge for N-API

* Rationalize abi-stable-node-addon-examples into node-addon-examples https://github.com/nodejs/abi-stable-node/issues/326
* Expand test suite
  * Start by using examples in test suite

**Comment by digitalinfinity** [comment]
One of the things that @seldo had suggested when we met at Node Summit was to introduce a GitHub badge for N-API modules that we could PR on the Readme for N-API modules. Should we consider this for milestone 11 as part of evangelism?

**Comment by digitalinfinity** [comment]
btw, this is a great set of items to track for milestone 11- thanks @mhdawson for writing it up!

**Comment by NickNaso** [comment]
Work on examples:
- Merge **abi-stable-node-addon-examples** into **node-addon-examples** see: https://github.com/nodejs/abi-stable-node/issues/326
- Use examples in test suite

**Comment by mhdawson** [comment]
@digitalinfinity and @NickNaso 2 great suggestions, lets review the overall list in this weeks meeting.

**Comment by jschlight** [comment]
As part of our evangelism work, we might want to propose an N-API "birds of a feather" session for the Node Community Corner at JS Interactive to be scheduled after Michael and Arunesh presentation. It would be a chance for those whose interest is raised by Michael and Arunesh's talk to meet face-to-face with N-API team members to discuss their projects.

**Comment by mhdawson** [comment]
@jschlight great idea, do you want to propose that?  I know its past the deadline but we can still ask if there is room.

**Comment by mhdawson** [comment]
If its not possible to submit through the original process then ping @ladyleet

**Comment by mhdawson** [comment]
Initial content agreed, closing
