### ISSUE TITLE
JS Interactive 2018, Node Community Corner Session

### ISSUE THREAD

**Issue by jschlight** [nodejs/abi-stable-node#331]
Here's my proposal for the JS Interactive 2018 Node Community Corner. I'm open to comments and suggestions before I submit it to the conference which should happen tomorrow at the latest. 

### First Name and Last Name

Jim Schlight

### First Names and Last Names of additional panelists or presenters

Arunesh Chandra, Michael Dawson, Nicola Del Gobbo, Gabriel Schulhof (pending)

### Type of talk

Birds of a feather

### Topic Title

N-API Birds of a Feather

### Topic Abstract

Are you working on a Node native add-on using N-API? Or maybe thinking of starting one? This is a great opportunity to consult with the team behind this compelling new technology and to discuss experiences with fellow N-API add-on developers. Ask questions, make suggestions, and learn how you can help shape the future of N-API.

Bring your project and N-API team members will be available to help answer questions, make suggestions, and offer tips. If you don't have a project, team members can answer your questions and help make sure you get off to a solid start.

This is also a great chance for N-API add-on developers to share experiences, lessons, and best practices with fellow N-API add-on developers. 

If you're interested, please join us!

Note: Arunish & Michael will be making a presentation on N-API during JS Interactive. It would be really good if this birds of a feather could be scheduled after Arunish & Michael's talk. 

### Duration of talk

30 minutes

**Comment by NickNaso** [comment]
It's good to me!

**Comment by jschlight** [comment]
Thank you @NickNaso. I've submitted the proposal to Node Community Corner Topics as shown here.

**Comment by mhdawson** [comment]
@jschlight thanks for putting together and submitting :)

**Comment by mhdawson** [comment]
It's on the schedule :)

**Comment by mhdawson** [comment]
Jim to bring deck for Workshop, we'll start by displaying the resouces page

Michael to bring deck on node-addon-api, Michael+ Arunesh to bring deck from Conference.

**Comment by mhdawson** [comment]
Session held.
