### ISSUE TITLE
Document limitations of the ABI stability offered by N-API

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#332]
I opened a [PR](https://github.com/nodejs/node/pull/22508) with some documentation modifications to remind that the ABI stability offered by N-API goes away if add-ons link to other Node.js APIs and/or external non-ABI-stable libraries.

AFAICT the two doc files touched by the PR are the only ones where it makes sense to mention this.

**Comment by gabrielschulhof** [comment]
That PR has now landed. It touches doc/api/addons.md and doc/api/n-api.md. Perhaps we should add a similar blurb to node-addon-api's documentation.

**Comment by NickNaso** [comment]
@gabrielschulhof I think that we can write a brief recap on `README` and then link to a specific section where we would deeply explain what means ABI stability.

**Comment by gabrielschulhof** [comment]
@NickNaso I must've read your mind 🙂 https://github.com/nodejs/node-addon-api/pull/326

**Comment by gabrielschulhof** [comment]
@NickNaso I don't have the link to the deep explanation yet, but maybe that belongs into the main repo and we can link to it there.

**Comment by NickNaso** [comment]
@gabrielschulhof And if we create a file inside the `doc` folder (e.g abi_stability.md) and write all the necessary things about ABI stability there?

**Comment by gabrielschulhof** [comment]
@NickNaso I'd rather do it in the main repo, because ABI stability is offered by N-API, not node-addon-api, so I'd like to reuse the explanation for those using N-API directly.

**Comment by NickNaso** [comment]
@gabrielschulhof Ok so we can just link it from `node-addon-api`.

**Comment by mhdawson** [comment]
PR landed on node-addon-api.

**Comment by mhdawson** [comment]
Need to check if equivalent has landed in core @gabrielschulhof

**Comment by gabrielschulhof** [comment]
@mhdawson the equivalent has landed in core: https://github.com/nodejs/node/pull/22508

This issue cannot be closed yet because in the above comments starting at [this one](https://github.com/nodejs/abi-stable-node/issues/332#issuecomment-418379903) @NickNaso and I talk about creating a document inside the Node.js main repo's documentation subdirectory that explains the issues of ABI stability in detail.

**Comment by mhdawson** [comment]
Outstanding issue was to created detailed info on, has created PR on core: https://github.com/nodejs/node/pull/23229

**Comment by mhdawson** [comment]
Landed all updates.
