### ISSUE TITLE
Discuss how we should advocate the use of badges in our documentation

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#333]
https://github.com/nodejs/admin/issues/221 opens the discussion on whether/how we should document that we recommend that add-on maintainers use badges to indicate that their module in N-API-based.

**Comment by gabrielschulhof** [comment]
Seems like there are no objections, so we can start opening PRs advocating the use of badges of the form `[N-API|v<n>]` where `n` is the N-API version number. Shall we go with `[N-API|vx]` if the addon needs experimental? That will later be replaced by the addon maintainer with a number once the API goes out of experimental. Maybe whenever choosing experimental, the colour should not be green, because depending on experimental carries with it a small chance of ABI breakage.

**Comment by mhdawson** [comment]
I'd agree with not being green if it uses experimental.  Otherwise N-API|v<n> sounds good to me.

**Comment by digitalinfinity** [comment]
Yup, seems like a reasonable plan

**Comment by mhdawson** [comment]
PR to add some text to node core https://github.com/nodejs/node/pull/22801#pullrequestreview-157171072

**Comment by mhdawson** [comment]
@gabrielschulhof Updated abi-stable-node readme repo, will land once 72 hours is up.

Next gabriel will suggest text on badges go into update readme.

**Comment by gabrielschulhof** [comment]
Since the issue in the core repo was closed, if/when we PR this, we should PR this against the README.md in this repo.

**Comment by gabrielschulhof** [comment]
At today's N-API meeting we discussed the possibility of suggesting at our N-API workshop that a badge be included in a PR that ports a module to N-API.

**Comment by mhdawson** [comment]
@gabrielschulhof  submitted this pull request: https://github.com/nodejs/abi-stable-node/pull/357
