### ISSUE TITLE
ShadowNode: another implementation of N-API

### ISSUE THREAD

**Issue by yorkie** [nodejs/abi-stable-node#334]
Hey @nodejs/n-api team, I'm previously one of the active collaborators, but this time I just wanna change my role to be the creator of [ShadowNode], another Node.js program runtime which is doing implement and implemented N-API outside of the Node.js project. So I call this to be _N-API enabled runtime_.

> See https://github.com/Rokid/ShadowNode/blob/master/docs/api/N-API.md for our supported list for N-API.

### Why this issue?

My purpose to open this issue here has the following reasons:

- make [ShadowNode] promotion to @nodejs/n-api team.
- some suggestions to make integrating N-API to another JavaScript engine easier.
- proposal to add new README section "N-API enabled runtimes".

### What's the ShadowNode?

It's inspired and forked from the another popular project [IoT.js] which is for writing JavaScript program in low-end device(RAM < 1MB). but our target device is up to 10MB. Within this better environment, we have added more Node.js features like [Child Process], [Crypto], [TLS] and [N-API].

### N-API Test Suite

The most important to integrate the N-API within another VM is testing, that we called it **NTS**(N-API Test Suite). All the tests are still on the core repository, then implementor has to pull it by version like what we are doing it. The problem of this way is that we have to do the following post processing:

- analysis if some suites are dependents by `common.js` and others from core repository.
- convert those tests written in ES6 to ES5 which the VM of ShadowNode can read.

> The complete pull script is here: https://github.com/Rokid/ShadowNode/blob/master/tools/pull-napi.sh

Therefore I propose that moving the N-API tests inside this repository or another like `nodejs/napi-test-suite`, remove the Node.js dependences as possible, and publish **NTS** on NPM. 

Within this movement, implementor could install test suites via NPM only and start testing its implementation easier.

### N-API enabled runtime

Like [Node.js](https://nodejs.org) and [ShadowNode], which implemented [N-API] should be called as _N-API enabled runtimes_,  and could be documented at the README of this repository just like: _N-API enabled modules_.

With this list, module developers could see which runtimes could be working for their module without rewriting and rebuilding in the same architecture. This is why [ShadowNode] is going to support N-API, that might be useful for someone interested in maybe.

/cc @joyeecheung @legendecas @rvagg 

[nodejs/node]: https://github.com/nodejs/node
[ShadowNode]: https://github.com/Rokid/ShadowNode
[IoT.js]: https://github.com/Samsung/IoT.js
[Child Process]: https://github.com/Rokid/ShadowNode/blob/master/docs/api/Child-Process.md
[Crypto]: https://github.com/Rokid/ShadowNode/blob/master/docs/api/Crypto.md
[TLS]: https://github.com/Rokid/ShadowNode/blob/master/docs/api/TLS.md
[HTTPS]: https://github.com/Rokid/ShadowNode/blob/master/docs/api/https.md
[N-API]: https://github.com/Rokid/ShadowNode/blob/master/docs/api/N-API.md

**Comment by joyeecheung** [comment]
Great work! Looks like this project is based on a fork of JerryScript, I recall that @gabrielschulhof has been doing similar work on JerryScript as well?

Refs: https://github.com/nodejs/node/issues/20118

**Comment by gabrielschulhof** [comment]
@joyeecheung I have indeed created a partial implementation of N-API on top of JerryScript. Some N-APIs cannot be implemented because, for example, of a lack of support for symbols and some constants like `MAX_SAFE_INTEGER`.

It's good that IoT.js is a more well-rounded runtime, and, in particular, that it has support for NPM, because then factoring out the N-API test suite is indeed viable.

**Comment by gabrielschulhof** [comment]
@yorkie I have found that a lot of the N-API tests will run fine when be translated with babel. We need to qualify and elaborate on the level of N-API support, given that things like symbols will be missing in JerryScript.

I'm definitely in favour of exposing the N-API test suite as a more generic N-API compliance test suite.

**Comment by gabrielschulhof** [comment]
@yorkie BTW, I was able to build and run the N-API tests as part of the JerryScript test suite unmodified using some helper scripts:

https://github.com/gabrielschulhof/jerryscript/tree/n-api-take-2/tests/unit-ext/n-api
https://github.com/gabrielschulhof/jerryscript/blob/n-api-take-2/scripts/convert-n-api-tests.js

**Comment by yorkie** [comment]
> @yorkie I have found that a lot of the N-API tests will run fine when be translated with babel. We need to qualify and elaborate on the level of N-API support, given that things like symbols will be missing in JerryScript.

Yea, we have integrated in the similar way, and it worked as well at ShadowNode, what I really proposed is like [tc39/test262](https://github.com/tc39/test262), and downgrade to expose test suite as more compliance test suite is important, too.

**Comment by mhdawson** [comment]
Great to see N-API being implemented and useful in other runtimes/implementations.

I wonder if a first step would be some scripts which would extract the tests from the Node repo and then package them separately as requested.  We could then look at a nightly CI job that would run that adn then publish the result to into a repo like nodejs/napi-ts

**Comment by yorkie** [comment]
> I wonder if a first step would be some scripts which would extract the tests from the Node repo and then package them separately as requested.

I think [ShadowNode](https://github.com/Rokid/ShadowNode) is working in this way now :p

> We could then look at a nightly CI job that would run that adn then publish the result to into a repo like nodejs/napi-ts

@mhdawson What does the napi-ts mean?

**Comment by mhdawson** [comment]
N-API test suite

**Comment by yorkie** [comment]
@mhdawson I guess napi-ts might be confusions, I thought it's N-API TypeScript :(

**Comment by mhdawson** [comment]
then mabye nodejs/napi-test-suite

It's not all that long even spelled out.

**Comment by gabrielschulhof** [comment]
@yorkie would you like to join us for our weekly N-API meeting? We meet on [zoom](https://zoom.us/). Our conference number is 363-665-824. We could discuss the logistics of making the N-API test suite available outside the Node.js code base.

**Comment by yorkie** [comment]
Sorry @gabrielschulhof, missed your last message, when the meeting starts?

**Comment by gabrielschulhof** [comment]
@yorkie the meeting is every Thursday at 1:30 PM Eastern Time on [zoom](https://zoom.us). The conference number is 363-665-824. You can check the Node.js calendar at https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98@group.calendar.google.com&pli=1

**Comment by yorkie** [comment]
Thanks @gabrielschulhof, May I join the next N-API weekly meeting for this topic?

**Comment by gabrielschulhof** [comment]
@yorkie absolutely! You're more than welcome!

**Comment by NickNaso** [comment]
Hi everyone,
recently I found this project: https://github.com/Tencent/Hippy. It contains a reduced and different implementation of N-API see: https://github.com/Tencent/Hippy/tree/master/core/napi.

**Comment by mhdawson** [comment]
We created this repo to externalize the tests - https://github.com/nodejs/js-native-api-test. I think this issue can be closed and initiative to get that working can be handled by issues in that repo.
