### ISSUE TITLE
Need clarity on napi_is_exception_pending

### ISSUE THREAD

**Issue by varun-elear** [nodejs/abi-stable-node#335]
What are the pending exceptions here? Are these raised due to execution of code in JS layer or C layer or napi API calls or because of some failure when the JS engine was trying to perform some tasks? Could you please give an example. Also, how can I create a scenario where there is a pending exception when I return from a napi call? I want to test the code block which will get executed when there is a pending exception and also I want to understand how pending exception works.

**Comment by mhdawson** [comment]
pending Exceptions are exceptions that were thrown when running JavaScript code (or thrown in your addon).  For example, if in https://github.com/nodejs/abi-stable-node-addon-examples/blob/master/3_callbacks/napi/addon.cc on line 23, the function called threw an exception, it would be pending after the return from napi_call_function.

The unit tests also provide example of this : https://github.com/nodejs/node/blob/master/test/addons-napi/test_exception/test_exception.c

To generate a pending exception in C you could use napi_throw_error (for example in https://github.com/nodejs/node/blob/master/test/addons-napi/test_error/test_error.c line 29)

**Comment by varun-elear** [comment]
Thank you @mhdawson . I got some clarity on how this works now. Just to confirm, this means that pending exceptions can be there only when:
1. Any JS function is called from the C code (N-API layer) 
2. When error is thrown explicitly from the C code (N-API layer) 

Is my understanding correct?

I had a doubt that when we call any of the APIs that are provided by N-API and anything goes wrong in the execution of the API code, then just the napi_status is set accordingly and no exception raised? 

Also, I wanted to understand whether is it the same VM (which runs the JS code) that also runs the C code and the napi API calls? Any resource or link for understanding this will be helpful.

**Comment by digitalinfinity** [comment]
@varun-elear that's right. Put it another way, pending exceptions are exceptions in the JS engine that have yet to be handled (either by JS or native C code). If the n-api C code calls a JS function and it throws, then the engine has a pending exception that either n-api C code can clear and handle, or bubble back up the JS VM if the n-api C code was called from JS in the first place. n-api C code can also cause the JS VM to have a pending exception by explicitly throwing any exception using `napi_throw_error`.

And yes, if there is an error in the usage of the n-api API itself, generally no exception should be thrown, an status code will get returned indicating the problematic operation.

I don't understand the last question- the C code runs natively, it's not executed by a VM. However, the VM that runs JS code and the VM that n-api will talk to are the same, if that's what you're asking.

**Comment by mhdawson** [comment]
In terms of the last question, I think the answer is that both the JavaScript and C code run in the same process using the same instance of v8.  @varun-elear does that answer your question?

**Comment by varun-elear** [comment]
Thanks @digitalinfinity, it clears the concepts of pending exceptions for me. Yes @mhdawson, it does answer my question, thank you!
Also, I needed some clarity regarding some other APIs, where is the right place to discuss that - via issues on this repo, the node mailing thread or somewhere else?

**Comment by mhdawson** [comment]
@varun-elear I think issues in this repo is ok.  It helps capture what people are asking about and having it documented may help us improve the documentation.

**Comment by mhdawson** [comment]
I think this has been answered, closing.  Please re-open if that's not the case.
