### ISSUE TITLE
napi_is_function

### ISSUE THREAD

**Issue by jorangreef** [nodejs/abi-stable-node#340]
I have looked through all the documentation, but there doesn't seem to be a way to verify that a `napi_value` is a JS function, e.g. using something like `napi_is_function`?

The reason for asking, is that I need to verify all user-supplied arguments (including a JS callback) and throw an exception before queuing async work.

**Comment by jorangreef** [comment]
I just came across `napi_function` which can be used like this:

```c
napi_valuetype type;
assert(napi_typeof(env, argv[0], &type) == napi_ok);
if (type != napi_function) {}
```

**Comment by gabrielschulhof** [comment]
@jorangreef yep, that's the way to ascertain whether a `napi_value` holds one of the primitive types + `napi_external` 🙂

**Comment by ralphtheninja** [comment]
@jorangreef Check out [`napi-macros`](https://github.com/mafintosh/napi-macros/blob/master/napi-macros.h#L187-L208) module by @mafintosh. There might be some handy stuff for you in there. Also, maybe add a `NAPI_ARGV_FUNCTION()` which does this assertion?

**Comment by jorangreef** [comment]
Thanks @gabrielschulhof and @ralphtheninja
