### ISSUE TITLE
NodeConf EU 2018, N-API Workshop

### ISSUE THREAD

**Issue by jschlight** [nodejs/abi-stable-node#343]
[NodeConf EU 2018](https://www.nodeconf.eu) — November 4-7, 2018 in Kilkenny, Ireland. 
The workshop is schedule for two 1½ hour sessions on the afternoon of November 7. 
**Part 1** 14:00–15:30. **Part 2** 16:00–17:30.

Workshop slides [Getting Started with N-API and node-addon-api](https://docs.google.com/presentation/d/1nBw8QNWDzMe-8QEYSnvJDNPWYMvmbmUz-mtnGZuiWLE/edit#slide=id.p)

### Speakers

- Gabriel
- Nicola
- Michael
- Jim

### Topics for discussion

- ~Lessons from Node Summit~
- ~Other Talks Page~
- ~Contributors Page~
- ~Portion out the slides~

**Comment by mhdawson** [comment]
1) Asking @digitalinfinity to update generator to have 2 options - https://github.com/digitalinfinity/generator-napi-module/issues/5

  - simple
  - object wrap (which is what is there today)

2) Update workshop have the 2 different steps (Jim) 

3) Update list of modules people can port (Hitesh)

~4) Update contributors page (Jim~

**Comment by mhdawson** [comment]
Done, closing

**Comment by gabrielschulhof** [comment]
@jschlight do you think you could open up the Google slides doc for reading to anyone with the link?

**Comment by jschlight** [comment]
Anyone with this link should now be able to view the slides:

https://docs.google.com/presentation/d/1nBw8QNWDzMe-8QEYSnvJDNPWYMvmbmUz-mtnGZuiWLE/

**Comment by gabrielschulhof** [comment]
@jschlight thanks!
