### ISSUE TITLE
Proposal to add some labels on node-addon-api repo 

### ISSUE THREAD

**Issue by NickNaso** [nodejs/abi-stable-node#344]
Hi everyone,
I realized that in the repo of `node-addon-api` we don't have many labels to tag the issues. I think that could be a good idea add the following labels:
- doc
- test
- do-not-land
- good first issue

If you agree I can do this and if you want we can discuss the idea through this issue or directly at next meeting.

**Comment by mhdawson** [comment]
+1 from me

**Comment by NickNaso** [comment]
I'm closing the issue because I just added the labels as discussed today in the meeting.
