### ISSUE TITLE
Factor out N-API to expand embeddability use cases

### ISSUE THREAD

**Issue by digitalinfinity** [nodejs/abi-stable-node#354]
As @bghgary mentioned on the N-API WG meeting on 10/18, there is a use case where developers who are embedding JS engines directly (and not embedding Node) can need a VM-neutral interface to talk to these engines in an ABI-stable manner. Given that N-API already has this, @bghgary suggested factoring out the ES-specific parts of N-API into its own header. Opening this issue to continue that discussion.

@bghgary's prototype is here: https://github.com/bghgary/node-addon-api/tree/ES-only

**Comment by mhdawson** [comment]
I think its a great suggestion.  Making it easier for other projects/teams to consume N-API should help overall adoption.  In addition it will increase the chances of these projects contributing back enhancements.

**Comment by bghgary** [comment]
See https://github.com/nodejs/node/pull/23786

**Comment by gabrielschulhof** [comment]
Landed in https://github.com/nodejs/node/commit/596bd5f1bb64cebc8d9b72c114f78ef9f074863b.
