### ISSUE TITLE
Membership review - still active?

### ISSUE THREAD

**Issue by jschlight** [nodejs/abi-stable-node#355]
The N-API team decided to initiate a membership review during its October 4, 2018 meeting using the procedure established by the Node [Security](https://github.com/nodejs/security-wg/issues/302) and [Diagnostics](https://github.com/nodejs/diagnostics/issues/215) Working Groups. 

@aruneshchandra - Arunesh Chandra
@boingoing - Taylor Woll
@corymickelson - Cory Mickelson
@digitalinfinity - Hitesh Kanwathirtha
@gabrielschulhof - Gabriel Schulhof
@ianwjhalliday - Ian Halliday
@jasongin - Jason Ginchereau
@jschlight - Jim Schlight
@mhdawson - Michael Dawson
@NickNaso - Nicola Del Gobbo
@sampsongao - Sampson Gao
@anisha-rohra - Anisha Rohra
@kfarnung - Kyle Farnung

Please confirm by posting a comment on this issue if you plan to continue being active in the `abi-stable-node` project. If we don't hear from you we will move you to emeritus status.

**Comment by NickNaso** [comment]
Hi everyone I want continue to contribute to this project.

**Comment by mhdawson** [comment]
I'm still around and active.

**Comment by kfarnung** [comment]
I'm still around and active.

**Comment by anisha-rohra** [comment]
I would still like to contribute and be active!

**Comment by digitalinfinity** [comment]
Around + still active

**Comment by mhdawson** [comment]
@boingoing - Taylor Woll
@corymickelson - Cory Mickelson
@ianwjhalliday - Ian Halliday
@jasongin - Jason Ginchereau
@sampsongao - Sampson Gao

Second ping to see if you are still active.  If we don't hear from you, we'll move you to Emeritus.

**Comment by boingoing** [comment]
I am still around and relatively active.
