### ISSUE TITLE
Backports for tsfn

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#358]
Need to backport to 8.x and 10.x and make non experimental to help adoption.

**Comment by mhdawson** [comment]
Gabriel - already in as experimental in 10.X

Steps:

1) Make non-experimental in master
2) roll back to 10.x and 8.x

Gabriel will get the ball rolling.

**Comment by gabrielschulhof** [comment]
v10.x backport: https://github.com/nodejs/node/pull/25633
v8.x backport: https://github.com/nodejs/node/pull/25648

**Comment by mhdawson** [comment]
From the meeting today sounds like there is a problem with FreeBSD 10 in the 10.x staging and release branches.  Believe its the same problem that I refereed to in https://github.com/nodejs/node/pull/25574.

**Comment by gabrielschulhof** [comment]
The commit on v10.x-staging that seems to have introduced the failure to compile on FreeBSD 10 is this: https://github.com/nodejs/node/commit/acf7e7d282e87b4c0b5a5ab672e21c3c67311cf2

**Comment by gabrielschulhof** [comment]
These backports have now landed.
