### ISSUE TITLE
Add support for napi_create_boolean()

### ISSUE THREAD

**Issue by nkreeger** [nodejs/abi-stable-node#362]
I noticed that the N-API does not have support to create boolean types from C-code. There are methods for various integer types, floating points, and strings - but nothing for booleans. In order to surface a return value that is a true boolean it looks like I need to include something like:

```c++
Nan::New<v8::Boolean>(value);
```

I'm happy to contribute a PR - I just want to make sure there are no concerns about x-platform support (I'd think booleans are no big deal). We are heavy users of this API for [TensorFlow.js Node bindings](https://github.com/tensorflow/tfjs-node) and a  [headless WebGL project](https://github.com/google/node-gles).

**Comment by mhdawson** [comment]
I see this in: https://github.com/nodejs/node/blob/master/src/js_native_api.h

```C
NAPI_EXTERN napi_status napi_get_boolean(napi_env env,
                                         bool value,
                                         napi_value* result);
```

which is what you'd use to create a boolean with the C API.

There is also support in node-addon-api: https://github.com/nodejs/node-addon-api/blob/master/doc/boolean.md.

So I `think` its already there unless I misunderstood.

**Comment by DaAitch** [comment]
Yeah I also think it's already there. Maybe it's a bit confusing, because it's not "create boolean" but "get boolean", like with undefined, simply because in JS they are constants.

**Comment by gabrielschulhof** [comment]
@nkreeger hopefully this has addressed your issue. Please feel free to reopen otherwise.

**Comment by bpasero** [comment]
**jm2c**: took me almost half day to figure this out. How is this not documented on https://nodejs.org/api/n-api.html, at least as a hint?

In general I have to say, https://nodejs.org/api/n-api.html lacks some serious examples of the most basic things like having a method with some values passed in and a result value returned back. I have a frustrating experience migrating to N-API :-|

**Comment by mhdawson** [comment]
@bpasero have you seen the examples in nodejs/node-addon-examples?

**Comment by waruqi** [comment]
I think napi_get_boolean should be rename to `napi_create_boolean`, or add a `napi_create_boolean` macro at least.
