### ISSUE TITLE
Separate additional package on top of node-addon-api?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#363]
Do we need an additional module for extentions to node-addon-api?

For example: https://github.com/nodejs/node-addon-api/pull/377

**Comment by mhdawson** [comment]
Also https://github.com/nodejs/node-addon-api/issues/439 with part of the context.

Created this issue and added to Milestone 11 so that we review/discuss in the next N-API team meeting.

**Comment by mhdawson** [comment]
Another one that might be in helper or N-API itself: https://github.com/nodejs/node-addon-api/issues/265

**Comment by mhdawson** [comment]
From discussion 2 approaches would be:

* node-addon-api is limited to 
  * wrappers of N-API functions
  * utilities for which we can demonstrate strong benefits for being in node-addon-api versus a module
  and we encourage and support ecosystem modules as the starting

* We are relatively liberal in terms of what we take into node-addon-api.

**Comment by mhdawson** [comment]
Next steps:

- [x] @digitalinfinity will take a first cut at expanding on the 2 approaches
- [ ] document our preferred approach as PR to node-addon-api (@digitalinfinity will do that)
- [ ] get input from those who have submitted the two PRs above
- [ ] get input from other N-API users.

**Comment by digitalinfinity** [comment]
Here's a first cut on a doc that expands on the problem being covered in this issue and possible solutions: https://docs.google.com/document/d/13DqZUeLjwf09EmkRBBIJkLE2bxmqWt2zF5FoNvHbjZc/edit?usp=sharing

**Comment by mhdawson** [comment]
PR landed here: https://github.com/nodejs/node-addon-api/pull/477
