### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#364]
It might be time for a new release.  The last one was just over 3 months ago.

Some PRs/issues we might want to address first:
-[ ] https://github.com/nodejs/node-addon-api/pull/407

@nodejs/n-api  Please suggest others if you think we should address them before the next release.

**Comment by mhdawson** [comment]
Oops put this in  the wrong repo, will close and open one in node-addon-api

**Comment by addaleax** [comment]
Maybe this repository should be archived?

**Comment by mhdawson** [comment]
@addaleax we still use this repository actively.....  Just not the right place for the discussion of a release for node-addon-api.
