### ISSUE TITLE
Submissions to NodeConfEU

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#365]
NodeConfEU is the the first but we should also think about node Summit and Node+JS interactive.

Call for NodeConf EU is open https://sessionize.com/nodeconf-eu-2019 and closes 31 May 

@nodejs/n-api

**Comment by gabrielschulhof** [comment]
I'm planning on writing a talk entitled "The Life and Times of a Native Addon".

**Comment by NickNaso** [comment]
I would like talk about the possibility to write a wrapper over N-API with different programming languages, but all depends on how all my work will go forward in the next month.
What do you think about the idea?

**Comment by mhdawson** [comment]
@jschlight submitted the workshop as outlined: https://github.com/nodejs/abi-stable-node/issues/367.

**Comment by NickNaso** [comment]
Hi everyone I submitted my talk entitled **Let's Go N-API** at NodeConf EU.
Thanks all for helping me to write the proposal.

**Comment by NickNaso** [comment]
Hi everyone I'm closing this issue because now the CFP is closed.
