### ISSUE TITLE
Node.js blog post

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#366]
Hello @nodejs/n-api!

I would like to eventually publish https://github.com/gabrielschulhof/gabrielschulhof.github.com/pull/1/files on the Node.js blog. Could you please read it over and leave comments/corrections?

Thank you very much for your help!

**Comment by mhdawson** [comment]
Made a few comments but looks like a great blog post.

**Comment by mhdawson** [comment]
Blog published.
