### ISSUE TITLE
Request for modules adopting N-API - media related modules

### ISSUE THREAD

**Issue by sparkpunkd** [nodejs/abi-stable-node#368]
In this [Medium article](https://medium.com/the-node-js-collection/n-api-next-generation-apis-for-node-js-native-addons-available-across-all-lts-release-lines-4f35b781f00e) by Arunesh Chandra and Michael Dawson, a request is made to let _this repo_ know about interesting modules using N-API or that you are proud of.

We have been working with N-API for a year to develop media-processing related capabilities and had a good experience. We have developed the following modules using N-API that may be of general interest:

* [beamcoder](https://www.npmjs.com/package/beamcoder) - The Aerostat Beam Coder addon binds [FFmpeg](http://ffmpeg.org/) to Node.js, providing access to media muxing, transcoding and transformation with promises frame-by-frame. (A plug for why N-API made this possible [here](https://www.linkedin.com/pulse/introducing-aerostat-beam-coder-richard-cartwright/).)
* [naudiodon ](https://www.npmjs.com/package/naudiodon)- Addon wrapper for [PortAudio](http://www.portaudio.com/) to allow access audio devices from Node.js.
* [nodencl ](https://www.npmjs.com/package/nodencl) - Experimental addon providing [OpenCL](https://www.khronos.org/opencl/)-based access to GPU-processing capabilities from Node.js.
* [macadam](https://www.npmjs.com/package/macadam) - Addon to control and access data to/from [Blackmagic](https://www.blackmagicdesign.com/) playback and capture devices.

We have other N-API-based modules in development. Please let me know if you would like further information and apologies if this was the incorrect approach to notifying you of these packages. The _issue_ here is that N-API is a real enabler!

**Comment by mhdawson** [comment]
Thanks for posting.  It's great to have this info and please add the other modules once you complete them.

**Comment by sparkpunkd** [comment]
We will keep you up to date! Thanks.
