### ISSUE TITLE
Napi version in node-gyp

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#371]
For discussion in next meeting:

https://github.com/nodejs/node-gyp/issues/1745

**Comment by jschlight** [comment]
With `node-pre-gyp` and `prebuild`, the N-API version is essentially specified by the user and then the actual N-API version being built against is communicated into the `binding.gyp` file using a new `napi-build-version` variable we created for the purpose. 

In the linked issue, the user is requesting that `node-gyp` inform the `binding.gyp` file which N-API version is supported by the version of Node being built against. 

It's like the opposite of what we implemented for `node-pre-gyp` and `prebuild`.

**Comment by richardlau** [comment]
A PR was opened against core: https://github.com/nodejs/node/pull/27800

**Comment by NickNaso** [comment]
Hi everyone,
I closed my previous PR and reopened new one  https://github.com/nodejs/node/pull/27835. Please if you have time take a look.

**Comment by NickNaso** [comment]
Hi everyone,
if someone has time could take a look at this PR https://github.com/nodejs/node/pull/27835 in particular the last two comments? I need a feedback.

**Comment by NickNaso** [comment]
I’m closing this because the PR has been landed yesterday and the work now is on Node.js 12.6.0
