### ISSUE TITLE
Submissions to Node+JS Interactive - June 21st.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#372]
Deadline ~June 14~ extended to June 21.

@jschlight volunteered to summit the workshop and put together a abstract for the birds of a feather.

**Comment by NickNaso** [comment]
Hi everyone I submitted my talk entitled **Let's Go N-API** at Node+JS Interactive.
Thanks all for helping me to write the proposal

**Comment by jschlight** [comment]
## Birds of a Feather Proposed Abstract

The world of Node native add-ons is rapidly evolving with the widespread adoption of N-API. Improvements implemented over the past year now make native add-ons nearly on par with those written in JavaScript. At this birds of a feather, you’ll meet members of the Node team advancing this important technology along with other native add-on developers. You’re invited to come join us to learn about important new developments including asynchronous operations, context awareness, and thread-safe functions. Whether you’re a seasoned native add-on developer or are interested in starting your own new project, this is the perfect place to get your questions answered by the native add-ons experts and fellow developers.

**Comment by jschlight** [comment]
I've submitted both the workshop and the birds of a feather. Reviews will begin shortly and final notifications will be sent on Wednesday, July 31.

**Comment by mhdawson** [comment]
I think we can close this now. Please re-open if you think that's incorrect.
