### ISSUE TITLE
Interlock with WASM/WASI team

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#376]
I've been talking with the WASM team to set up an interlock so we can discuss the overlap or synergy between WASM/WASI and N-API.

Current target is to have some of the WASM team come to the meeting the ~~first week of July~~ second week of July as their team is very busy between now and then.

I've send out an invite and will update when its confirmed.

**Comment by mhdawson** [comment]
Changed to second week of July as Monday of the first week is a Holiday in Canada.

**Comment by mhdawson** [comment]
Should have posted here that it's happening today 3 EST

The regular N-API team zoom

https://zoom.us/j/363665824

Sorry, should have updated earlier but forgot to do that when it got moved up.

**Comment by cjihrig** [comment]
I think the N-API meeting conflicted with the Modules team meeting and Zoom kicked us out.

**Comment by mhdawson** [comment]
Yup we had to use alternate zoom links and unfortunately, I did not get a recording.  It was a good meeting thought.

Next step is to review the impl that Ohad is work on with @ofrobots once its available.
