### ISSUE TITLE
Building addons with cmake

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#381]
See: https://github.com/nodejs/node-addon-api/issues/445

Creating issue so we make sure to discuss, ideally when we have @jschlight in the meeting.

**Comment by mhdawson** [comment]
Nicola, we should look at existing solutions like `cmake-js` and see if they need any updates to support node-addon-api.

Jim, the work he did for pre-build was for cmake-js.

Nicola, maybe we can move some of what Jim did for pre-build to cmake-js so that all dependencies can leverage that.

Jim, cmake-js is pretty generic, did not have to do much, only document what you needed there.

Nicola then it might just be a matter of documentation.

Jim will:

* review issue and let us know what he thinks we we should do
* add links to the doc he created to nodejs/node-addon-api#445

**Comment by gengjiawen** [comment]
`node-gyp` already support generate cmake config. I have used it in Clion, works pretty well (code autocomplete and debug).

**Comment by jschlight** [comment]
I've added a comment here about building N-API addons using CMake.js: https://github.com/nodejs/node-addon-api/issues/445#issuecomment-536057129

**Comment by jschlight** [comment]
During today's call we discussed the behavior of CMake.js when the underlying CMake executable is not installed. Here's what I found:

```
spare:~ jim$ npm install -g cmake-js
/Users/jim/.nvm/versions/node/v10.16.3/bin/cmake-js -> /Users/jim/.nvm/versions/node/v10.16.3/lib/node_modules/cmake-js/bin/cmake-js
+ cmake-js@6.0.0
added 140 packages from 108 contributors in 8.486s
spare:~ jim$ cmake
-bash: cmake: command not found
spare:~ jim$ cmake-js
[ '/Users/jim/.nvm/versions/node/v10.16.3/bin/node',
  '/Users/jim/.nvm/versions/node/v10.16.3/bin/cmake-js' ]
info TOOL Using Unix Makefiles generator.
ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
spare:~ jim$ 
```

CMake.js displays a message instructing the user to install the CMake executable if it is not found.

**Comment by mhdawson** [comment]
@jschlight thanks for checking that out. Great to see that it shows a good message.

**Comment by jschlight** [comment]
The PR merge should have closed this issue? But maybe the automatic close does not work between repos?
