### ISSUE TITLE
Consider adding to core documentation node-gyp, cmake, prebuild etc.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#384]
There have been some question about cmake, we've done work around prebuild Should there be a section in the core documentation?

**Comment by mhdawson** [comment]
Jim will take a first cut.

**Comment by mhdawson** [comment]
Possible location: https://nodejs.org/dist/latest-v12.x/docs/api/addons.html#addons_building

**Comment by mhdawson** [comment]
Some additional info in https://github.com/nodejs/abi-stable-node/issues/386

**Comment by jschlight** [comment]
It appears that the `Building` section on the proposed page is part of a "Hello world" tutorial.

https://nodejs.org/dist/latest-v12.x/docs/api/addons.html#addons_building

- Does it make sense to add a new `Building` section on this page instead?

   https://nodejs.org/api/n-api.html

   It could go after the `Usage` section.

My plan is to create documentation at a fairly high-level, pretty much describing the available tools and when you'd want to use them. But then linking off to the various tools for the specifics.

- Does the Node.js Foundation have policies on documentation in general and linking to other sites in particular?

**Comment by mhdawson** [comment]
I'm not sure on the policy for linking out to other sites.  I think adding to https://nodejs.org/api/n-api.html to start does make sense.
