### ISSUE TITLE
Add to Node Core documention

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#386]
Add to core documentation which covers 2 options for building your packages
  - gyp 
  - cmake

Add to https://nodejs.org/dist/latest-v12.x/docs/api/addons.html#addons_building

Also talk about prebuild etc.?

**Comment by mhdawson** [comment]
Duplicate of https://github.com/nodejs/abi-stable-node/issues/384

**Comment by jschlight** [comment]
It looks like the `Building` section on the proposed [C++ Addons documentation page](https://nodejs.org/dist/latest-v12.x/docs/api/addons.html) is part of a "Hello world" tutorial.  

- Would it be better to create a new `Building` section on this page? 

   https://nodejs.org/dist/latest-v12.x/docs/api/n-api.html 

   It could go after `Usage`.

- Are there documentation guidelines for these pages? For example, linking to sites not maintained by the Node.js Foundation? 

   I'm thinking this section should be at a "high-level" with links to the specific tools for the details.
