### ISSUE TITLE
N-API 6

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#393]
The only outstanding backport for new N-APIs is https://github.com/nodejs/node/pull/31384 which brings `napi_get_all_property_names` to v10.x. Shall we wait until it lands to make off N-API 6 as including `napi_get_all_property_names`, or shall we leave `napi_get_all_property_names` experimental and roll N-API 6 without it?

Once we have arrived at a decision, we need to file a PR in core that bumps the `NAPI_VERSION` and updates the preprocessor if-block into which the N-API declarations are placed.

**Comment by legendecas** [comment]
Since https://github.com/nodejs/node/pull/31384 has landed on v10.x-staging as https://github.com/nodejs/node/pull/31384#issuecomment-593361988, I'd believe we're going to roll N-API 6 with `napi_get_all_property_names` if there are no other issues arisen.

**Comment by mhdawson** [comment]
@gabrielschulhof looks like we are ready to go

**Comment by gabrielschulhof** [comment]
Excellent!
