### ISSUE TITLE
NodeConf.EU workshop proposal

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#399]
NodeConf.EU is online-only this year.

NodeConf Remote will take place from 2nd – 6th November 2020. (Monday-Friday)

CFP closes July 27th.

[Main conference page](https://www.nodeconf.eu)

### Workshop details

We can request either a 1½ or 3 hour session.

The workshop can have one main speaker and up to three co-speakers.

The workshop will be offered during daytime hours in Dublin which is Irish Standard Time (IST).

For those in North America, Daylight Saving Time ends on November 1, 2020 which is the day before the conference begins. During the week of the conference, Dublin will be 5 hours ahead of the Eastern Time Zone and 8 hours ahead of the Pacific Time Zone. 

### Conducting the workshop online

The slides we've been using are available [here](https://docs.google.com/presentation/d/1kGzkj_4RqoE4YJ4I4XPdMLPcaiCHiJqLVL0nRBSUPhQ/edit#slide=id.g6bf08a015e_2_10). 
Video of the 2019 workshop at Node+JS Interactive is [here](https://www.youtube.com/watch?v=-v4Q0y4CeRA&list=PLfMzBWSH11xZPfWcC0DqFqKo_reMP58mw&index=45&t=0s).

Historically, members of the team have introduced the workshop by going through the slide deck in sections. At the conclusion of the introduction, participants are then free to work through the tutorial material or on a project they've brought to work on. The N-API team members conducting the workshop are then available for on-on-one consultation with workshop participants. 

We need to give some thought to how this approach will work in an online setting and the technical tools we'll need to accomplish it.

**Comment by jschlight** [comment]
### Proposed Workshop Description

Harness the power of Node.js native addons by utilizing technology built into Node.js to combine the performance of C and C++ with the agility of JavaScript. In this workshop you’ll learn how to create a native addon that gives you access to existing C/C++ libraries or previously unavailable operating system capabilities.

This workshop, offered by experts from the N-API team, describes important new features essential to the performance of your native add-on. These new features include asynchronous operations which permit you to safely and reliably spread your work across multiple threads. Context awareness permits your add-on to be loaded multiple times without the multiple copies interfering with each other. Finally, adopting thread-safe functions insures your functions run reliably regardless of the thread from which they are called or in which they run.

Whether you are just starting out with native add-ons or are an old pro looking for an update on N-API, bring your project or work through the workshop tutorials under the helpful guidance of the N-API experts. You’ll leave this workshop with a solid understanding of these important new technologies and how they apply to your own projects. And perhaps, with a bit of luck, working code!

> The first paragraph was updated 2020-07-10

**Comment by NickNaso** [comment]
I'm posting the link for the slides used in the last workshop:
https://docs.google.com/presentation/d/1kGzkj_4RqoE4YJ4I4XPdMLPcaiCHiJqLVL0nRBSUPhQ/edit?usp=sharing

**Comment by mhdawson** [comment]
Proposal submitted, just waiting to hear from the organizers one way or the other.

**Comment by jasnell** [comment]
We will be making final selections on workshops soon

**Comment by jschlight** [comment]
I've received this note from NodeConf Remote letting us know our workshop proposal was not accepted.

> Hello Jim Schlight,

> Thank you for submitting a talk proposal for this year's NodeConf.eu/NodeConf.remote. We had an amazing response with far too many amazing proposals but only 20 speaking slots to fill. As such, it was extremely difficult for us to narrow down the selections! We're really sorry, but the following sessions have not been accepted for NodeConf Remote: 
> - Access the power of C/C++ libraries from JavaScript

> Thanks, 
> NodeConf Remote
