### ISSUE TITLE
WIP: Common module registration for all versions of node

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#4]
Not sure if I'm on the right track, but here's some code that will call a module's init on all versions of node from 0.10 to 4.5.0 (at least). I haven't yet dealt with passing the arguments that Init receives in a node-agnostic fashion, but hence the WIP :)

``` C++
#include <stdio.h>

void Init() {
    printf("Init\n");
}

struct old_module {
    int version;
    void *aPointer;
    const char *filename;
    void (*entry_point)(void);
    const char *module_name;
};

struct new_module {
    int version;
    int something;
    void *aPointer;
    const char *filename;
    void (*entry_point)(void);
    void *anotherPointer;
    const char *module_name;
    void *yetAnotherPointer;
    void *andAnotherPointer;
};

// 0.10
extern "C" {
    __attribute__((visibility("default")))
    struct old_module hello_module = {
        .version = 11,
        .aPointer = __null,
        .filename = "../hello.cc",
        .entry_point = Init,
        .module_name = "hello"
    };
}

// 0.12
extern "C" {
    static struct new_module _module = {
        .version = 14 /* 46 for 4.0.0 */,
        .something = 0,
        .aPointer = __null,
        .filename = "../hello.cc",
        .entry_point = Init,
        .anotherPointer = __null,
        .module_name = "hello",
        .yetAnotherPointer = __null,
        .andAnotherPointer = __null
    };
    void node_module_register(void *module) __attribute__((weak));
    unsigned int uv_version(void) __attribute((weak));
    static void _register_hello(void) __attribute__((constructor));
    static void _register_hello(void) {
        if (node_module_register) {
            if ((uv_version ? uv_version() : 0) >= 0x10703) {
                _module.version = 46;
            }
            node_module_register(&_module);
        }
    }
}
```

**Comment by gabrielschulhof** [comment]
[gist](https://gist.github.com/gabrielschulhof/e4d2bed23cf035548718fe4b6abbd032)-ed it so I can move it forward.

**Comment by gabrielschulhof** [comment]
I guess there'll be buy-in from node which takes care of Init ...

**Comment by gabrielschulhof** [comment]
Observations:

  * In 0.10 we have to add ```node::addon_abi_register_func``` to the end of ```node_module_struct``` to maintain binary compatibility (branch api-prototype-0.10.40)

  * On master, I'm not sure how we can maintain binary compatibility since the ```node_module``` structure ends in a link to another module. I suppose we could just tack the function to the end just like in 0.10, but it's kinda weird if the link is not the last member.

**Comment by mhdawson** [comment]
@sampsongao I know you were going to look at this as well.

**Comment by sampsongao** [comment]
Yes, but after some discussion in today meeting, we think node-0.12 might be a easier to achieve the goal. So I plan to port node-0.12 next week and then try again.

**Comment by jasongin** [comment]
Closing because this is obsolete.
