### ISSUE TITLE
N-API 7

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#402]
Might it be time for a new version of N-API?

We have the buffer detaching stuff marked as experimental in all three LTS releases, so we could just define these APIs as N-API 7.

We also have type-tagging and asynchronous env cleanup coming on master, but those still need to be backported. As v10.x approaches EOL it is increasingly unlikely that they will be backported all the way there. Thus, it might make sense to sync our N-API version bump with the EOL of 10.x.

Shall we formalize and document our policy for moving APIs out of experimental and into a stable version of N-API?

**Comment by mhdawson** [comment]
We agreed:
*  that we should make buffer detaching stable in N-API 7
* that type-tagging and async env cleanp should wait until N-API 8, possibly around the Node.js 16.x release timeline.

**Comment by gabrielschulhof** [comment]
@Flarna asked that https://github.com/nodejs/node/pull/35214 be folded into N-API 7 because it's such a small change. Let's discuss at our next meeting.

**Comment by mhdawson** [comment]
All ready to go, just waiting next 10.x release and then we can close this.

**Comment by mhdawson** [comment]
Landed in 10.x, done !
