### ISSUE TITLE
Blog post to discuss last few years of N-API

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#405]
We've made

Mention, weekly downloads, summary of current status

- Quote from each team members

**Comment by mhdawson** [comment]
@NickNaso will add a google doc that we can write the post in.

**Comment by NickNaso** [comment]
Here the link for the doc https://docs.google.com/document/d/1zZsbzeiHt7wG5FAjKOmrfp859EzWFuQCNXT_IhWMvBE

**Comment by mhdawson** [comment]
Thanks we missed talking about it in the meeting today, we can brainstorm next week or review content if people have already added.

**Comment by gabrielschulhof** [comment]
Landed in https://nodejs.medium.com/building-modern-native-add-ons-for-node-js-in-2020-cd3992c68e0 😉
