### ISSUE TITLE
Tracking for N-API PRs needing backport

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#406]
| status | PR | description/branch | backports |
|---|---|---|:---:|
| **complete** |  |  |  |
|  | https://github.com/nodejs/node/pull/37652 | **Node-API 8** |  |
|  |  | master | https://github.com/nodejs/node/commit/d15475578abfcc7e0a420719b8d55a6b3ab4f198 |
|  |  | v14.x |  |
|  |  | v12.x | https://github.com/nodejs/node/commit/93dd799a864c420c1ce1f9d1bac2ccde7c5ede1d |
|  |  | v10.x | not planned |
|  | https://github.com/nodejs/node/pull/37195 | **add-on file name** |  |
|  |  | master | https://github.com/nodejs/node/commit/ad3ebed046ef457530b046f2a62313a7e16b7e29 |
|  |  | v14.x | https://github.com/nodejs/node/pull/37327 |
|  |  | v12.x | https://github.com/nodejs/node/commit/f5692093d3aab880afd2fe8c994ebdec0dedcae6 |
|  |  | v10.x | not planned |
|  |  |  |  |
|  | https://github.com/nodejs/node/pull/35359 | **freeze/seal** |  |
|  |  | master | https://github.com/nodejs/node/commit/19f14517c7637b0e277b4fc3fdfe4473e5cc1262 |
|  |  | v14.14.0 | https://github.com/nodejs/node/commit/c995242068f364292bf90c6f5a5fa6bda662896d |
|  |  | v12.20.0 | https://github.com/nodejs/node/commit/5faaa603d84af583ddd3c68d64183e9531008b84 |
|  |  | v10.x | not planned |
|  | https://github.com/nodejs/node/pull/35266 | **napi_build_version** |
|  |  | master | https://github.com/nodejs/node/commit/9868126546b93ed992cff094e1884af3a88460a3 |
|  |  | v14.0.0 | -"- |
|  |  | v12.6.0 | -"- |
|  |  | v10.23.0 | https://github.com/nodejs/node/commit/b83f9a56fc3e3b507dee17c00958c001b6f427f1 |
|  | https://github.com/nodejs/node/pull/35214 | **more property defaults** |  |
|  |  | master | https://github.com/nodejs/node/commit/c9506a8f3e9bc5c679151feb39198023154464ab |
|  |  | v14.12.0 | https://github.com/nodejs/node/commit/7f3b2b2a1f2b2fa25adf9c4ea261f2a99ddd74aa |
|  |  | v12.20.0 | https://github.com/nodejs/node/commit/d938e8508ba86ad40183366d4e600feee9c584f9 |
|  |  | v10.x | not planned |
|  | https://github.com/nodejs/node/pull/28237 | **type tagging** |  |
|  |  | master | https://github.com/nodejs/node/commit/cc7ec889e863433c248bc4b5c8e33f61ccc40f29 |
|  |  | v14.8.0 | https://github.com/nodejs/node/commit/8cc9e5eb52dbbff49a594c2c8c07032d0b8f6d98 |
|  |  | v12.9.0 | https://github.com/nodejs/node/commit/e7486d4df6aeb7252bc6ae09d3cced9d4adfa076 |
|  |  | v10.x | not planned |
|  | https://github.com/nodejs/node/pull/34819 | **async cleanup hooks** |  |
|  |  | master | https://github.com/nodejs/node/commit/0848f56cb39432090cdb99af9b8541fbc1a2849c |
|  |  | v14.10.0 | https://github.com/nodejs/node/commit/3c32fe09e9354479a2527bdd7484d6efab39f864 |
|  |  | v12.9.0 | https://github.com/nodejs/node/commit/a5aa3ddacf7470b10a7be8221d3d52d52d927b99 |
|  |  | v10.x | not planned |
|  | https://github.com/nodejs/node/pull/35199 | **Node-API 7** |  |
|  |  | master | https://github.com/nodejs/node/commit/31b3202d5902e7fa105949758677ea09643d8c5f |
|  |  | v14.12.0 | https://github.com/nodejs/node/commit/ca1181615e961ec948587aa6f8b7e46efd7cbd71 |
|  |  | v12.19.0 | https://github.com/nodejs/node/commit/b9d0f73c7c6644d9f88fdfefcbcf2fb56c3bc3f5 |
|  |  | v10.23.0 | https://github.com/nodejs/node/commit/54c2bc2e621fd9cde22ea65bda7f652a63b40340 |
|  | https://github.com/nodejs/node/pull/34045 | **wasm version** |  |
|  |  | master | https://github.com/nodejs/node/commit/b327d335ff6bc48c3c2aaedccfa9c40522f6b32f |
|  |  | v14.5.0 | https://github.com/nodejs/node/commit/ac41bf03fa6b8f1d78d8ec150481553d765ac290 |
|  |  | v12.18.3 | https://github.com/nodejs/node/commit/c0d6ff592ba51f82b7768755600804bffe97da26 |
|  |  | v10.x | not planned |
|  | https://github.com/nodejs/node/pull/33597 | **wasm guards** |  |
|  |  | master | https://github.com/nodejs/node/commit/b4ede54a7d235cfe58265b2b8c455298698460a8 |
|  |  | v14.5.0 | https://github.com/nodejs/node/commit/9148e01e7612f886a6fe6563e1ad7bb20e7beac1 |
|  |  | v12.18.3 | https://github.com/nodejs/node/commit/0a949c3f93dd2567951dff5aee9f844927f3956e |
|  |  | v10.x | not planned |

**Comment by legendecas** [comment]
Should we close this as it's all complete and create an issue for each new node-api version?

**Comment by mhdawson** [comment]
+1 makes sense to me.
