### ISSUE TITLE
Tracking issue for modules we've noticed are ported to Oct 2020 - Oct 2021

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#414]

**Comment by NickNaso** [comment]
I want to report this project **[napi-nim](https://github.com/andi23rosca/napi-nim)** that allows to write NodeJS native extensions in Nim.

**Comment by NickNaso** [comment]
I want o report this project **[napi-cs](https://github.com/EYHN/napi-cs)** an experimental tool chain for build NodeJS modules with .NET 6.0 and C#.

**Comment by NickNaso** [comment]
I want o report this project [zig-nodejs-example](https://github.com/staltz/zig-nodejs-example) an example on how to build NodeJS modules with Zig.

**Comment by mhdawson** [comment]
1302 dependents 4 Feb 2022

**Comment by vweevers** [comment]
Updated: https://github.com/vweevers/about-native-addons/blob/main/data.md

**Comment by mhdawson** [comment]
@vweevers thanks for that data, very interesting.  

What does the number under `Preb.` mean. The number of pre-built binaries that are provided?

**Comment by vweevers** [comment]
> The number of pre-built binaries that are provided?

Aye

**Comment by NickNaso** [comment]
[Bun](https://github.com/Jarred-Sumner/bun)  JavaScript runtime that uses JavaScriptCore as JavaScript engine implements Node-API functions (about 90%).

**Comment by NickNaso** [comment]
There is a PR to add Node-API in Deno https://github.com/denoland/deno/pull/13633

**Comment by NickNaso** [comment]
**[Veil](https://github.com/lightsourceengine/veil)** https://github.com/lightsourceengine/veil is a NodeJS-like runtime for running JS apps on a wide range of hardware. It implements Node-API see: https://github.com/lightsourceengine/veil/tree/main/src/napi

**Comment by NickNaso** [comment]
Deno v1.26.1 added Node-API https://github.com/denoland/deno/releases/tag/v1.26.1

**Comment by mhdawson** [comment]
Closing since it's no longer 2021
