### ISSUE TITLE
Rename primary branch to main 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#421]
Github tooling is in place to do this. Unless there are objections I'll go ahead and do it.

Once we do that we should also do for node-addon-api

**Comment by mhdawson** [comment]
Discussed in meeting, turns out we don't even have a master branch in abi-stable-node, so we are good!

In terms of node-addon-api a few things we will also need to change

1) Jenkins job, default branch to test - https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/
2) Github actions for the linter - https://github.com/nodejs/node-addon-api/blob/master/.github/workflows/linter.yml
3) Heads up on readme (in process of updating docs)
4) Fix up docs - Jim will do that.

We should then look at examples repo...

**Comment by jschlight** [comment]
This is just a note to document a change that should be made at some time in the future. The `node-addon-api` `README.md` file has number of links to the `master` branch on `node-addon-examples`. IIUC, GitHub will "fixup" these links for us. But we may want to go back at some point and update these links after `node-addon-examples` has adopted the default `main` branch.

**Comment by mhdawson** [comment]
- [X] Jenkins job, default branch to test - https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/
- [x] Github actions for the linter - https://github.com/nodejs/node-addon-api/blob/master/.github/workflows/linter.yml
- [x] Heads up on readme (in process of updating docs)
- [X]  Fix up docs - Jim will do that.

**Comment by mhdawson** [comment]
Will leave open for a few days to see if we run into any issues.

**Comment by mhdawson** [comment]
@jschlight in terms of the references to node-addon-examples somebody mentioned today in another call that we can update to refer to HEAD instead of main and that will work both before/after the rename.  If that works we don't have to wait to do the updates in node-addon-api

**Comment by jschlight** [comment]
Excellent! I've created a PR that implements this. https://github.com/nodejs/node-addon-api/pull/898

**Comment by mhdawson** [comment]
node-addon-api is done.  The remaining repos include:

- [ ] node-addon-examples
  - [ ] github yaml for website - https://github.com/nodejs/node-addon-examples/blob/master/.github/workflows/website.yml
  - [ ] 6 doc links

@jschlight will take a look and update.

**Comment by mhdawson** [comment]
We believe this is done, closing.
