### ISSUE TITLE
Blog post about transition to Node-API

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#426]
Short article on Node.js medium

**Comment by gabrielschulhof** [comment]
@NickNaso will send out a link to team members for us to brainstorm on the content.

**Comment by mhdawson** [comment]
Here is the doc from @NickNaso https://docs.google.com/document/d/1leEUX_yasYlGJ8XxClfZqgpLwGUu_9Ortzphr2zn7sY/edit

**Comment by mhdawson** [comment]
@NickNaso sent email to Foundation staff, planned to be published next Monday.

**Comment by mhdawson** [comment]
Blog post published here: https://nodejs.medium.com/renaming-n-api-to-node-api-27aa8ca30ed8

closing.
