### ISSUE TITLE
Ask for review of node-serialport Node-API port - https://github.com/serialport/node-serialport/pull/2305/files

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#430]
In https://github.com/serialport/node-serialport/issues/1186#issuecomment-894448550 the OP asked if any of the Node-API team would be able to take a look at:

https://github.com/serialport/node-serialport/pull/2305/files

**Comment by mhdawson** [comment]
@NickNaso and @KevinEady have started to review, Thanks !

**Comment by gabrielschulhof** [comment]
The PR was merged and released as 10.0.0 under the beta flag.
