### ISSUE TITLE
Node-API v9

### ISSUE THREAD

**Issue by NickNaso** [nodejs/abi-stable-node#436]
Might it be time for a new version of Node-API?

We added the following new features:

- node_api_symbol_for (https://github.com/nodejs/node/blob/master/src/js_native_api.h#L96)
- node_api_create_syntax_error (https://github.com/nodejs/node/blob/master/src/js_native_api.h#L120)
- node_api_throw_syntax_error (https://github.com/nodejs/node/blob/master/src/js_native_api.h#L377)
- node_api_get_module_file_name (https://github.com/nodejs/node/blob/master/src/node_api.h#L276)
- runtime versioning (https://github.com/nodejs/node/pull/45715)
    - without actual napi_ref behavior change.

**Comment by mhdawson** [comment]
+1 from me

**Comment by mhdawson** [comment]
Discussed in the node-api team meeting this week. Lets think about it this week and the decide in the next meeting.

**Comment by gabrielschulhof** [comment]
I think we should wait for https://github.com/nodejs/node/pull/45715 as well.

**Comment by mhdawson** [comment]
We did forget this for a while, I think doing a new Node-API version would be good. We missed the lauch of Node.js 20 but I think we can get it in before it goes LTS.

**Comment by vmoroz** [comment]
Should we also put there the new finalizer behavior? Or they must be part of v10 as it is a quite big behavioral change?

**Comment by mhdawson** [comment]
We discussed today to do Release 9 with just

- node_api_symbol_for (https://github.com/nodejs/node/blob/master/src/js_native_api.h#L96)
- node_api_create_syntax_error (https://github.com/nodejs/node/blob/master/src/js_native_api.h#L120)
- node_api_throw_syntax_error (https://github.com/nodejs/node/blob/master/src/js_native_api.h#L377)
- node_api_get_module_file_name (https://github.com/nodejs/node/blob/master/src/node_api.h#L276)

along with https://github.com/nodejs/node/pull/45715 and release those along with 45715 but modifying this line to guard with experimental -   if (env->module_api_version <= 8) , as well as the documentation that says at what point the new functionality takes place, was well as the tests.

@vmoroz will submit a PR to makes those changes
@legendecas will do the the release.  As part of that he will add to https://github.com/nodejs/node/issues/47664

**Comment by gabrielschulhof** [comment]
We have released Node-API version 9. Closing.
