### ISSUE TITLE
Better coverage of node-api in Youtube

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#437]
It was mentioned that a search on youtube shows videos which are still mostly non node-addon-api. We should work to improve that.

**Comment by mhdawson** [comment]
@nodejs/addon-api if you have thoughts on what videos would make sense to create or existing content that we should promote.

**Comment by mhdawson** [comment]
1 to promote - https://www.youtube.com/watch?v=4cCSPw-I0GE

**Comment by mhdawson** [comment]
Suggestion, walk through the existing examples in the examples repo in a video

**Comment by mhdawson** [comment]
Another suggestion projections into other languages

**Comment by KevinEady** [comment]
We discussed in the 24 June 2022 Node API meeting, that it would be beneficial to find some vloggers that are interested in developing addons using Node-API in order to promote the API usage. If there are people that have videos / other promotions using NAN or V8 APIs directly, we can contact them to see if they are interested in doing a similar one in Node-API.

**Comment by mhdawson** [comment]
We discussed in the meeting this week and opened, https://github.com/nodejs/social-team/issues/7

@NickNaso has volunteered to start working on some videos so we wanted to agree on where best to post them.

**Comment by mhdawson** [comment]
* Some ideas for video:
  * What is Node-API, what are Node addons?
  * Getting started with Node-API (simple hello world example)
  * Node-API, node-addon-api under the hood
  * Follows ons for any of the example in node-addon-examples repo
  * Contributing/tests effort
* Find some existing videos
 * build page in abi stable node repo. 
* put links those on page somewhere?  Add link to Node.js API core documentation?

**Comment by KevinEady** [comment]
- Additional ideas for videos:
    - Explain how to perform debugging of native modules and JavaScript code (simultaneously?)

**Comment by mhdawson** [comment]
From discussion in the meeting today, it would be good to add to this issue links to some existing presentations. Some include:

https://www.youtube.com/watch?v=-Oniup60Afs
https://www.youtube.com/watch?v=BrJcsYjp8Nw
https://www.youtube.com/watch?v=-v4Q0y4CeRA
https://www.youtube.com/watch?v=4cCSPw-I0GE
https://www.youtube.com/watch?v=UtWP2iR3_DQ
https://www.youtube.com/watch?v=E848bgHfoxE

**Comment by KevinEady** [comment]
We discussed in the 11 Nov Node API meeting of "where do we put links to videos". 

We believe the best approach would be something similar to what we plan for the Node bindings list, where we:
1. create new page in abi-stable-node repo which lists the videos
2. PR in a link to that page in the Node.js core API documentation

**Comment by mhdawson** [comment]
Kevin volunteered to `create new page in abi-stable-node repo which lists the videos`

**Comment by KevinEady** [comment]
Created PR in core to add link to Node-API main documentation: https://github.com/nodejs/node/pull/46189

**Comment by mhdawson** [comment]
We agreed to close based on the pages being set up. We should still remember that there is more video content we could create.

**Comment by kraenhansen** [comment]
@mhdawson I found it curious that the most recent videos was not added to [the "Working Group - Node-API" playlist](https://www.youtube.com/playlist?list=PLfMzBWSH11xb8_DRfdB3yiB4g7MPzGA_l) 🤔 That might make it easier for discoverability / filtering for folks just interested in Node-API.
