### ISSUE TITLE
Document how to check for memory leaks in addon/default leak.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#440]
Add to Node.js api docs 

1) info on checking addons for memory leaks
2) that by default you will see one leak as outlined in - https://github.com/nodejs/node/issues/44518

**Comment by mhdawson** [comment]
@KevinEady is going to take a look at this one.

Suggestion is to add to doc in node-addon-api repo

**Comment by KevinEady** [comment]
I've been working on this, but what I have runs more like a blog-post than a documentation guide. PTAL and add comments as necessary: [Checking Node Add-ons for Memory Leaks using Valgrind](https://docs.google.com/document/d/1gw9NdIpp4CtVyLC9lsWOxGH9De5WVNgfu2dm2QrjaXQ/edit#). 

Would this be okay as a format for the node-addon-api doc?

**Comment by KevinEady** [comment]
PR created https://github.com/nodejs/node/pull/47760

**Comment by mhdawson** [comment]
PR landed, done
