### ISSUE TITLE
Get contacts for each of the runtimes supporting Node-API

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#445]
See if we can get a contact and possibly create a team or easy way to mention the group on issues.

**Comment by legendecas** [comment]
We can set up one (or two) of the following methods to invite runtime authors:

1. [x] GitHub team: easy to get notified in issues and PRs.
    1. However, adding a person to a GitHub team requires granting an org membership to the person.
3. [ ] Google groups: easy to join, no additional invitation.
4. [ ] OpenJS Slack channel
    1. requires people to create an account in OpenJS slack org.


Update: Option 1 is done.

**Comment by legendecas** [comment]
Invitation sent to @toyobayashi to the @nodejs/node-api-implementer teams.

**Comment by legendecas** [comment]
Confirmed with @littledivy and @bartlomieju and invitations sent.

**Comment by vmoroz** [comment]
@Jarred-Sumner, do you want to be added to this list?

**Comment by Jarred-Sumner** [comment]
Yes please

**Comment by ritikbanger** [comment]
I would also like to contribute in this, it would be great if you add me to the team too.

@legendecas @vmoroz

**Comment by mhdawson** [comment]
@ritikbanger you and others on the list are also welcome to come to the team's weekly meeting which is on Fridays at 11 ET.  The info is in the node.js calendar nodejs.org/calendar including the zoom link you can use to join.

**Comment by mhdawson** [comment]
Discussed in the meeting today, agreed that final step would be to create a document that explains how to join the team and then we can close as having pulled in as many runtimes as we can for now.
