### ISSUE TITLE
What's new in the Node-API and node-addon-api world? - 2023 version

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#446]
We use this issue to track/announce what is new on the Node-API front. 

We'll discuss at the start of Node-API meetings and capture what's new.

Also feel free to post news that you have so that we can share with the broader community.

**Comment by mhdawson** [comment]
New node-addon-api version (5.1.0) published by @NickNaso - https://github.com/nodejs/node-addon-api/blob/main/CHANGELOG.md#2023-01-13-version-510-nicknaso

**Comment by mhdawson** [comment]
[Node-API](https://nodejs.org/docs/latest/api/n-api.html) implementation for [Emscripten](https://emscripten.org/index.html) - and PR in node-addon-api to conditionally make TSFN available on Emscripten-> https://github.com/nodejs/node-addon-api/pull/1283

**Comment by mhdawson** [comment]
And another similar effort that @NickNaso mentioned in the meeting - https://github.com/devongovett/napi-wasm

**Comment by mhdawson** [comment]
Should be node-addon-api version 6.0 release today. Thanks @NickNaso

**Comment by NickNaso** [comment]
node-api-headers v0.0.3 has been released.

**Comment by NickNaso** [comment]
Deno v1.31 stabilize Node-API implementation more info here: https://deno.com/blog/v1.31#stabilization-of-node-api

**Comment by NickNaso** [comment]
node-api-headers v0.0.4 has been released.

**Comment by mhdawson** [comment]
.net project made public which lets you use .net to build Node.js addons using node-api - https://github.com/microsoft/node-api-dotnet.

**Comment by NickNaso** [comment]
node-api-headers v0.0.5 has been released.

**Comment by NickNaso** [comment]
node-api-headers v1.0.0 has been released.

**Comment by NickNaso** [comment]
node-addon-api v6.1.0 has been released.

**Comment by vmoroz** [comment]
JSI implementation for Node-API is released in its own repo: https://github.com/microsoft/node-api-jsi
It is an updated version of the code that was previously part of [v8-jsi](https://github.com/microsoft/v8-jsi) and [RNW](https://github.com/microsoft/react-native-windows) repos.
[JSI](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactCommon/jsi/jsi) is a C++ JS engine API implemented by Meta for [React Native](https://github.com/facebook/react-native).

The [Node-API for .Net](https://github.com/microsoft/node-api-dotnet) project started to publish [NPM](https://www.npmjs.com/package/node-api-dotnet) and [Nuget](https://www.nuget.org/packages/Microsoft.JavaScript.NodeApi) packages.
There was a new [presentation](https://htmlpreview.github.io/?https://github.com/microsoft/node-api-dotnet/blob/main/Docs/presentation2.html) shown internally at Microsoft.

**Comment by NickNaso** [comment]
node-api-headers v1.0.1 has been released.

**Comment by Brooooooklyn** [comment]
https://napi.rs/ ecosystem is growing, [napi](https://crates.io/crates/napi) crate has been downloaded around **4 million** times

**Comment by legendecas** [comment]
Node-API version 9 has been landed: https://github.com/nodejs/node/pull/48151.

**Comment by NickNaso** [comment]
node-api-headers v1.1.0 has been released.

**Comment by gabrielschulhof** [comment]
node-canvas was ported to Node-API: https://github.com/Automattic/node-canvas/pull/2235

**Comment by mhdawson** [comment]
New SemVer minor version of Node-API released last week, planning to do a SemVer major release to next week to drop support for Node.js 16.x

**Comment by legendecas** [comment]
It was the end of 2023. Please post any news on https://github.com/nodejs/abi-stable-node/issues/459. Closing this one.

**Comment by UlisesGascon** [comment]
If we decide to use a different issue, we need to update the references in https://github.com/nodejs/nodejs-news-feeder/blob/main/config.json#L28 and in https://github.com/nodejs/node/blob/main/doc/contributing/sharing-project-news.md?plain=1#L31, just to keep the automation updated. ~~I will create the PRs for this change in a moment~~
