### ISSUE TITLE
Improve score on OpenSSF scorecard

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#450]
https://deps.dev/project/github/nodejs%2Fnode-addon-api
https://deps.dev/project/github/nodejs%2Fnode-addon-examples

**Comment by mhdawson** [comment]
- Kevin mentioned branch protection in the last meeting.

**Comment by KevinEady** [comment]
### node-addon-api ([scorecard](https://deps.dev/project/github/nodejs%2Fnode-addon-api))

- Branch-Protection
  - Add branch protection on `main` (For GitHub, check out the steps [here](https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule).)
  - Delete unused branches `v2.x-staging`, `v1.x-staging`
- Code-Review
  - Make "code reviews" mandatory in your repository configuration. ([Instructions for GitHub.](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#require-pull-request-reviews-before-merging))
  - Enforce the rule for administrators / code owners as well. ([Instructions for GitHub.](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#include-administrators))
- Add fuzzing...? ([scorecard criteria](https://github.com/ossf/scorecard/blob/main/docs/checks.md#fuzzing), [nodejs example](https://github.com/google/oss-fuzz/tree/master/projects/nodejs))

### node-addon-examples ([scorecard](https://deps.dev/project/github/nodejs%2Fnode-addon-examples))

- Add branch protection on `main`
- Add LICENSE file
- Make code reviews mandatory (as well as for administrators)
- Make GitHub Actions CI workflow tokens read-only
- Add CodeQL scanning similar to `node-addon-api`...?
- Add fuzzing...?

**Comment by mhdawson** [comment]
Add branch protection for both node-addon-api and node-addon-examples.

**Comment by mhdawson** [comment]
PR to add boilerplate files to node-addon-examples - https://github.com/nodejs/node-addon-examples/pull/213

**Comment by mhdawson** [comment]
@KevinEady can you expand a bit on `Make GitHub Actions CI workflow tokens read-only`

**Comment by mhdawson** [comment]
PR to add best practices to node-addon-api - https://github.com/nodejs/node-addon-examples/pull/214

**Comment by KevinEady** [comment]
Hi  @mhdawson,

> ... can you expand a bit on `Make GitHub Actions CI workflow tokens read-only`

From [Assigning permissions to jobs - GitHub Docs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs):

> You can use `permissions` to modify the default permissions granted to the GITHUB_TOKEN, adding or removing access as required, so that you only allow the minimum required access.

This is for the principle of least privilege, as discussed in the [Token-Permissions Check documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions).

This was mostly addressed by the SecurityBot PR https://github.com/nodejs/node-addon-examples/pull/214 , eg: https://github.com/nodejs/node-addon-examples/pull/214/commits/a05f82c2fc9fc2b6b3668de65ce057b053fab6c8#diff-e98936aa52a6dd7416e4296e9628456227d834f7245967383fd9ff80fd985dadR9-R11 but it skipped a workflow that I added to the PR in [this commit](https://github.com/nodejs/node-addon-examples/pull/214/commits/183ed493b13d35e3c236c43018bac5ee280362e0).

So once this PR is merged, we can say that the Token-Permissions issue has been addressed and we will receive full points.

**Comment by mhdawson** [comment]
@KevinEady I think I merged the PR you mentioned, so we should be able to close this now?
