### ISSUE TITLE
Consider changing the license for examples to MIT

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#456]
We have several examples in the node-addon-examples repo that are licensed ISC. I suspect this is because `npm init` by default sets the license to ISC. Some do not mention a license, and a few licenses are MIT though:

```bash
$ git grep -nHE 'license.?:'
a-first-project/node-addon-api/package.json:15:  "license": "ISC"
napi-asyncworker-example/node-addon-api/package.json:22:  "license": "MIT"
object-wrap-demo/node-addon-api/package.json:15:  "license": "ISC"
promise-callback-demo/node-addon-api/package.json:17:  "license": "ISC"
website/docs/getting-started/first.md:55:license: (ISC)
website/docs/getting-started/helloworld.md:50:license: (ISC) 
website/docs/getting-started/objectwrap.md:57:license: (ISC)
website/package.json:14:  "license": "MIT",
```

Shall we consider harmonizing the licenses?

**Comment by mhdawson** [comment]
@gabrielschulhof we might need the ok from the contributors to each of the examples to change the licence.  Can you take a look at who the people for have contributed to the examples are so that we can see how hard it might be to get the oks?

**Comment by gabrielschulhof** [comment]
All the relevant PRs have landed.
