### ISSUE TITLE
NODE_EXTERN napi_value napi_run_script(napi_env e, const char *script);

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#51]
I realized from https://github.com/nodejs/abi-stable-node/pull/33#issuecomment-270559877 that we may want to have such an API because AFAIK all engines provide this functionality.

**Comment by mhdawson** [comment]
Have we seen any modules need to do it ?  Thinking we should keep the api surface small, so unless we have examples where modules are using eval we might want to leave it out for now.

**Comment by gabrielschulhof** [comment]
@levimm has use for such an API.
