### ISSUE TITLE
AdjustExternalMemory

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#52]
While [porting the canvas package to NAPI](https://github.com/nodejs/abi-stable-node/issues/41), I found the canvas code calls `Nan::AdjustExternalMemory()` in a few places, to give some hints to the V8 GC. That NAN API is a wrapper around `v8::Isolate::AdjustAmountOfExternalAllocatedMemory()`. It's not critical for the functionality, but I assume it improves GC behavior significantly when working with large amounts of externally-allocated memory (image buffers in the case of canvas).

This is a V8-specific API; JSRT does not appear to have an equivalent. Do we need to expose it in NAPI? Possibly it could be implemented as a no-op on other engines.

**Comment by mhdawson** [comment]
https://github.com/nodejs/node/issues/13928

**Comment by digitalinfinity** [comment]
I think this has been addressed in https://github.com/nodejs/node/pull/14310. Feel free to reopen nodejs/node#13928 if you disagree.
