### ISSUE TITLE
C++ helper classes

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#53]
Code that is converted from V8's C++ classes to NAPI's C function  calls is often a little more verbose, e.g. `napi_get_number_from_value(env, v)` vs  `v->NumberValue()`. This could be cleaned up somewhat by adding low/zero-overhead C++ helper classes in NAPI, allowing for more V8 style interaction with objects, and therefore easier porting.

**Comment by jasongin** [comment]
PR at https://github.com/nodejs/abi-stable-node/pull/88

**Comment by aruneshchandra** [comment]
This is landed already 
https://github.com/nodejs/abi-stable-node-wrapper/commit/fe1d9fd5a2fa898f09695faeb40f5b251b162517
