### ISSUE TITLE
napi_call_function scope parameter

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#64]
NAPI's call-function API is defined like this:

```C++
napi_value napi_call_function(napi_env e, napi_value scope,
                              napi_value func, int argc, napi_value* argv);
```

What is that scope parameter supposed to be? Both the V8 and JSRT implementations treat it as the `this` argument for the function call, which makes sense except for the `scope` parameter name. Is the parameter mis-named?

This name confusion apparently has caused a problem in the function test case, which [passes a `napi_escapable_handle_scope` as the scope parameter after casting it to a `napi_value`](https://github.com/nodejs/abi-stable-node/blob/api-prototype-8.x/test/addons-abi/test_function/test_function.cc#L21-L24). When running the test on a NAPI V8 branch, the test passes, I assume because the function itself does not reference its `this` arg. But on the chakracore branch, the JSRT function call tries to validate that the parameter is an Object and returns an error code, so the function call fails.

**Comment by gabrielschulhof** [comment]
I think that should be `context`, not scope.

**Comment by gabrielschulhof** [comment]
... or `thisValue`, though that's an awkward name.

**Comment by jasongin** [comment]
Related to this, I think napi_get_global_scope is also mis-named, it should probably be napi_get_global_object.
