### ISSUE TITLE
How do we distinguish between own and prototype properties? 

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#67]
Moving @fhinkel's comment from #33  to an issue:

> Not V8 related, but do we need methods for own properties as well? Also, do we need a method that returns the property without invoking getters and interceptors (similar to v8::GetRealNamedProperty)?

**Comment by gabrielschulhof** [comment]
Actually this seems to be a major difference between 8.x and 6.2.0. On the latter, `napi_get_property()` will walk up the prototype chain, but in 8.x, the same function will only retrieve own properties. Maybe we have to be explicit about whether to walk up the prototype chain or not.

I think we need
```C++
napi_status napi_get_own_property(napi_env e,
                                  napi_value o,
                                  napi_propertyname p,
                                  napi_value* result);
```
which never walks up the prototype chain, and ensure that `napi_get_property()` always walks up the prototype chain.

**Comment by mhdawson** [comment]
https://github.com/nodejs/node/issues/13925

**Comment by digitalinfinity** [comment]
I think this has been addressed by PR https://github.com/nodejs/node/pull/14063. Feel free to reopen  nodejs/node#13925 if that's not the case.
