### ISSUE TITLE
../src/node_jsvmapi.cc:192:3: error: ‘interface’ does not name a type

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/abi-stable-node#69]
The error handling modifications fail to build with GCC.

**Comment by gabrielschulhof** [comment]
@boingoing ^

**Comment by boingoing** [comment]
This line is:
```c++
interface CallbackWrapper {
...
```
Does the 'interface' keyword not exist in GCC? Is 'interface' an ISO standard keyword? I'm actually not sure. Looks like it might be an MSVC-specific #define. Maybe we should replace this with class or struct for compliance sake?

**Comment by gabrielschulhof** [comment]
I think so. It certainly doesn't build out of the box.

**Comment by boingoing** [comment]
@jasongin 
Seems like replacing 'interface' with 'struct' should solve the issue. Is there a reason to use 'interface'? I'm actually not super familiar with it.

**Comment by boingoing** [comment]
There is another build issue on gcc, too, so I started a PR. https://github.com/nodejs/abi-stable-node/pull/70

**Comment by jasongin** [comment]
Yes, `interface` is just an alias for `struct`, supported by MSVC but not GCC. I had a habit of using `interface` from Windows programming, since it explicitly declares the intent for the struct to only have abstract methods. But it's certainly not required.

**Comment by jasongin** [comment]
Fixed by https://github.com/nodejs/abi-stable-node/commit/5ae919aa7e040ea1238605778ce8a5f33a91a480
