### ISSUE TITLE
Add ci jobs for abi-stable-node

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#71]
Based on recent discussion its probably time to add CI jobs as a safety net.  We should use the core node.js infrastructure so we can easily integrate the jobs into the regular regression tests once we merge into master.

I'm starting the process following : 

https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md

**Comment by mhdawson** [comment]
@nodejs/abi-stable-node

**Comment by mhdawson** [comment]
Created https://github.com/nodejs/build/issues/604 in build repo to outline next steps and get agreement.  Will configure initial blank jobs once that is in palce.

In the mean time we should get a list of jobs we should put in place.  My starting lis:

1) Build Node.js from branch, run abi stable add-on tests, validate all ran ok
2) Build Node.js from branch, install nanomsg, run tests, validate all ran ok 
3) Build Node.js from branch, install leveldown, run tests, validate all ran ok


We can then run these when required to test changes, and I'd also think we'd want to run nightly on 8.x and 6.x.

I'd also like to seem then all running across all of the supported os/platform combinations if possible. (linux, windows, AIX, x86, power, 390, etc.)

**Comment by mhdawson** [comment]
@gabrielschulhof is there a time we can meet this week to discuss this ?

**Comment by gabrielschulhof** [comment]
@mhdawson How about tomorrow before or after the meeting?

**Comment by mhdawson** [comment]
Sampson has been working on this so re-assigned.

**Comment by aruneshchandra** [comment]
woking on adding nanomsg, sqllite and node-sass while waiting to figure out issues with other modules

**Comment by digitalinfinity** [comment]
We have a job- we can have separate issues for specific changes we want to make to it
