### ISSUE TITLE
Revisit need for napi_set_function_name

### ISSUE THREAD

**Issue by boingoing** [nodejs/abi-stable-node#78]
ChakraCore (and possibly other engines) do not support changing the function name after creating a function. Let's add an optional name parameter to napi_create_function instead. If it's possible, can we also remove napi_set_function_name?

**Comment by mhdawson** [comment]
@boingoing do we know if any of the existing ports or examples use napi_set_function_name ? 
I agree that it should not be part of the API if it is not possible to support across engines.

**Comment by boingoing** [comment]
Resolved by #142
