### ISSUE TITLE
Measure NAPI perf for nanomsg perf benchmark

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#8]

**Comment by boingoing** [comment]
Here is a dump of the perf numbers with a summary at the end:

V8	|	Napi
-----------------------	|	-----------------------
real    0m10.998s	|	real    0m11.212s
user    0m1.968s	|	user    0m1.956s
sys     0m0.588s	|	sys     0m0.624s
-----------------------	|	-----------------------
real    0m10.967s	|	real    0m11.105s
user    0m1.980s	|	user    0m1.992s
sys     0m0.552s	|	sys     0m0.580s
-----------------------	|	-----------------------
real    0m10.886s	|	real    0m11.172s
user    0m1.940s	|	user    0m1.948s
sys     0m0.560s	|	sys     0m0.620s
-----------------------	|	-----------------------
real    0m11.033s	|	real    0m11.120s
user    0m1.960s	|	user    0m1.944s
sys     0m0.596s	|	sys     0m0.604s
-----------------------	|	-----------------------
real    0m10.998s	|	real    0m11.193s
user    0m1.940s	|	user    0m2.000s
sys     0m0.636s	|	sys     0m0.552s
-----------------------	|	-----------------------
real    0m11.098s	|	real    0m11.000s
user    0m1.972s	|	user    0m1.960s
sys     0m0.580s	|	sys     0m0.564s
-----------------------	|	-----------------------
real    0m10.984s	|	real    0m11.091s
user    0m1.912s	|	user    0m1.968s
sys     0m0.608s	|	sys     0m0.576s
-----------------------	|	-----------------------
real    0m10.949s	|	real    0m11.119s
user    0m1.932s	|	user    0m1.928s
sys     0m0.576s	|	sys     0m0.608s
-----------------------	|	-----------------------
real    0m11.051s	|	real    0m11.137s
user    0m1.944s	|	user    0m1.936s
sys     0m0.588s	|	sys     0m0.596s
-----------------------	|	-----------------------
real    0m10.945s	|	real    0m11.225s
user    0m1.960s	|	user    0m1.952s
sys     0m0.600s	|	sys     0m0.600s
-----------------------	|	-----------------------
real    0m10.910s	|	real    0m10.912s
user    0m1.964s	|	user    0m1.968s
sys     0m0.576s	|	sys     0m0.588s
-----------------------	|	-----------------------
real    0m11.371s	|	real    0m10.954s
user    0m1.912s	|	user    0m1.924s
sys     0m0.600s	|	sys     0m0.624s
-----------------------	|	-----------------------
real    0m11.112s	|	real    0m11.004s
user    0m1.980s	|	user    0m1.944s
sys     0m0.556s	|	sys     0m0.640s
-----------------------	|	-----------------------
real    0m10.945s	|	real    0m11.148s
user    0m1.984s	|	user    0m1.932s
sys     0m0.524s	|	sys     0m0.648s
-----------------------	|	-----------------------
real    0m10.975s	|	real    0m11.018s
user    0m1.996s	|	user    0m1.956s
sys     0m0.496s	|	sys     0m0.588s
-----------------------	|	-----------------------
avg(real) 11.0148	|	avg(real) 11.094 (+0.7%)

**Comment by aruneshchandra** [comment]
We should use this issue for perf measurements after the error handling completed.

**Comment by aruneshchandra** [comment]
Closing this issue. Perf measurement after error handling will be covered via issue #57
