### ISSUE TITLE
Measure perf for node-sass after conversion

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/abi-stable-node#82]

**Comment by boingoing** [comment]
Node-sass-napi binary built from https://github.com/boingoing/node-sass/commit/b663dcfea188592c5469c87da6b13f6307bb7264
Node-sass-nan binary built from https://github.com/sass/node-sass/commit/cc7c3b37ba65fe5c7ebd0965c16e086abec57f3b
Node-V8 8.x built from https://github.com/nodejs/abi-stable-node/commit/75e28c5e735af71404578d189ec2533c4b356cc5

Performance is measured via this suite:
https://github.com/eoneill/node-sass-perf-test

The performance test doesn't drill-down into specific areas or APIs to give details on what is taking up the time, we just have an overall execution time.

node-sass Nan on V8-Node 8.x | node-sass NAPI on V8-Node-Napi 8.x
--- | ---
12ms | 13ms
12ms | 14ms
13ms | 12ms
12ms | 17ms
13ms | 13ms
17ms | 12ms
13ms | 15ms
12ms | 12ms
12ms | 12ms
12ms | 12ms
24ms | 12ms
11ms | 12ms
13ms | 24ms
15ms | 13ms
13ms | 13ms
12ms | 12ms
13ms | 15ms
11ms | 12ms
12ms | 12ms
12ms | 12ms
**avg = 13.2ms** | **avg = 13.45ms (+1.9%)**

Tests run on a Windows machine with this hardware:
Intel Xeon E5-1620 v3 @ 3.50GHz
16GB DDR4 @ 2133MHz
Samsung XP941 SSD
