### ISSUE TITLE
Can we move weekly meeting time + or - 1 hour

### ISSUE THREAD

**Issue by mhdawson** [nodejs/abi-stable-node#92]
Can we move the weekly meeting to 1EST or 3 EST ? 

I have a meeting I really need to attend at our current 2 pm EST slot that I don't think I can get moved.

**Comment by sampsongao** [comment]
I am ok for both 1 and 3.

**Comment by aruneshchandra** [comment]
Can we do Thursday 1 pm EST (10 am PST) instead ?

**Comment by gabrielschulhof** [comment]
I'm also OK for Friday 1 PM and 3 PM Eastern.

**Comment by mhdawson** [comment]
I could do 1:30 EST on Thrusday.

**Comment by aruneshchandra** [comment]
I can do 1.30 EST on Thursday. Are we talking about just this week or recurring? I'm ok with both.

**Comment by mhdawson** [comment]
Recurring.

**Comment by mhdawson** [comment]
@gabrielschulhof Does 1:30 EST on Thursdays work for you ?

**Comment by gabrielschulhof** [comment]
Yeah, I can do that.

**Comment by mhdawson** [comment]
We on for today for this week at 1:30 EST (10 mins from now ?)

**Comment by gabrielschulhof** [comment]
I'm lurking ...

**Comment by mhdawson** [comment]
I'm going to be 5 mins late if we are as I really need to eat something before the meeting.

**Comment by mhdawson** [comment]
Ok looks like we'll do regular time tomorrow and then shift for the upcoming weeks.

**Comment by aruneshchandra** [comment]
sorry - we missed it! yea let's do it regular time tomorrow and then shift to the new timing from next week onwards.
