### ISSUE TITLE
Deleting properties

### ISSUE THREAD

**Issue by jasongin** [nodejs/abi-stable-node#94]
There should be NAPI functions for deleting named properties and indexed properties:
```C
napi_status napi_delete_property(napi_env env, napi_value object, napi_propertyname name);
napi_status napi_delete_element(napi_env env, napi_value object, uint32_t i);
```

This is not super high-priority, since only one of the top native modules I scanned (couchbase) referenced `v8::Object::Delete()`.

**Comment by mhdawson** [comment]
https://github.com/nodejs/node/issues/13924

**Comment by digitalinfinity** [comment]
Addressed in https://github.com/nodejs/node/pull/13934
